### ISSUE TITLE
DB-Errors, SQL Query Errors and a question

### ISSUE THREAD

**Issue by ShoXikologe** [ZhengPeiRu21/mod-individual-progression#1]
Hi! At first i would like to thank you for this module. I really like the idea of it and i'm excited to try it out. 
I hope you will put it in the AC catalogue aswell, so it's get's more traction.

Secondly i have a question about the pre-AQ quests. In the config file it says: 
> Please note that this is a very grindly quest chain requiring quests to be completed 200+ times - to make this more reasonable, some optional quest nerfs can be found in the module's SQL files.

Unfortunately i couldn't find anything in that regard. Is there a change i have to make or is it already included?

I saw in the **boss_drakkisath.cpp** you weren't sure about the Thunderclap Spell ID
```
boss_drakkisath.cpp

creature_template: 10363
creature_template_spell: 23462,20691,23023,23931 (don't know if that helps)
SPELL_THUNDERCLAP = 23931 (not 15548)

[Classic](https://classic.wowhead.com/spell=23931/thunderclap)
[WOTLK with SpellID](https://db.rising-gods.de/?spell=23931)
```
While applying the SQL files **manually** in HeidiSQL (i know, i'm new), there were some errors and a warning.

**SQL's not used:**
optional_remove_quest_markers.sql
transports.sql
### SQL Query Errors:
```
mounts_and_riding.sql (row 2)

WARNING: Run unsafe queries without a WHERE clause?
(`disables`WHERE <- missing space)
SOLUTION: DELETE FROM `disables` WHERE `sourceType`=1 AND `entry` IN (3631, 4487, 4488, 4489, 4490);


quest_missing_diplomat.sql (row 7,16,21,22,24)

INSERT INTO creature_queststarter(id, quest) VALUES (1748, 11223);
ERROR: SQL Error (1062): Duplicate entry '1748-11223' for key 'PRIMARY'

UPDATE creature_questender SET id=1748 WHERE quest=396;
ERROR: SQL Error (1062): Duplicate entry '1748-396' for key 'PRIMARY'

UPDATE creature_queststarter SET id=1748 WHERE quest=396;
ERROR: SQL Error (1062): Duplicate entry '1748-396' for key 'PRIMARY'

UPDATE creature_queststarter SET id=1748 WHERE quest=6182;
ERROR: SQL Error (1062): Duplicate entry '1748-6182' for key 'PRIMARY'

UPDATE creature_queststarter SET id=1748 WHERE quest=7782;
ERROR: SQL Error (1062): Duplicate entry '1748-7782' for key 'PRIMARY'
```
After successfully compling, the database would spit out some errors.
### DB-Errors:
```
> Incorrect value '315' for type 'unsigned char'. Value is raw ? 'false'
> Table name 'item_template'. Field name 'fire_res'

> Incorrect value '315' for type 'unsigned char'. Value is raw ? 'false'
> Table name 'item_template'. Field name 'nature_res'

> Incorrect value '315' for type 'unsigned char'. Value is raw ? 'false'
> Table name 'item_template'. Field name 'frost_res'

> Incorrect value '315' for type 'unsigned char'. Value is raw ? 'false'
> Table name 'item_template'. Field name 'shadow_res'

> Incorrect value '315' for type 'unsigned char'. Value is raw ? 'false'
> Table name 'item_template'. Field name 'arcane_res'

> Incorrect value '-10' for type 'unsigned char'. Value is raw ? 'false'	(-> therefore 'Petrospill Leggings' (9509) don't show the '-10 Fire Resistance' stat on the item)
> Table name 'item_template'. Field name 'fire_res'

> Incorrect value '-50' for type 'unsigned char'. Value is raw ? 'false'
> Table name 'item_template'. Field name 'holy_res'

> Incorrect value '-50' for type 'unsigned char'. Value is raw ? 'false'
> Table name 'item_template'. Field name 'fire_res'

> Incorrect value '-50' for type 'unsigned char'. Value is raw ? 'false'
> Table name 'item_template'. Field name 'nature_res'

> Incorrect value '-50' for type 'unsigned char'. Value is raw ? 'false'
> Table name 'item_template'. Field name 'frost_res'

> Incorrect value '-50' for type 'unsigned char'. Value is raw ? 'false'
> Table name 'item_template'. Field name 'shadow_res'

Creature (Entry: 12580) has assigned gossip menu 12580, but npcflag does not include UNIT_NPC_FLAG_GOSSIP (1).

Table `creature` have creature (SpawnId: 156950 Entries: 12397, 0, 0) with a `creature_template`.`flags_extra` in one or more entries including CREATURE_FLAG_EXTRA_INSTANCE_BIND but creature are not in instance.
Table `creature` have creature (SpawnId: 156950 Entries: 12397, 0, 0) with `MovementType`=0 (idle) have `wander_distance`<>0, set to 0.

Table `creature_queststarter` has creature entry (3412) for quest 2841, but npcflag does not include UNIT_NPC_FLAG_QUESTGIVER
Table `creature_queststarter` has creature entry (3412) for quest 2950, but npcflag does not include UNIT_NPC_FLAG_QUESTGIVER

Table `creature_questender` has creature entry (3412) for quest 2841, but npcflag does not include UNIT_NPC_FLAG_QUESTGIVER
Table `creature_questender` has creature entry (3412) for quest 2949, but npcflag does not include UNIT_NPC_FLAG_QUESTGIVER
Table `creature_questender` has creature entry (3412) for quest 2950, but npcflag does not include UNIT_NPC_FLAG_QUESTGIVER

Table 'creature_loot_template' Entry 10184 isn't creature entry and not referenced from loot, and thus useless.

Table 'creature_loot_template' Entry 12129 isn't creature entry and not referenced from loot, and thus useless.

addToGossipMenuItems: GossipMenuId 5747 Item 60040 not found
Not handled grouped condition, SourceGroup 5747

addToGossipMenuItems: GossipMenuId 5747 Item 60040 not found
Not handled grouped condition, SourceGroup 5747

Script named 'spell_bwl_chromaggus_time_lapse_60_2_A' is not assigned in the database.
Script named 'gobject_ipp_wotlk' is not assigned in the database.
```

**Comment by ZhengPeiRu21** [comment]
Thank you for the helpful and detailed report! None of these errors should prevent playable, but can be fixed. I will create an update to solve them as I can. The negative resistances error may require a change to AzerothCore upstream to support, but I can create a PR with that update if needed.

For the AQ quest, you are correct, it seems I did not check in that SQL file! I will push an update to add the missing file.

Thank you for willing to test the project! Please let me know if you are encountering any more issues.

**Comment by ZhengPeiRu21** [comment]
With the latest updates, all SQL errors should be resolve, so I am going to close this issue. Please re-open if you are continue to see any problem. Thank you!

**Comment by ShoXikologe** [comment]
So, I recently switched to **MySQL 8.0.29** and updated the module, only to find out that I couldn't apply the **restore_vanilla_elites.sql**. Here is the error message i got:
```
SQL Error (1064): You have an error in your SQL syntax;
check the manual that corresponds to your MySQL server version 
for the right syntax to use near 'rank=1 WHERE entry=314" at line 2
```
I removed line 2 to see if it works, just to discover that the error repeated for the next line,
which leaves me to believe that this affects all lines.

Here is a screenshot of the query in **HeidiSQL**:

### restore_vanilla_elites.sql

![syntax-error](https://user-images.githubusercontent.com/106157609/178350579-577d366e-1ff2-45ea-9ba7-1353bda905fb.jpg)

I also think I discovered the problem. The **'rank'** part should be in green-ish instead of blue (sorry, I don't know the technical terms) since it's one of the columns in "creature_template".

By right-clicking "rank" and selecting "SQL help" in the dropdown menu, "rank" is listed as a "window function" under "functions". 
(I really don't know if that has anything to do with it)

-----------------------------------------------------------------------------------------------------------------------------------

Oh, and the **mounts_and_riding.sql** still needs a fix for it's spacing error. (see original post)

On top of that, there are also some new errors in the **DBError.log**.
(there are still some from the original post, I'm listing only the new ones here, although tell me if you need the old ones again):
### DB-Errors:
```
Creature (Entry: 11679, class 2) has different `unit_class` in difficulty 1 mode (Entry: 22796, class 1).
Creature (Entry: 12157, class 2) has different `unit_class` in difficulty 1 mode (Entry: 22792, class 1).
Creature (Entry: 13419, class 2) has different `unit_class` in difficulty 1 mode (Entry: 22627, class 1).
Creature (Entry: 13539, class 2) has different `unit_class` in difficulty 1 mode (Entry: 22532, class 1).
Creature (Entry: 13541, class 2) has different `unit_class` in difficulty 1 mode (Entry: 22774, class 1).
Creature (Entry: 13542, class 2) has different `unit_class` in difficulty 1 mode (Entry: 22534, class 1).
Creature (Entry: 13548, class 2) has different `unit_class` in difficulty 1 mode (Entry: 22529, class 1).
Creature (Entry: 13557, class 2) has different `unit_class` in difficulty 1 mode (Entry: 22537, class 1).
Creature (Entry: 13956, class 2) has different `unit_class` in difficulty 1 mode (Entry: 22790, class 1).
Creature (Entry: 13958, class 2) has different `unit_class` in difficulty 1 mode (Entry: 22791, class 1).
Creature (Entry: 14021, class 2) has different `unit_class` in difficulty 1 mode (Entry: 22599, class 1).
Creature (Entry: 16505, class 8) has different `unit_class` in difficulty 1 mode (Entry: 29273, class 1).

Creature (GUID: 88165) does not exist but has a record in `creature_addon`
Creature (GUID: 88166) does not exist but has a record in `creature_addon`
```

Finally there are some **config errors** in the **Server.log**:

### Config-Errors in Server.log:
```
Config: Missing property IndividualProgression.VanillaHealingAdjustment in all config files, at least the .dist file must contain: "IndividualProgression.VanillaHealingAdjustment = 1.000000"

Config: Bad value defined for name 'IndividualXp.Announce', going to use 'true' instead
```

**Comment by ZhengPeiRu21** [comment]
Sorry, I did not see your comment earlier! Thank you for the corrections! I will make these fixes.

**Comment by Grim93** [comment]
From the latest update 'The True Masters questline fixes'

quest_missing_diplomat.sql
/* SQL Error (1062): Duplicate entry '1748-11223' for key 'creature_queststarter.PRIMARY' */

**Comment by ZhengPeiRu21** [comment]
> From the latest update 'The True Masters questline fixes'
> 
> quest_missing_diplomat.sql /* SQL Error (1062): Duplicate entry '1748-11223' for key 'creature_queststarter.PRIMARY' */

Thank you for the reporting, it looks like there was a typo causing a re-run of the SQL file to give an error. This is fixed in the latest update.

**Comment by ZhengPeiRu21** [comment]
With commit https://github.com/ZhengPeiRu21/mod-individual-progression/commit/23e25e7b34300a7124223496569e0c06ebb60ad6, all SQL errors and DB import errors should be resolve, except for one warning about negative resistance with is waiting for this AC PR to merge: https://github.com/azerothcore/azerothcore-wotlk/pull/12958

I am going to close this issue, but please re-open or post new issue if you see any additional errors! Thank you for reporting.
