### ISSUE TITLE
Titles not awarded

### ISSUE THREAD

**Issue by VladonAbaddon** [ZhengPeiRu21/mod-individual-progression#103]
Certain prestige titles are not awarded to players (the ones that were given in Classic and TBC versions but removed in WOTLK):

- Scarab Lord not awarded after AQ attunement (you still get the achievement).
- Champion of the Naaru not awarded after Serpentshrine Cavern and Tempest Keep attunements.
- Hand of A'dal not awarded after finishing Black Temple attunement (but the achievement is awarded).

**Comment by AlvinZhu** [comment]
confirmed.

I will fix it and submit a PR.

**Comment by ZhengPeiRu21** [comment]
Fixing the TBC title issues may require a custom script. It looks like AC does not yet have a way to trigger the hidden auto-complete flag quest (https://www.wowhead.com/quest=11116/trial-of-the-naaru-quest-flag) that actually awards the TBC titles:
https://github.com/ZhengPeiRu21/mod-individual-progression/issues/102#issuecomment-1482017020

**Comment by AlvinZhu** [comment]
https://github.com/ZhengPeiRu21/mod-individual-progression/pull/125
I try to fix this issue.
and I tested. it works as expect.

also fix part of this issue:
https://github.com/ZhengPeiRu21/mod-individual-progression/issues/102

**Comment by ZhengPeiRu21** [comment]
AlvinZhu has fixed this issue in https://github.com/ZhengPeiRu21/mod-individual-progression/pull/125. Please report any addition problems!
