### ISSUE TITLE
IndividProg with ARAC

### ISSUE THREAD

**Issue by deadcorpseeater** [ZhengPeiRu21/mod-individual-progression#106]
is it real? I have my own ideas about the game (I like to tank playing pal, but also my favourite race is forsaken). I'd like to play the paladin from Lordaeron who has been fallen in the third war, but still have holy power. (somehow holy priests can use holy magic o_O)

**Comment by ZhengPeiRu21** [comment]
If you would please link the ARAC module you would like to use, I will check if there are any compatibility problems.

**Comment by deadcorpseeater** [comment]
> If you would please link the ARAC module you would like to use, I will check if there are any compatibility problems.

https://github.com/heyitsbench/mod-arac

here it is! the main problem is there's no class related quests for pala undead, for example. this module let you play any race any class. that's what ARAC means.

**Comment by deadcorpseeater** [comment]
> I have briefly reviewed the module and don't think there would be any obvious compatibility issues. Class quests usually check only the class and not race, so an undead paladin would be able to complete Blood Elf paladin quests. Though I'm not able to formally support compatibility with all other modules, lease let me know if you encounter any specific issues and I will see if it is possible to accommodate them.

thank you for your answer, I'll try it someday
