### ISSUE TITLE
Are Priest Racial quests and skills in this mod?

### ISSUE THREAD

**Issue by Kuiriel** [ZhengPeiRu21/mod-individual-progression#108]
Per https://github.com/ZhengPeiRu21/mod-individual-progression/issues/16 I thought that the unique Priest racials were available.

However I have created a level 14 priest and the relevant quest for [Touch of Weakness](https://www.wowhead.com/classic/quest=5658/touch-of-weakness) is not appearing in the Undercity at [Aelthalyste](https://www.wowhead.com/classic/npc=4606/aelthalyste)?

Have I done something wrong?

I'm not sure how it would play out anyway as Devouring Plague is something you get when levelling anyway, but it's flavor anyway. No pressure.

**Comment by ZhengPeiRu21** [comment]
Thank you for asking, I should have given more explain in the original issue when it was closed.

Priest spells were not re-implemented. The data for most of the spells has been totally removed from the client, so restoring them would require a custom patch. If this was the only problem that would be okay - we already have a custom patch to restore rogue poison crafting, which was also removed - but it is troubled with a number of other issues. Many of the spells still exist in their WotLK form and are given to all races with the same names and IDs, and there is also the question of considering that the spells would still be usable at end-game, so it could affect balance. Finally, the quests themselves did not have any content other than speaking to your trainer and receiving the spell, so there is no interesting lore or playable content to restore. Between these things together, I decided not to re-implement the Priest racials.

Please let me know if you think this is not the best solution, and I will re-consider!

**Comment by Kuiriel** [comment]
You chose the best solution. Thank you for kindly explaining it.
