### ISSUE TITLE
[SQL] dungeon_the_stockades.sql incorrect faction ID causes lag on stormwind harbor

### ISSUE THREAD

**Issue by XSNomad** [ZhengPeiRu21/mod-individual-progression#11]
Need to remove
Line 7,8

`-- Defias Prisoner
UPDATE `creature_template` SET `maxlevel`=24, `faction`=17 WHERE `entry`=1706;`

Current
![image](https://user-images.githubusercontent.com/60951221/187801147-2c9c3784-cb75-45c1-a2ce-47f9dc2a8d8a.png)
![image](https://user-images.githubusercontent.com/60951221/187801162-aeb753b1-057d-467e-8365-b4916f0fc39a.png)
![image](https://user-images.githubusercontent.com/60951221/187801193-2308720a-87e8-4a6c-93ba-b141527b869d.png)

Expected
![image](https://user-images.githubusercontent.com/60951221/187801208-3b7b3d11-c435-4274-a6f0-7fa89919a0b7.png)
![image](https://user-images.githubusercontent.com/60951221/187801218-8fe14cd2-80de-40a4-bba5-15eb85d78241.png)

Credit: Player Naomi

**Comment by ZhengPeiRu21** [comment]
Fixed in https://github.com/ZhengPeiRu21/mod-individual-progression/commit/8c18a89aca556a77d4b5d5286d6a83bdfec6d2f0. Thank you to player Naomi!
