### ISSUE TITLE
Script to Modify Individual Progression

### ISSUE THREAD

**Issue by Day36512** [ZhengPeiRu21/mod-individual-progression#112]
Hey didn't know how to get a hold of you best so I'm just putting this here. I went ahead and created a lua script that adds an npc into the game that allows players to set their individual progression via gossiping with said npc. May be useful for some people:

https://github.com/Day36512/Acore_Lua_Set_Individual_Progression_NPC

**Comment by ZhengPeiRu21** [comment]
Thank you for sharing! I have added this to a new page on the wiki: https://github.com/ZhengPeiRu21/mod-individual-progression/wiki/Useful-Extras
