### ISSUE TITLE
The missing naaru below the blood knights in farstriders square

### ISSUE THREAD

**Issue by Kuiriel** [ZhengPeiRu21/mod-individual-progression#131]
I note that as a blood elf paladin wandering silvermoon, there is a little discrepancy regarding the state of the captive naaru that powers the blood knights. 

During the first trial quest component there is a moment where a stage quest giver in the naaru chamber refers to the naaru as still being there with them. In the next moment of dialogue he refers instead to tapping light from the dazed magisters who we do still see there. So it could just be a small dialogue discrepancy. 

I imagine that if this was *perfect* individual progression through the eras, though I don't know how much work it would be but I imagine too much, kael thas would be still ruling silvermoon and not have been called out as traitor and the captive naaru would still be present until burning crusade phases were completed. But I expect it would be more practical to just have a burning crusade emulator then instead of work! I think that was during a patch of burning crusade though.

**Comment by ZhengPeiRu21** [comment]
Thank you again for your reports! I think small RP details like this are important to capture correctly, so I'm very appreciate you noticing them and bringing to attention. I'm not very familiar with this event, but I will investigate the best way to implement it.

**Comment by Kuiriel** [comment]
The details about the captive Naaru are here: https://wowpedia.fandom.com/wiki/M%27uru

It looks like he was stolen from the area after Kael'thas's defeat in Tempest Keep, which would have come out with BC to start with.

Looks like a LOT of work adding that sort of stuff back in since it would lean on so much text all pre-WOTLK, I can't imagine it's feasible!

**Comment by ZhengPeiRu21** [comment]
I've done some more research and would like to implement this change, along with reverting the other Silvermoon changes from patch 2.4. I am still trying to find sources for some of the original dialogs, but will do my best to re-create it as accurately as possible. I am less familiar with Horde content, so I appreciate you bringing this to my attention! I will continue to update this issue with progress.

**Comment by Kuiriel** [comment]
Well then this will be awesome and mind blowing stuff, especially if you're able to get it to transform from pre to post BC 2.4 towards some point in BC progression (I guess with suncrown and kael thas etc) ! That must be an insane amount of work. Especially finding old dialogue. 

Does that mean you've also already got the whole changes in undercity that happen with wrathgate betrayal, if I recall correctly?

**Comment by ZhengPeiRu21** [comment]
> Does that mean you've also already got the whole changes in undercity that happen with wrathgate betrayal, if I recall correctly?

Yes, right now Undercity should be in the pre-Wrathgate state. I hope later to add the option to allow it to progress once the player is at the correct point of the timeline, but for now it is statically in the Vanilla state, which fits better than the 3.3.5 post-Wrathgate state.

**Comment by Kuiriel** [comment]
We are not at wrathgate yet for me to test it. Do you have a plan for how the whole invade undercity to kill putress after wrathgate will play out?

**Comment by ZhengPeiRu21** [comment]
These changes have been implemented in https://github.com/ZhengPeiRu21/mod-individual-progression/commit/0bc5148e1c2f5a78bb5a122dbbc4133e674971db. There may still be details to sort out - please feel free to comment or open a new issue if you notice anything else that needs changing.

Sorry I didn't see your earlier question. The Battle for Undercity quests should all work as intended - they use a separate phasing that isn't impacted by Individual Progression changes. At the moment Undercity does not change after the quest is completed; it remains in Vanilla state so that all Vanilla content is still available.
