### ISSUE TITLE
Low level creatures damage too high

### ISSUE THREAD

**Issue by ZhengPeiRu21** [ZhengPeiRu21/mod-individual-progression#132]
Even after 63add43ec2958711dca413d383487a51de596349, low level creatures seem to be dealing too much damage. This is only noticable for the first few levels, but does impact the early leveling experience. Creature stats are the same as Vmangos for these levels, so there might be an underlying formula difference accounting for the additional damage. The issue becomes less impactful as level increases and seems to match Vmangos damage values starting around level 10.

Thanks to MemeMachine on Discord for reporting the bug.

**Comment by bughero999** [comment]
Hi ZhengPeiRu,

First of all a huge thank you for this module, in particular having all these vanilla reversions in one place is amazing and has saved me so much time and effort.

I've been looking into this bug, and I'm kind of an AC noob but I was able to experiment my way into a solution of sorts.

1) You probably know this but the main bug is something to do with creature_class_stats.sql. If you run nothing but this you get the bug. If you run everything but this you don't get it. I don't know the exact reason but by removing this file I was able to get enemy damage roughly equal to Classic Era at low levels.

2) There seems to be a bug with AzerothCore itself where very low level creatures have no variance in their damage, and will always do the lowest amount. So for example a level 1 Young Nightsaber in both Classic Era and Wrath Classic does 1-2, in AC it always does 1 with no variance. I think it has something to do with rounding when the numbers are too low to round correctly. I was able to fix this by making this change to AzerothCore, in C:/AzerothCore/src/server/game/Entities/Unit/StatSystem.cpp, the function Creature::CalculateMinMaxDamage, right below the line:

`maxDamage = ...` on line 1153

I added the line:

`maxDamage = ceil(maxDamage);`

and recompile, that makes it always round up and now I'm getting the exactly correct vanilla damage values on my local server. I'm not confident that this is 100% the correct fix but I think it's on the right track. Anyway I hope this info is of some help!

**Comment by ZhengPeiRu21** [comment]
> Hi ZhengPeiRu,
> 

Thank you for your comment. It's great to know that others are finding the module and its resources useful. I've reached the same conclusion - even though the creature stats appear lower than in Vmangos, low level enemies do actually appear to be doing correct damage amounts (barring the AzerothCore bug itself you mentioned.)

As far as the module is concerned, I do think that disabled the creature class stats adjustments seems to be the right move - I've done so in https://github.com/ZhengPeiRu21/mod-individual-progression/commit/c6e4560c4b72d96c821431b07487dcf43b05a872, so I think we can consider this issue resolved. I'll see what I can do about fixing the bug in AzerothCore itself.

Please reach out if you find anything else that needs to be changed or is missing as you work with the module. Thanks again!
