### ISSUE TITLE
Blood Elf warlock quest missing quest item drop

### ISSUE THREAD

**Issue by olyukha** [ZhengPeiRu21/mod-individual-progression#135]
the quest [Windows to the Source](https://www.wowhead.com/tbc/quest=8344/windows-to-the-source) requires four [Wraith Essence](https://www.wowhead.com/tbc/item=20934/wraith-essence) and one [Tainted Wraith Essence](https://www.wowhead.com/tbc/item=20935/tainted-wraith-essence), but the Tainted Wraith Essence never drops, rendering the quest unable to be completed.

Wraith Essence drops seem unaffected, it's only the Tainted Wraith Essence that doesn't drop.

**Comment by AlvinZhu** [comment]
```sql
INSERT INTO creature_loot_template (Entry, Item, Reference, Chance, QuestRequired, LootMode, GroupId, MinCount, MaxCount, Comment) VALUES (15298, 20935, 0, 80, 1, 1, 0, 1, 1, 'Tainted Arcane Wraith - Tainted Wraith Essence')
```
this should fix it.

**Comment by ZhengPeiRu21** [comment]
Fixed in https://github.com/ZhengPeiRu21/mod-individual-progression/commit/b0d7a07926762a5c245a8e163d0b73789e91120f. Thanks @AlvinZhu!

**Comment by MatthewHinds** [comment]
The undead equivalent is also broken
