### ISSUE TITLE
Minor TBC creature fix

### ISSUE THREAD

**Issue by bkmangx1** [ZhengPeiRu21/mod-individual-progression#136]
These 2 creatures have wrong stats in tbc, caused by these lines from vmangos import. They are old vanilla values, these creature ids were reused in tbc.

https://github.com/ZhengPeiRu21/mod-individual-progression/blob/master/sql/world/base/vanilla_creature_values.sql#L2348
https://github.com/ZhengPeiRu21/mod-individual-progression/blob/master/sql/world/base/vanilla_creature_values.sql#L9866

https://www.wowhead.com/classic/npc=1410/loranna-dawnfyre-unused-reuse-me
https://www.wowhead.com/tbc/npc=1410/firewing-bloodwarder

https://www.wowhead.com/classic/npc=5355/blink-reuse
https://www.wowhead.com/tbc/npc=5355/firewing-defender

**Comment by ZhengPeiRu21** [comment]
Fixed in c18476756291760e23d773ec539c07e34d4c84aa.
