### ISSUE TITLE
NPC Windcaller Proudhorn

### ISSUE THREAD

**Issue by mtompkins** [ZhengPeiRu21/mod-individual-progression#141]
One of the classic quests, "Taking Back Silithus" is missing the needed NPC WIndcaller Proudhorn https://www.wowhead.com/npc=15191/windcaller-proudhorn

**Comment by ZhengPeiRu21** [comment]
Quests that were added with AQ patch, and their related NPCs, are not available until the player has reached the AQ40 phase. Can you confirm that this NPC is missing even when the player is in the correct phase?

**Comment by mtompkins** [comment]
Thank you for the response. I thought this particular question predated AQ. I'll confirm with a character in that phase. Apologies in advance.

**Comment by ZhengPeiRu21** [comment]
I'm going to go ahead and close this issue; if you do continue to notice any problems with this NPC, please feel free to re-open it. Thanks!
