### ISSUE TITLE
fatal error

### ISSUE THREAD

**Issue by houbing2006** [ZhengPeiRu21/mod-individual-progression#144]
azerothcore/modules/mod-individual-progression/src/IndividualProgressionPlayer.cpp:133:69: fatal error: non-virtual member function marked 'override' hides virtual member function
    void OnGiveXP(Player* player, uint32& amount, Unit* /*victim*/) override
                                                                    ^
/root/azerothcore/src/server/game/Scripting/ScriptMgr.h:1038:18: note: hidden overloaded virtual function 'PlayerScript::OnGiveXP' declared here: different number of parameters (4 vs 3)
    virtual void OnGiveXP(Player* /*player*/, uint32& /*amount*/, Unit* /*victim*/, uint8 /*xpSource*/) { }
                 ^
1 error generated.

**Comment by ZhengPeiRu21** [comment]
Thank you for submitting the issue report. This should be fixed in 4ff8d369b3f362bdaaa4445cc5e185e2fee04b76.
