### ISSUE TITLE
the vendors and npc of the trial of the crusader don't appear

### ISSUE THREAD

**Issue by arslenx** [ZhengPeiRu21/mod-individual-progression#145]
Hi, 
I have a problem with Individual Progression tier 14, the vendors and npc of the trial of the crusader don't appear, 
Can it be fixed in the future? or what can be done to make them appear when tier 14 is activated

**Comment by arslenx** [comment]
> Hi, I have a problem with Individual Progression tier 14, the vendors and npc of the trial of the crusader don't appear, Can it be fixed in the future? or what can be done to make them appear when tier 14 is activated

**Comment by thor99157** [comment]
same issues. you might want to change phaseMask
when you use .gm on . npc will shows. 
Implemented in 43ab399 
ipp_aware_npcs.sql set phaseMask to 1

**Comment by ZhengPeiRu21** [comment]
> same issues. you might want to change phaseMask when you use .gm on . npc will shows. Implemented in [43ab399](https://github.com/ZhengPeiRu21/mod-individual-progression/commit/43ab3995d2489b746ced67746a8c29f7f4857397) ipp_aware_npcs.sql set phaseMask to 1

These NPCs will only appear when at the appropriate progression level. Phasing occurs when entering the area, so you will need to leave and re-enter if you change your progression while at the Tournament.
