### ISSUE TITLE
A few minor issues in Mulgore.

### ISSUE THREAD

**Issue by Grimfeather** [ZhengPeiRu21/mod-individual-progression#146]
Suberb project

 I'm still in tier one, a few issues I've encountered.

- in Red Cloud Mesa: plainstrider, mountain cougar and battle boar have wrong skinning loot. (I was getting blue whelp scales. )

in Thunder Bluff: 
- Nida Winterhoof's title is wrong. It says expert enchanter, it should be herbalism supplies
- Ruk Warstomper is standing on top of Kergul Bloodaxe. afaik Ruk is not supposed to be there (yet). Also Ruk is level 60, he should be level 81
- Mosha Starhorn is standing on top of Taim Ragetotem. Mosha is not supposed to be there (yet). Also Mosha is level 60, she should be level 81

**Comment by ZhengPeiRu21** [comment]
Thank you very much for reporting these issues. I've fixed Nida Winterhoof's title in https://github.com/ZhengPeiRu21/mod-individual-progression/commit/fe8fbd298b466aab1b065409de57f412f403f7d9 and the battlemasters in https://github.com/ZhengPeiRu21/mod-individual-progression/commit/89023cc1a0558c34e6ac51b396c1cf83f1e1529b.

The skinning loot issue is an upstream AzerothCore bug. I have submitted a fix here: https://github.com/azerothcore/azerothcore-wotlk/pull/16789.
