### ISSUE TITLE
BC first aid

### ISSUE THREAD

**Issue by Remakbna** [ZhengPeiRu21/mod-individual-progression#149]
Hello. Thank you for your work. Please check: Aresella and maybe Burko - Hellfire Peninsula First Aid teachers don't sell books for first aid up to 375.

**Comment by ZhengPeiRu21** [comment]
Thank you very much for reporting this issue. The NPCs had the correct items in their inventories but had incorrect flags so they were not marked as vendors. This has been fixed in https://github.com/ZhengPeiRu21/mod-individual-progression/commit/67e658248a8b5abf56f37a0e4845aef7060af8d1.
