### ISSUE TITLE
Cannibalistic Cousins

### ISSUE THREAD

**Issue by Grimfeather** [ZhengPeiRu21/mod-individual-progression#157]
small error in: vanilla_quest_levels.sql

/*  Cannibalistic Cousins  */
UPDATE `quest_template` SET `LogDescription` = "Mystic Yayo'jin at Revantusk Village in the Hinterlands wants you to kill 30 Vilebranch Scalpers and 2 Vilebranch Soothsayers. Return to her when this task is complete.$B$BYayo'jin indicated that these trolls could be found near the Shaol'watha and Agol'watha temples in the north by northeastern region of the Hinterlands." WHERE `ID` = 7844;

It's not 2 Vilebranch Soothsayers. it's 15. Just a mistake in the quest description. the quest itself is correct.

**Comment by ZhengPeiRu21** [comment]
Thank you very much for reporting this issue. I'm very grateful for your reports and identifying these problems I've missed! This has been fixed in https://github.com/ZhengPeiRu21/mod-individual-progression/commit/9dbf9182a0be3c092c791675121b3aabc9db951d.
