### ISSUE TITLE
Xerash Fireblade, quest "A Strange Request"

### ISSUE THREAD

**Issue by Grimfeather** [ZhengPeiRu21/mod-individual-progression#158]
The quest "A Strange Request" in Feralas can't be completed normally because Xerash Fireblade (entry 36208) is set to the wrong progression tier. At least I think that's what's going on.

I found entry 36208 in 'ipp_aware_npcs.sql' 
UPDATE `creature_template` SET `ScriptName` = 'npc_ipp_wotlk_totc' WHERE `entry` IN (35498, 35577, 35496, 36208, 35500, 35497, 34244, 28701);

**Comment by ZhengPeiRu21** [comment]
Thank you for reporting this issue. This is actually a problem with the quest itself - it has not been properly corrected to its Classic form, which requires speaking to a different NPC. I will make the necessary fixes.

**Comment by ZhengPeiRu21** [comment]
Thank you again for reporting this issue. This has been fixed in https://github.com/ZhengPeiRu21/mod-individual-progression/commit/28618ed612387155c18af90e99117e42d623524b.
