### ISSUE TITLE
Molten Core - runes of warding

### ISSUE THREAD

**Issue by Grimfeather** [ZhengPeiRu21/mod-individual-progression#161]
Been clearing MC with NPCbots
Molten Core isn't resetting.
After a week Majordomo spawned with no runes of warding extinguished
IndividualProgression.MoltenCore.ManualRuneHandling = 1
I don't even have the item to douse the runes, Aqual Quintessence
To be clear, a week ago, right after I killed the last boss that guards a rune of warding Majordomo did NOT spawn.
It looked like it was working correctly. I think something went wrong with the instance reset that triggered Majordomo.

Furthermore, 2 minions of Garr respawned
guid 56619, 192, entry 12099
guid 16399, 188, entry 12099

And lastly, Ragnaros spawned as a lvl63 non elite called Unknown, not Ragnaros.
Only visual bug though, he was quite strong.

Maybe some, or perhaps even all of this isn't part of this module and should be reported on AzerothCore instead.
I'm sorry about that if that's the case.

**Comment by ZhengPeiRu21** [comment]
Thanks for reporting these issues. I'll see what I'm able to reproduce locally. The module does only make minimal changes to Molten Core, so some of these (like the Garr adds respawning) are probably on the AzerothCore side. I'll submit fixes there where appropriate.

**Comment by Grimfeather** [comment]
just noticed a report on AzerothCore about instance resets.
https://github.com/azerothcore/azerothcore-wotlk/issues/17842
turns out the server needs to be online on reset day. My server hasn't been online 24/7 so that's most likely the issue here.
