### ISSUE TITLE
Silithus Quest: The Calling

### ISSUE THREAD

**Issue by Grimfeather** [ZhengPeiRu21/mod-individual-progression#164]
https://www.wowhead.com/classic/quest=8315/the-calling

The quest is labeled as a group quest right now. Suggested Players [2]
This used to be a raid quest in vanilla.
Emissary Roman'khan was tough to kill so I'm pretty sure it's only the quest description that needs to be changed still.

**Comment by ZhengPeiRu21** [comment]
Thanks for reporting the issue. I'll fix the quest flag.

**Comment by ZhengPeiRu21** [comment]
Resolved in https://github.com/ZhengPeiRu21/mod-individual-progression/commit/4d22d60a58d431741047bed8f9bd4446fcedcdf3.
