### ISSUE TITLE
Deadwood of the North & some other Timbermaw Hold issues.

### ISSUE THREAD

**Issue by Grimfeather** [ZhengPeiRu21/mod-individual-progression#171]
This quest in Felwood has a few issues.
https://www.wowhead.com/classic/quest=8461/deadwood-of-the-north

Not sure why, but in the database there are 2 versions of this quest. 8461 and 6221
The difference is having to kill either 5 or 6 of each enemy
The quest that I picked up is 8461. having to kill 6 of each.

In vanilla_quest_reputations.sql you don't change anything for 8461
But you do makes changes for 6221, which isn't used afaik.

I received 1400 reputation for completing this quest.
according to wowhead this quest should reward 150rep.

same problem with Winterfall Activity 
https://www.wowhead.com/classic/quest=8464/winterfall-activity
this quest also has two entries in the database. 8464 and 6241
you makes changes for 6241, but not for 8464.
And 8464 is the quest I picked up and completed. And it rewarded me with 1400 rep.
according to wowhead this quest should reward 150rep

-------

deadwood ritual totem (8470) gives 1400 rep. should be 150
winterfall ritual totem (8471) gives 1400 rep. should be 150
Speak to Salfa (8465) gives 100rep, should be 25

killing Winterfall Pathfinders gives 6rep, should be 5
https://www.wowhead.com/classic/npc=7442/winterfall-pathfinder

**Comment by ZhengPeiRu21** [comment]
Fixed in https://github.com/ZhengPeiRu21/mod-individual-progression/commit/f037fcd06bff763a108766ff489f0ac97f3e4630. Thank you for the detailed reports!
