### ISSUE TITLE
Zombie Chow Faction

### ISSUE THREAD

**Issue by Day36512** [ZhengPeiRu21/mod-individual-progression#173]
Hey! Sorry I didn't push the change because I wasn't sure where you wanted it, but Zombie Chow will need the proper faction ID, 89, which is npcid 351069.

**Comment by ZhengPeiRu21** [comment]
Thank you, I'll make that fix!

**Comment by ZhengPeiRu21** [comment]
Resolved in https://github.com/ZhengPeiRu21/mod-individual-progression/commit/f6e726c856f499400c6605fb468a9ae6a77eb69a.
