### ISSUE TITLE
Periodic effects not affected by power adjustment

### ISSUE THREAD

**Issue by atrapalis** [ZhengPeiRu21/mod-individual-progression#176]
Hello,

Thank you for your work on this great mod!

It seems like damage over time effects are not affected by the vanilla / TBC power adjustments (e.g. hunter's Serpent Sting, Explosive and Immolation traps). I noticed this when looking at class balance at level 60.

My question is: is this intentional or would you consider it an issue / want to change it?

to clarify I am referring to this setting from the config file:
```
#    IndividualProgression.VanillaPowerAdjustment
#        Description: Adjustment to player's attack power before completing Vanilla content
#                     This is meant to provide a more accurate Vanilla feeling in Vanilla content
#                     Applied linearly per level between levels 11 and 60
#                     Set to 1 (100% of regular damage) to disable
#
#        Default:     0.6 - 60% of regular damage
# IndividualProgression.VanillaPowerAdjustment = 0.6
```

Thanks

**Comment by ZhengPeiRu21** [comment]
Thank you for reporting this! I was not aware of the problem and it is definitely unintended; periodic effects should have the same adjustment. I'll look into this as a high priority issue.

**Comment by atrapalis** [comment]
No problem. I am sure you know where to find this but this is a list of damage/healing related scripting functions I've found in another module:
```
    uint32 DealDamage(Unit* AttackerUnit, Unit *playerVictim, uint32 damage, DamageEffectType /*damagetype*/) override { }
    void ModifyPeriodicDamageAurasTick(Unit* target, Unit* attacker, uint32& damage, SpellInfo const* spellInfo) override { }
    void ModifySpellDamageTaken(Unit* target, Unit* attacker, int32& damage, SpellInfo const* /*spellInfo*/) override { }
    void ModifyMeleeDamage(Unit* target, Unit* attacker, uint32& damage) override { }
    void ModifyHealReceived(Unit* target, Unit* attacker, uint32& damage, SpellInfo const* /*spellInfo*/) override { }
```

I believe `ModifyPeriodicDamageAurasTick` is missing from individual progression. I assume this also affects healing over time effects although I did not test this.

I will say that although unintended, the added DoT damage is beneficial for some builds that are weak at level 60.
I may opt out of it in my local branch if you decide to fix it but I will test it first :)

**Comment by ZhengPeiRu21** [comment]
Thanks for your input. Balancing is always tricky. If there are particular builds that drastically underperform at the 60 and 70 level caps, perhaps we could add a config option to slightly boost damage for them; I'd welcome any additional details!

**Comment by ZhengPeiRu21** [comment]
This should be fixed in https://github.com/ZhengPeiRu21/mod-individual-progression/commit/2dd4ee11627d11bc434d86703ad4948976c44b11. Please let me know if you continue to see any issues! Thanks again for your contributions.
