### ISSUE TITLE
Сharacter doesn't get experience after 20 lvl.

### ISSUE THREAD

**Issue by Fidaen** [ZhengPeiRu21/mod-individual-progression#177]
I stopped getting experience from any actions after 20 level, tried to look for a solution to the problem in the config, but did not find such a limitation. What could this be related to?

P.S. Thank you for repak, all aspects of the game work very well.

**Comment by ZhengPeiRu21** [comment]
I'm not able to reproduce this issue. Did you change any values in the worldserver config?

**Comment by Fidaen** [comment]
I played regular repak without individual progression. I changed the auto-study of spells in the config maybe this led to a bug. Now I have installed a busy server with individual progression and there is no such error.

I wanted to ask something else. I apologize, if there was already such a question. I just could not find how to turn off random magic effects in ordinary weapons. Some of them too bright. Where can I turn them off?

**Comment by ZhengPeiRu21** [comment]
> I played regular repak without individual progression. I changed the auto-study of spells in the config maybe this led to a bug. Now I have installed a busy server with individual progression and there is no such error.
> 
> I wanted to ask something else. I apologize, if there was already such a question. I just could not find how to turn off random magic effects in ordinary weapons. Some of them too bright. Where can I turn them off?

I'm sorry, but it sounds like you are using a repack provided by someone else. Those effects are not part of Individual Progression, and are not included in the build I provide. You will need to go to whenever you found the repack and ask the maintainer of it for support. If you would like to change to the official Individual Progression pre-compiled build, it is available here: https://github.com/ZhengPeiRu21/mod-individual-progression/releases
