### ISSUE TITLE
pvp item restriction system blocks incorrect items

### ISSUE THREAD

**Issue by EllieSca** [ZhengPeiRu21/mod-individual-progression#178]
![WoWScrnShot_083123_153153](https://github.com/ZhengPeiRu21/mod-individual-progression/assets/92201409/84987e53-d2f7-49c2-aa21-423ffc7f1c11)

same thing with legionnaire's sword

**Comment by ZhengPeiRu21** [comment]
Thanks for reporting the issue. Fixed in https://github.com/ZhengPeiRu21/mod-individual-progression/commit/91696a5c1b85a9bb9d428ab3b40c68ae53627469.
