### ISSUE TITLE
AC New update broke the mod

### ISSUE THREAD

**Issue by Siafria** [ZhengPeiRu21/mod-individual-progression#183]
Because Azerothcore commit [358a1e71e](https://github.com/azerothcore/azerothcore-wotlk/commit/358a1e71e0b84c194164d0fb74fd2372d9bcf713) changed the way player_class_stats table function the module no longer work.

**Comment by ZhengPeiRu21** [comment]
Thank you for reporting the issue. Fixed in https://github.com/ZhengPeiRu21/mod-individual-progression/commit/de2c9aa8c040577c1cab91aa80bf35015aa06fd9.
