### ISSUE TITLE
Editing SQL + Adding Modules.

### ISSUE THREAD

**Issue by EmmanouilBrotzakis** [ZhengPeiRu21/mod-individual-progression#185]
1) I know this is not exactly an issue but more of a question, how can I edit SQL tables, since it seems like they're stored as .MYD, .MYI and .frm files? 

2) Is it possible to add some more modules on top of the ones already installed?

**Comment by ZhengPeiRu21** [comment]
1. You can access the SQL database either directly through the mysql binary in the cli, or through software such as HeidiSQL. The username is root and there is no password.

2. No, additional modules can't be added to the pre-compiled build. If you have interest, I highly recommend compiling your own core by following the [installation guide](https://www.azerothcore.org/wiki/installation). It isn't difficult and will give you full control over your server, and will make keeping up to date easier.

**Comment by EmmanouilBrotzakis** [comment]
Is there a chance we can get the pre compiled build with the modules and everything, so I can throw my own modules and then compile it?

**Comment by ZhengPeiRu21** [comment]
> Is there a chance we can get the pre compiled build with the modules and everything, so I can throw my own modules and then compile it? What I mean by pre compiled is the build before you compile it, so I can go ahead and throw my modules in and run it through cmake and then build it.

It is just a regular AzerothCore installation, with the following modules installed:
-     mod-autobalance
-     mod-individual-progression
-     mod-reagent-bank
-     mod-transmog
-     mod-ah-bot
-     mod-challenge-modes
-     mod-leech
-     mod-aoe-loot
-     mod-instance-reset
-     mod-pvp-titles
    
If you download the AzerothCore source and put each of those modules in the modules directory, it will be the same as what I am building. (NPCBots is an exception and does require a patch, but you can just use the pre-patched AzerothCore source from [here](https://github.com/trickerer/AzerothCore-wotlk-with-NPCBots). No module is necessary.) If you use Discord, please feel free to join the AzerothCore Discord for help getting it set up.
