### ISSUE TITLE
[Feature Request] Power/Healing/Health Adjustments as a separate module or enable separately

### ISSUE THREAD

**Issue by Dreathean** [ZhengPeiRu21/mod-individual-progression#192]
Hello! If at all possible, could the power/healing/health adjustments be spun into a separate module? Or make it to where you can enable strictly those features without enabling the rest of the individual progression module? Thank you for all you do.

**Comment by ZhengPeiRu21** [comment]
Because the adjustments work by checking the progression level of the player, it is closely tied to the module. I've tried to make the module as modular as possible, so if there are any changes you don't like, you can just not run the related SQL files (you may get some console warnings about scripts not being assigned, but these can be disregarded.) Is there a certain feature that can't currently be disabled that is causing you to not want to use the module?

**Comment by Dreathean** [comment]
Gotcha! I'll have to look more into how much is impacted via SQL vs CPP changes, I assumed I would be forced to use most of the alterations of the module. The biggest thing for me is the return of attunements which are not configurable - https://github.com/ZhengPeiRu21/mod-individual-progression/issues/152, among some other vanilla features I'm not looking to return to like 1.12 riding requirements (I'm assuming that's including lvl 40 basic mount vs 20), unsure of the ramifications of restoring all vanilla items to their 1.12 version (ie does that entail reverting items with crit rating back to their original crit %?).

Otherwise I think most other changes are truly great and some things I may not want like the profession changes are optional files I see. Definitely love the return of OG Onyxia and Naxx. The other biggest thing, which we have discussed before, is how Playerbots interact with this module, I know you said the goal is for them to work seamlessly with this module, but I'm not sure if that is currently the case or if it is a future goal? I can see how Playerbots I use with my raid team can progress seamlessly at least, but not sure what would happen to all of the Playerbots not progressing with me/opposite faction will progress and make it to BC, WOTLK, etc.

**Comment by Grimfeather** [comment]
Player bots will go where you go. They're not restricted to progression levels.
You can have multiple characters, all at different progression levels. It's not an issue.
If a character on the opposite faction progresses to TBC, that won't effect you at all.

I can only see a possible issue if a character on your side progresses to TBC and the auction house is enabled.
Not sure how that is handled. You may see TBC items available on the AH.
It's singleplayer though, AH should be disabled IMO.

**Comment by Dreathean** [comment]
Interesting, so playerbots do not need to abide by the progression restraints at all? Meaning when I move onto BC content, even playerbots that did not raid with me will move onto BC and beyond without any issues? I did not consider that might be the case. 

It seems most of my other concerns are solved by excluding the relevant sql files, so if this is the case and can be confirmed I will happily close this comment out!

Thank you ZhengPeiRu as always for all of your excellent work on these modules!

**Comment by Dreathean** [comment]
@ZhengPeiRu21 Something just came to mind if you can please clarify, if Playerbots do indeed not abide by the progression restraints, then how would we know which set of damage/healing/hp adjustments they would be subjected to since those are directly tied to progression?

**Comment by Grimfeather** [comment]
I was the one who brought it up, so I'll step in here.
There may be more going than I thought. Is there a patch for npcbots to work better with Individual progression?
I'm asking because I'm not using the Module Preview Build myself. 
I'm using azerothcore, npcbots, individual progression and eluna.

There are no settings for dmg/healing/hp adjustments tied to progression tiers in worldserver.conf for me

**Comment by Dreathean** [comment]
The dmg/healing/hp adjustments are part of the individual progression module, not something found in the worldserver.conf. See below. If I had to guess, npcbots "work" for you because they are not affected at all by the individual progression module. However, that means they also are not having their dmg/heal/hp adjusted at all either. I imagine most people using Playerbots would want their playerbots to be impacted if they're looking to reduce "player" power as it is a great part of this module enabling people to retain some of the former difficulty of these raids in the WOTLK setting.

https://github.com/ZhengPeiRu21/mod-individual-progression/blob/master/conf/individualProgression.conf.dist
![image](https://github.com/ZhengPeiRu21/mod-individual-progression/assets/132776330/5ad8f985-2655-437d-9e20-f74cfde7492b)

**Comment by Grimfeather** [comment]
Those are just for you. not for the npcbots.

**Comment by Dreathean** [comment]
I understand they are only for players, not NPCbots. That is why I am discussing Playerbots, the module by Zheng, and not NPCbots. Playerbots use AI that control actual player characters whereas NPCbots use creatures. So with that in mind, I would imagine and hope that the power tuning would be applied to them.

**Comment by Dreathean** [comment]
Just sharing in case you haven't seen it:

NPCBOTS - https://github.com/trickerer/AzerothCore-wotlk-with-NPCBots
Playerbots - https://github.com/ZhengPeiRu21/mod-playerbots

Two totally different modules which I think is causing some of the confusion here.

**Comment by Grimfeather** [comment]
Ok, that clears things up. Indeed confusing because the Module Preview Build says it uses NPCbots.

I'll step out of this discussion.
NPCbots are creatures pretty much turned into NPCbots you can hire. So they aren't effected by those modifiers.
I'm not 100% sure how playerbots works. I've read you can turn your own alts into bots. 
Depending on how that is done, it could be different. Probably not, but it could be.

**Comment by Dreathean** [comment]
All good! To be honest I'm not sure what you're referencing when you say "Module Preview Build". 

And yup I've been using NPCbots for a while but been testing with Playerbots and plan on switching over to that in conjunction with Individual Progression modules. Not only do they use your alts, you can generate hundreds of playerbots to run around and level up that makes the world feel much more alive, but this is beyond the scope of this discussion.

**Comment by Dreathean** [comment]
Ah okay I did not realize that Zheng releases his own Repack there and included NPCbots with it. Not too surprising given they are currently more advanced than Playerbots though I suspect that will change soon. Thanks that clears that part up haha

**Comment by ZhengPeiRu21** [comment]
NPCBots does have a config option you may find helpful that allows you to set damage multipliers per level bracket. This should let you give them a roughly equivalent scaling to the Individual Progression damage scaling:
```
#    NpcBot.Mult.Damage.Levels
#        Description: Multipliers for bots' damage by level: 0-9, 10-19, 20,29, ... , 70-79, 80+.
#                     At least 9 values required.
#        Default:     1.0
#        Minimum:     0.1
#        Maximum:    10.0

NpcBot.Mult.Damage.Levels = 1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
```

Unfortunately there isn't an equivalent for health and healing, but there is a global multiplier you can play with to find something that works.

**Comment by Dreathean** [comment]
Ah that is good to know, thank you! I intend to test it soon, but can you please clarify if the Individual Progression hp/healing/dmg will impact Playerbots? I'm hoping it would since it seems to be based at least in part on level?

**Comment by Dreathean** [comment]
@ZhengPeiRu21 Sorry to ping you, I know you must be busy - the only remaining question I have before closing this out is just how Playerbots are impacted by this module? Since if they won't be restricted progression-wise, how do I ensure they receive the same nerfs as us players?

Looking at the code though, I imagine the Playerbots will basically be stuck at level 60 with vanilla power/healing scaling? Since they will not be progressing except for the ones raiding with us.

**Comment by Dreathean** [comment]
I think I figured a work-around just in case on this - I can use the config to force the starting progression level to whatever level we get to. Closing out now.
