### ISSUE TITLE
Some periodic heals are adjusted incorrectly

### ISSUE THREAD

**Issue by atrapalis** [ZhengPeiRu21/mod-individual-progression#193]
Some periodic heal values are adjusted twice, resulting in lower heal values than intended.

The problem seems to be that periodic heals trigger two scripting events:
ModifyHealReceived
ModifyPeriodicDamageAurasTick

ModifyHealReceived applies one adjustment (e.g. 0.5 vanilla healing adjustment)
ModifyPeriodicDamageAurasTick applies a second adjustment (e.g. 0.6 vanilla power adjustment)

As a result the total modifier is 0.6 * 0.5 = 0.3.

I tested this with Lifeblood (herbalism spell), but from what I can see other periodic heals behave the same in terms of scripting.

**Comment by atrapalis** [comment]
I think this may be related to a different mod - will reopen issue if needed

**Comment by ZhengPeiRu21** [comment]
Thank you for the report! I wasn't aware of this issue. Odd that the ModifyPeriodicDamageAurasTick is applying to heals - I will get this fixed!

**Comment by ZhengPeiRu21** [comment]
This should be fixed in https://github.com/ZhengPeiRu21/mod-individual-progression/commit/3dbc2e0a561a376170c4407fa93579e8dfa6a3a8. Please let me know if you continue to see any issues. Thanks again for the report!
