### ISSUE TITLE
[Suggestion] Restore the Amani War Bear drop to Zul'Aman

### ISSUE THREAD

**Issue by Daeymon** [ZhengPeiRu21/mod-individual-progression#195]
As per https://wowpedia.fandom.com/wiki/Zul%27Aman_timed_event, restore the "Amani War Bear" drop to the "Ashli's Bag" chest in Zul'Aman as the final reward for saving all the hostages. Was removed in WotLK.

**Comment by ZhengPeiRu21** [comment]
Thanks for the suggestion! I definitely want to implement this. I'll add it to an upcoming release.

**Comment by ZhengPeiRu21** [comment]
This has been implemented in https://github.com/ZhengPeiRu21/mod-individual-progression/commit/2e01eab59a9445200cccce11bd394d19c0e59cdd. Thanks to Bench for the original commit from which this was cherrypicked!
