### ISSUE TITLE
Dungeon Finder locked

### ISSUE THREAD

**Issue by nilskus** [ZhengPeiRu21/mod-individual-progression#196]
Upon reaching lvl 15, I am unable to queue for dungeons with my NPC Bots due to "not having the world of warcraft expansion"

![dungeon finder](https://github.com/ZhengPeiRu21/mod-individual-progression/assets/118109588/935a2f8f-349b-4102-820e-df3ee95b34ab)

tried setting DungeonFinder.OptionsMask in the worldserver.conf to 5 and 7, sadly neither worked

could this be an issue with my client, or is something off with my repack? 
thank you!

edit: i can enter the dungeons manually no problem, by just travelling to them and walking through the portal

**Comment by ajgration** [comment]
It's a feature of the mod. If you want to re-enable dungeon finder, change this setting in individualProgression.conf.

"IndividualProgression.SimpleConfigOverride = 0" instead of 1.

Do note however that this will disable other features and options needed by the mod. You will have to enable these manually in worldserver.conf, importantly EnablePlayerSettings, and DBC.EnforceItemAttributes. EnablePlayerSettings needs to be =1, DBC.EnforceItemAttributes = 0.

**Comment by ajgration** [comment]
Not too sure about that one sorry! Last time I was using the steps I mentioned above with SoloLFG and this mod I had no issues... Does a relog fix it?

**Comment by PaienNate** [comment]
> Thank you for the swift reply!
> 
> After adjusting those values I was able to queue, but after finishing the first dungeon it won't let me queue for another, spitting out a red "Wrong dungeon type 0 for dungeon 0" message in the worldserver.exe and in-game chat says "One or more dungeons was not valid"
> 
> Is this issue related or could it be an incompatibility problem with SoloLFG?

I have the same problem, with SoloLFG.

**Comment by nilskus** [comment]
The error ended up fixing itself somehow .. did a full dungeon so I got the achievement, and afterwards I couldn't reproduce the problem. Hope it works out for you as well!

**Comment by PaienNate** [comment]
> The error ended up fixing itself somehow .. did a full dungeon so I got the achievement, and afterwards I couldn't reproduce the problem. Hope it works out for you as well!

Actually for me, I'm not sure what's wrong and I tried a lot. I turned off the lfg-solo, delete this module and rebuild the world database, nothing work. Then I dump my character file and rebuild the characters database and load my character, it works. Seems there has some database changed in characters caused this problem.

**Comment by ZhengPeiRu21** [comment]
Because this now appears to all be working, I'll be closing this issue. Please feel free to re-open it if you continue to see problems!
