### ISSUE TITLE
Naxx 40 Autobalance Compatability 

### ISSUE THREAD

**Issue by justurn** [ZhengPeiRu21/mod-individual-progression#197]
Autobalance module is referring to either lfgdungeons_dbc table or the lfgdungeons DBC file for scaling data.
Without this entry the latest Autobalance is unable to scale Naxx 40.
A Naxx 40 entry here or directly in the DBC file seems to resolve the scaling issue from my testing.

**Comment by ZhengPeiRu21** [comment]
Thank you for reporting this issue. This should be straightforward to fix - I'll look into adding an entry to the dbc override table.

**Comment by Kabakaylen** [comment]
> Thank you for reporting this issue. This should be straightforward to fix - I'll look into adding an entry to the dbc override table.

Where is this dbc table? I am interested in playing with this trying to get it working. 

Thanks a lot.

**Comment by ZhengPeiRu21** [comment]
This should be fixed by https://github.com/ZhengPeiRu21/mod-individual-progression/commit/cd4ec548f1dcb1450e3836fe40fc62bf5d9ded32. Please let me know if there are any further issues!
