### ISSUE TITLE
Items missing stats

### ISSUE THREAD

**Issue by Grim93** [ZhengPeiRu21/mod-individual-progression#2]
I've noticed some inconsistencies which I think should be fixed in the Itemchanges.sql with items being changed back to their vanilla values, to bring the items back to their intended power levels. I only have a few examples, but from what I saw it was consistent with every item with these stat types. The three I've noticed so far are **+%Crit chance to SPELLS**, **+%Hit chance to SPELLS** and **+Weapon Skills**. They're all missing on items with no replacement stats.

For example;
**Edgemaster's Handguards** - In Vanilla these give +7 to Axes, Daggers and Swords. In WotLK this has been changed to +19 Hit rating, +17 Expertise rating. Currently with this mod, the item has NO stats at all. Now I understand the WotLK version is not how the item was in Vanilla, but it is effectively doing the same thing as the vanilla item, just with WotLK stat types. In Vanilla, +weapon skills lowers your chance of missing and decreases the damage penalty your glancing blows do. There's not a comparable stat for the glancing blows damage, so I think the new WotLK hit and expertise values are fair, as this keeps the item inline with it's intended vanilla use. It is still the best item for warriors to eliminate misses and one of the only items to reduced dodge/block/parries. Having the WotLK stats is better than a blank, unusable item with no stats in my opinion.
**Aged Core Leather Gloves** - this is another example of this. Missing +5 to Daggers, with no replacement Expertise in the mod to bring the item back to it's intended power level and use.

**Neltharion's Tear** - In Vanilla this has +44 spell damage, +2% Hit chance for SPELLS. In WotLK this is changed to +44 spell damage, +16 Hit rating (1.6% @ 60). In the mod this item currently just has +44 spell damage and NO Hit at all. This should either be reverted to WotLK values, or given +20 Hit rating to bring it back to vanilla levels.

**Benediction** - In Vanilla this has +106 Healing power, +2% Crit chance for Holy Spells. In WotLK this was changed to +56 Spell power and a flat +28 Crit rating (2% @ 60). In the mod this item currently only has +56 spell power with no Crit chance. I understand that the Crit was only intended for Holy spells, so adding the full +2% Crit chance would make the item more powerful than vanilla. So perhaps +14 Crit rating (1% @ 60) would be appropriate, as removing it completely nerfs the item too much in my opinion.

I'm assuming all items with these stat types listed will need a review.

**Comment by ZhengPeiRu21** [comment]
Thank you, this is very useful to know. This is due to some stats changing at the client level, so it may impossible to completely fix, but I think we can do some hand-tuning to approximate the power like you have suggested.

**Comment by ZhengPeiRu21** [comment]
It seems that these were achieve using custom spells on the items and I was able to restore them or a very close equivalent. Fixed in https://github.com/ZhengPeiRu21/mod-individual-progression/commit/470481190b21ada52cb1cc6a7190cbfa095cb033.

**Comment by ajgration** [comment]
Here's a couple more low level items missing stats. I'll just keep adding to this as I find more.

Coppercloth Gloves - currently no stats, missing +3 strength - https://classicdb.ch/?item=4767
Gemmed Copper Gauntlets -  currently no stats, missing <random enchantment> such as "of the bear/eagle etc." - https://www.wowhead.com/classic/item=3474/gemmed-copper-gauntlets
