### ISSUE TITLE
MC 

### ISSUE THREAD

**Issue by OpexNSK** [ZhengPeiRu21/mod-individual-progression#20]
After killing the defenders of the Majordomo Executus, he goes to Ragnaros through the textures on a straight trajectory. Very very slowly. You also need to be near him so that he goes

**Comment by ZhengPeiRu21** [comment]
Thank you for the reporting. I will investigate. Do you know if this issue is happen on base AzerothCore as well?

**Comment by OpexNSK** [comment]
I haven't tried it on master branch

**Comment by ZhengPeiRu21** [comment]
I was able to reproduce this issue on a clean AC build, so this is not a progression module issue. I have opened an AC ticket to address: https://github.com/azerothcore/azerothcore-wotlk/issues/13019
