### ISSUE TITLE
Isle of Quel'Danas and Sunwell Plateau

### ISSUE THREAD

**Issue by JumpyLion87** [ZhengPeiRu21/mod-individual-progression#200]
When the content is limited to PROGRESSION_TBC_TIER_1, there is access to the Isle of Quel'Danas and you can enter the Sunwell Plateau raid, but you cannot exit. With this setup, it should not be allowed to enter this raid.

**Comment by ZhengPeiRu21** [comment]
Thank you for reporting this issue. I'll look into it. Access should be restricted - how is it that you are accessing the Isle?

**Comment by JumpyLion87** [comment]
I got to the island on a quest https://www.wowhead.com/tbc/quest=11482/duty-calls

**Comment by JumpyLion87** [comment]
Then I flew to the island through the flight manager at Silvermoon

**Comment by ZhengPeiRu21** [comment]
Thanks for the additional details. I'll get this resolved.

**Comment by Grimfeather** [comment]
General Tiras'alan in Shattrath city also gives the quest "Enter, the Deceiver.."
https://www.wowhead.com/tbc/quest=11550/enter-the-deceiver

This quest sends you to Silvermoon city to talk to the flight master and allows you to fly to the Sunwell Plateau too early.
I believe General Tiras'alan can be hidden/phased. Afaik he only starts this quests.

**Comment by ZhengPeiRu21** [comment]
Thank you both for the reports. These should be fixed in https://github.com/ZhengPeiRu21/mod-individual-progression/commit/19727d9f0e7efc6f07f6dfe49442f733a3ef0eb9.
