### ISSUE TITLE
issues with single player gameplay and npc mind control spells

### ISSUE THREAD

**Issue by SPPGamer** [ZhengPeiRu21/mod-individual-progression#201]
i play single player progress as single player game and last night i was doing quest in tbc and had big issue with this quest 

https://www.wowhead.com/tbc/quest=10320/destroy-naberius

no possible alone bc he will use chains of nebrius which mind controls u but if its a single player game theres nobody to help/break it

https://www.wowhead.com/wotlk/npc=20483/naberius#abilities

so it goes like u hit him then he mc you then combat ends resets and he goes back to full hp

i have not try dungeons or raids yet but there are defanately bosses like first boss in sewers of black temple who does combat removing/charms/stuns/mc at some phase i will try write list if i find any more

**Comment by Dreathean** [comment]
I do not believe this problem is in the scope of this specific module. You have a variety of options however - 1) use NPCbots module, 2) use Playerbots module, or 3) adjust spells as needed

**Comment by ZhengPeiRu21** [comment]
As Dreathean mentioned, this is outside the scope of the module. I would recommend giving this recently created module a try - it is designed to make changes to encounters to make them doable with smaller groups: https://github.com/kjack9/mod-smallcraft
