### ISSUE TITLE
Autobalance - Battlegrounds crashing when clicking 'Enter Battle' on queue notification

### ISSUE THREAD

**Issue by SheriffBaloo** [ZhengPeiRu21/mod-individual-progression#204]
Autobalance (ZhengPeiRu21's fork) being added is crashing my battlegrounds when clicking 'Enter Battle' on the battleground queue notification after about 3 seconds of very high lag, no loading screen after clicking 'Enter Battle' shows up, just unable to cast for about 3 seconds and then my worldserver crashes. 

[Auth.log](https://github.com/ZhengPeiRu21/mod-individual-progression/files/13497102/Auth.log)
[Errors.log](https://github.com/ZhengPeiRu21/mod-individual-progression/files/13497103/Errors.log)
[Playerbots.log](https://github.com/ZhengPeiRu21/mod-individual-progression/files/13497104/Playerbots.log)
[Server.log](https://github.com/ZhengPeiRu21/mod-individual-progression/files/13497106/Server.log)
[b739cfe21960+_worldserver.exe_[29-11_0-54-50].dmp](https://github.com/ZhengPeiRu21/mod-individual-progression/files/13497109/b739cfe21960%2B_worldserver.exe_.29-11_0-54-50.dmp)
[b739cfe21960+_worldserver.exe_[29-11_0-54-50].txt](https://github.com/ZhengPeiRu21/mod-individual-progression/files/13497110/b739cfe21960%2B_worldserver.exe_.29-11_0-54-50.txt)

**Comment by ZhengPeiRu21** [comment]
Thank you for filing an issue. Please do not use my autobalance fork - it only exists for when I create a PR on the main repo. Please use the AzerothCore standard Autobalance module, and file any issues there.
