### ISSUE TITLE
[Fix Included] Lethargy Root Quality/Rarity

### ISSUE THREAD

**Issue by StraysFromPath** [ZhengPeiRu21/mod-individual-progression#208]
![image](https://github.com/ZhengPeiRu21/mod-individual-progression/assets/119371540/7b336cbe-1eec-40d0-bdc3-ce264afbabc2)

All rogue poison ingredients except this are white. This is grey/poor by mistake.

I can fix! Here is:

FIX: UPDATE `item_template` SET `Quality` = 1 WHERE (`entry` = 3777);

**Comment by ZhengPeiRu21** [comment]
Thanks for filing this issue. This being grey quality is correct. This was the behavior in 1.12. This is the case in Vmangos and Cmangos, and can be confirmed on WoWhead classic: https://www.wowhead.com/classic/item=3777/lethargy-root
