### ISSUE TITLE
Night Elf Ambusher doesn't seem correct

### ISSUE THREAD

**Issue by ValeTheVioletMote** [ZhengPeiRu21/mod-individual-progression#210]
The Night Elf Ambusher from tbc_creatures.sql is given absurdly high damage:

```sql
/*  Night Elf Ambusher  */
UPDATE `creature_template` SET `speed_run` = 1.38571, `DamageModifier` = 5.0 WHERE `entry`=16238;
```

This causes the player and NPC scout to be near instantly killed upon turning in the quest "Deliver the Plans to An'telas".

Commenters from 2007 make no mention of being slaughtered at this quest - just that the mobs will appear: https://www.wowhead.com/tbc/quest=9166/deliver-the-plans-to-antelas

**Comment by ZhengPeiRu21** [comment]
Thanks for reporting this issue. That does seem incorrect - I'd guess my sources are wrong. For now, I've reverted it back to the AC default DamageModifier.
