### ISSUE TITLE
How to check

### ISSUE THREAD

**Issue by ForevergloryXXI** [ZhengPeiRu21/mod-individual-progression#212]
Hei I'm newbie in this I just finish installing it

- How can I check if the module work / work correctly?
- I have other modules and when I log in on my character
- Their Ar show up in chat example " Sololfg module " is active 
- But this module didn't show up in chat

**Comment by StraysFromPath** [comment]
> Hei I'm newbie in this I just finish installing it
> 
>     * How can I check if the module work / work correctly?
> 
>     * I have other modules and when I log in on my character
> 
>     * Their Ar show up in chat example " Sololfg module " is active
> 
>     * But this module didn't show up in chat

Individual progression doesn't announce itself to chat.

Your best way to check if the module is working is to test some of the module edits listed here: https://github.com/ZhengPeiRu21/mod-individual-progression/wiki/List-of-Changes

For example use GM commands to add 30 potions of minor healing. If they stack in 5s, that's module, if they stack in 20s, something went wrong.

Another way to check is to make a lvl 1 warlock and see if the warlock trainer has a quest to learn imp. That's module/classic behaviour.

**Comment by ZhengPeiRu21** [comment]
StraysFromPath gives some good suggestions. I'm going to close this issue, but feel free to reopen it if you continue to have problems.
