### ISSUE TITLE
Autobalance on Onyxia 40

### ISSUE THREAD

**Issue by Kabakaylen** [ZhengPeiRu21/mod-individual-progression#214]
Thanks for all your work!

I have a custom build with autobalance (the NPC Bots fork) and NPC bots with Individual Progression.

When I enter Ony 40 man, autobalance is ignored for all creatures (and doesn't count them, etc.) so if I am entering with a reduced group (say 10 man, rather than 40) Ony is still at 1,824,000 HP and is pretty much impossible. 

I cannot find any solution to get her forced on autobalance, or the other mobs in the instance. I have tried manually adding in the creatureID of Onyxia  (10184) in autobalance to try and reduce her HP but it does not work,  says map ignored.

Is there anything that can be done? autobalance does work with the level 80 versions so I am stumped.

EDIT: looks like similar issue to Naxx: https://github.com/ZhengPeiRu21/mod-individual-progression/issues/197

Thanks a lot!
<img width="284" alt="Screenshot 2023-12-24 212325" src="https://github.com/ZhengPeiRu21/mod-individual-progression/assets/26560186/43f8ee3b-69a7-4a33-a2b2-45419cfd5f8c">

**Comment by Kabakaylen** [comment]
This has been fixed with https://github.com/ZhengPeiRu21/mod-individual-progression/pull/220 simply by running the updated SQL to update the database.

Thank you so much. It was so nice being able to run this <3

As an FYI if anyone is having trouble with Vanilla Ony and you are running a raid under 25 people, you cannot enter the instance through the front portal, it puts me in the WotLK version. I am going to look into adjusting entry requirements to keep players under 70 out. I have not tried a 40 man raid to confirm if that fixes it or not.

I use .tele onyxia to enter the zone direct. You know you are in the right version of the instance when there is a "0" on the flag by your minimap (opposed to 10 or 25 which would be the WotLK raid again).

**Comment by Day36512** [comment]
It's easier if you adjust the core and framexml to let you set to 10H. I've done some adjusting on onyxia zoning in general. May push it later this week.

**Comment by ZhengPeiRu21** [comment]
> It's easier if you adjust the core and framexml to let you set to 10H. I've done some adjusting on onyxia zoning in general. May push it later this week.

Please do!

**Comment by Day36512** [comment]
Yeah looks like unfortunately my changes require an XML edit, which we aren't really in the habit of doing so for this module that I'm aware of. If only Blizz let you set to 10H by level 60 by default, that'd be nice.

**Comment by ZhengPeiRu21** [comment]
> Yeah looks like unfortunately my changes require an XML edit, which we aren't really in the habit of doing so for this module that I'm aware of. If only Blizz let you set to 10H by level 60 by default, that'd be nice.

Agreed. Looks like we'll have to make do with the fix from https://github.com/ZhengPeiRu21/mod-individual-progression/pull/220.

I'll go ahead and mark this issue as closed; if anyone continues to see autobalance issues with Onyxia, please let me know and I will re-open it.

**Comment by Kabakaylen** [comment]
I apologize if this is not the appropriate place to throw this out there as the issue is closed.

One thing I found while playing around after updating the sql is at the Ony raid entrance the blizz UI actually gives me the option to right click my portrait and set my raid difficulty to 10H and I can actually walk directly in to the 40m version.

I was wondering if it worth noting maybe in your wiki section that the way to enter this raid with a team <26 players is to walk to the zone entrance, and manually adjust the raid difficulty which would help someone in the future as it is probably not obvious.

Thank you so very much for your efforts on this, you have given me hours of enjoyment!!!

**Comment by Day36512** [comment]
> I apologize if this is not the appropriate place to throw this out there as the issue is closed.
> 
> One thing I found while playing around after updating the sql is at the Ony raid entrance the blizz UI actually gives me the option to right click my portrait and set my raid difficulty to 10H and I can actually walk directly in to the 40m version.
> 
> I was wondering if it worth noting maybe in your wiki section that the way to enter this raid with a team <26 players is to walk to the zone entrance, and manually adjust the raid difficulty which would help someone in the future as it is probably not obvious.
> 
> Thank you so very much for your efforts on this, you have given me hours of enjoyment!!!

Are you on a repack or your own? Dinkle's repack has Frame XML edit. Sometimes though you're able to change difficulty due to the server trying to change it for you first. It's a big buggy that way.

**Comment by Kabakaylen** [comment]
I am using my own, but it is based off of the AC fork that Trickerer did to incorporate NPC Bots, I do not believe other significant modifications were made, but I am not certain if there were any large changes like that. 

I do suspect that it is a "bug" from being near the zone entrance as the option to set raid difficulty comes and goes depending on my location. I will try to re-create it a bit tonight and see what does and doesn't trigger it.

I was able to watch it update in the SQL group table (as I was in a group with NPC bots at the time), not sure if there is a flag in another part of the database for the individual player.

Is the XML client or server side?

**Comment by Day36512** [comment]
Client side but core side modifications need to take place as well if I recall. Looking through my commits.
[Interface.zip](https://github.com/ZhengPeiRu21/mod-individual-progression/files/14514834/Interface.zip)

**Comment by Kabakaylen** [comment]
I finally had a chance to play around, it is a bug for sure to be able to change the raid difficulty. If it doesn't automatically appear outside of the Ony entrance you need to enter, which should default you to a 10N raid, then exit and change the difficulty while not in a party. 

Not the most straightforward, but it does work...

**Comment by webtectonics** [comment]
So I have about 10 folks and we can't seem to get this to work.  We form a raid and it's set to 10H by default.  No matter how we zone in (via .teleport or walking in), the mobs and Ony are not getting balanced.  This is a pretty fresh install of Azerothcore and AB (about 2 weeks old).  I checked the SQL tables and the Onyxia updates are in there.  So what are we doing wrong?

![Screenshot 2024-06-27 123342](https://github.com/ZhengPeiRu21/mod-individual-progression/assets/16596507/3b723706-befe-4bf2-8bba-6f2a217f551c)

**Comment by atrapalis** [comment]
@webtectonics There is a bug that I am aware of and I think you may be seeing the same problem. This is what I know from testing on my server with autobalance and NPCBots: if you enter Onyxia's Lair while in a group, autobalance scaling does not seem to work and the mob HP seems to be set for level 80 (although the mobs are level 60-63).

If you enter Onyxia's Lair WITHOUT a group, you will be teleported into the level 60 version which scales correctly with autobalance. At that point I can exit the dungeon, and re-enter with a group and everything seems to work. I have not looked into what is causing this issue as I have found this work-around.

**Comment by webtectonics** [comment]
You need a raid group to enter the zone though... Even with the .teleport command...

**Comment by atrapalis** [comment]
Yes you do by default but there is a setting (I think in AzerothCore's worldserver.conf) to disable the group/raid requirement for zoning into raids.

**Comment by webtectonics** [comment]
Ahhhhhh.  Thank you, I'll give it a shot!

**Comment by webtectonics** [comment]
@atrapalis - I disabled the group/raid requirement and teleported in solo via the .teleport command.  I'm still seeing the following below though.  Am I missing anything?

![image](https://github.com/ZhengPeiRu21/mod-individual-progression/assets/16596507/b52287f8-3a37-4079-bcbe-9566675ce736)

**Comment by atrapalis** [comment]
@webtectonics I tested this when I initially replied by zoning into the raid by walking to the portal. I am trying to recreate your issue using .teleport onyxia and will edit this comment.

**Comment by webtectonics** [comment]
We are all level 60 and in Phase 1 still.  Only mods we are using is Individual Progress and Auto Balance.

I tried walking in as well.  What I tried doing was:
- Walked in solo with a raid difficulty of 10H. Same screenshot as your 1st one. Except my ID was 249-4.
- Zoned out, set difficulty to 25H.
- Set difficulty to 10H.  Zoned in solo.
No dice. Same situation as screenshot #1.  

I appreciate your help though.  Not sure what can be causing it.

**Comment by webtectonics** [comment]
Hey @atrapalis - is there any platform I can communicate with you on besides here? My 10 buddies just really want to do Onyxia so I'm trying to get to the bottom of this and see if I can work out a fix or a workaround.  Any help is much appreciated.  I'm relatively new to AzerothCore and the AutoBalance module.

**Comment by atrapalis** [comment]
Let's continue the discussion on #263
I'll try to look into this some more when I have time.
