### ISSUE TITLE
[Bug] Gurubashi Arena Timings are Wild

### ISSUE THREAD

**Issue by StraysFromPath** [ZhengPeiRu21/mod-individual-progression#221]
![image](https://github.com/ZhengPeiRu21/mod-individual-progression/assets/119371540/53938f0f-d32c-4ccd-9d40-1d0fad3616c7)

Gurubashi arena triggers at totally random times, such as 1:21pm.

It should occur every 3 hours server-time.

**Comment by ZhengPeiRu21** [comment]
I believe this is an AzerothCore upstream issue. I don't think I've changed anything related to the Gurubashi Arena timings.
