### ISSUE TITLE
Disable XP Config Options Broken

### ISSUE THREAD

**Issue by StraysFromPath** [ZhengPeiRu21/mod-individual-progression#223]
This setting works on normal plain azerothcore but something about this module breaks this option.

#    ToggleXP.Cost
#        Description: Cost of locking/unlocking XP
#        Default:     100000 - (10 Gold)
#

ToggleXP.Cost = 0

![image](https://github.com/ZhengPeiRu21/mod-individual-progression/assets/119371540/3c4007cf-7ca1-405a-afb3-b7af918e5240)

**Comment by StraysFromPath** [comment]
Temp fix / workaround until fixed is:

```
DELETE FROM `gossip_menu_option` WHERE (`MenuID` = 10638);
INSERT INTO `gossip_menu_option` (`MenuID`, `OptionID`, `OptionIcon`, `OptionText`, `OptionBroadcastTextID`, `OptionType`, `OptionNpcFlag`, `ActionMenuID`, `ActionPoiID`, `BoxCoded`, `BoxMoney`, `BoxText`, `BoxBroadcastTextID`, `VerifiedBuild`) VALUES
(10638, 0, 0, 'I no longer wish to gain experience.', 35531, 1, 1, 0, 0, 0, 0, 'Are you certain you wish to stop gaining experience?', 35535, 0),
(10638, 1, 0, 'I wish to start gaining experience again.', 35532, 1, 1, 0, 0, 0, 0, 'Are you certain you wish to start gaining experience again?', 35533, 0);


DELETE FROM `gossip_menu_option` WHERE (`MenuID` = 10638);
INSERT INTO `gossip_menu_option` (`MenuID`, `OptionID`, `OptionIcon`, `OptionText`, `OptionBroadcastTextID`, `OptionType`, `OptionNpcFlag`, `ActionMenuID`, `ActionPoiID`, `BoxCoded`, `BoxMoney`, `BoxText`, `BoxBroadcastTextID`, `VerifiedBuild`) VALUES
(10638, 0, 0, 'I no longer wish to gain experience.', 35531, 1, 1, 0, 0, 0, 0, 'Are you certain you wish to stop gaining experience?', 35535, 0),
(10638, 1, 0, 'I wish to start gaining experience again.', 35532, 1, 1, 0, 0, 0, 0, 'Are you certain you wish to start gaining experience again?', 35533, 0);
```

**Comment by ZhengPeiRu21** [comment]
Thanks for opening the issue. I don't remember doing anything in the module that should be impacting the cost of disabling XP, but I will look into it.

**Comment by StraysFromPath** [comment]
> Thanks for opening the issue. I don't remember doing anything in the module that should be impacting the cost of disabling XP, but I will look into it.

It's an issue with 

IndividualProgression.SimpleConfigOverride = 1

Which breaks lots of settings in an undocumented way.

**Comment by ZhengPeiRu21** [comment]
> > Thanks for opening the issue. I don't remember doing anything in the module that should be impacting the cost of disabling XP, but I will look into it.
> 
> It's an issue with
> 
> IndividualProgression.SimpleConfigOverride = 1
> 
> Which breaks lots of settings in an undocumented way.

SimpleConfigOverride does the following:
```
            sWorld->setIntConfig(CONFIG_WATER_BREATH_TIMER, 60000);
            sWorld->setIntConfig(CONFIG_LFG_OPTIONSMASK, 4);
            sWorld->setBoolConfig(CONFIG_OBJECT_QUEST_MARKERS, false);
            sWorld->setBoolConfig(CONFIG_OBJECT_SPARKLES, false);
            sWorld->setBoolConfig(CONFIG_PLAYER_SETTINGS_ENABLED, true);
            sWorld->setBoolConfig(CONFIG_LOW_LEVEL_REGEN_BOOST, false);
            sWorld->setBoolConfig(CONFIG_DBC_ENFORCE_ITEM_ATTRIBUTES, false);
```

This is the same as if you set these values in the worldserver.conf to the provided values. Nothing else is impacted by this setting. 

I tested on a build of AzerothCore without the module and still encountered the issue, so it appears this is an upstream bug.
