### ISSUE TITLE
20% of quest objects/npcs do not display the questgiver ! symbol.

### ISSUE THREAD

**Issue by StraysFromPath** [ZhengPeiRu21/mod-individual-progression#225]
The "re-enable quest markers" sql breaks several things previously reported such as quest sparkles, NPC hover quest info that tells you about drops, and map regions.

But it also breaks questgiver ! symbols for roughly 20% of quests.

![image](https://github.com/ZhengPeiRu21/mod-individual-progression/assets/119371540/c903805a-799f-46ee-86d0-9e5bfe9cf663)

Other examples:

Every bounty/wanted posted.

Every washed up remains in Darkshore.

Almost every chain quest.

**Comment by SuzumiK** [comment]
I can't confirm this.
Sparkles are a config option.
A ! showed up over a beached creature for me just now with a test character.

I suspect the quests are too low level for you to show up. You can adjust the low level cutoff in worldserver.conf (`Quests.LowLevelHideDiff`).

**Comment by StraysFromPath** [comment]
> I can't confirm this. Sparkles are a config option. A ! showed up over a beached creature for me just now with a test character.
> 
> I suspect the quests are too low level for you to show up. You can adjust the low level cutoff in worldserver.conf (`Quests.LowLevelHideDiff`).

Good idea I'll try the low level hide diff setting but I have low hopes as my char was lvl 21 and the quest is for 21-28. https://www.wowhead.com/classic/quest=1009/ruuzel

Sparkles config option doesn't make a difference. I have it set in my config and nothing sparkles anyway.

**Comment by SuzumiK** [comment]
Have you set `IndividualProgression.SimpleConfigOverride = 1` in `individualProgression.conf` (default)?

```
#        Description: If enabled, allow IndividualProgression module to set several AzerothCore values to suit individual progression
#                     Many of these config options were added with IndividualProgression in mind.
#                     For more advanced individual tuning, disable this option and change the respective values in worldserver.conf
#
#                     Changed options include:
#                     Water Breath Timer to 1 Minute (Vanilla value, changed to 3 Minutes in WotLK)
#       >>>>>         Disable Quest Object sparkle and object quest markers (added in patch 2.3)
#                     Enable PlayerSettings (required by Individual Progression module)
#                     Disable the LFG tool, aside from special Holiday events otherwise inaccessible
#                     Do not enforce DBC Item Attributes, so that Vanilla item changes can override client values
```

You need to turn this off to override the sparkle setting, but then you also need to set the other options to your liking.

**Comment by StraysFromPath** [comment]
> IndividualProgression.SimpleConfigOverrid

OMG thank you so much. My mistake. I thought =1 meant config WAS overriden, not that it would be over-ridden.

**Comment by coler-j** [comment]
What are the other specific options to set?

**Comment by coler-j** [comment]
Seems like 
- https://github.com/azerothcore/azerothcore-wotlk/blob/67f587d958fbd39bffecbabb1ba8322c2da4459e/src/server/apps/worldserver/worldserver.conf.dist#L2035
- Visibility.ObjectSparkles
- Visibility.ObjectQuestMarkers
- EnablePlayerSettings 
- DBC.EnforceItemAttributes
Not sure about LFG one
