### ISSUE TITLE
Goblin Transponder Not Working

### ISSUE THREAD

**Issue by StraysFromPath** [ZhengPeiRu21/mod-individual-progression#227]
https://www.wowhead.com/classic/quest=2843/gnomer-gooooone#comments

Quets chain for horde to get to gnomer works but the teleporter doesn't work.

![image](https://github.com/ZhengPeiRu21/mod-individual-progression/assets/119371540/7bcd5cf9-d434-4473-8698-6727866db5fe)

**Comment by Grimfeather** [comment]
you're right.
this has been an issue for a long time
https://github.com/azerothcore/azerothcore-wotlk/issues/8823

reported in 2021, still an open issue.
the teleporter does work to get back to booty bay.

needs to get fixed upstream.

**Comment by StraysFromPath** [comment]
> you're right. this has been an issue for a long time [azerothcore/azerothcore-wotlk#8823](https://github.com/azerothcore/azerothcore-wotlk/issues/8823)
> 
> reported in 2021, still an open issue. the teleporter does work to get back to booty bay.
> 
> needs to get fixed upstream.

It's the world's stupidest/easiest fix. You literally just have to type ".gob add" and spawn THIS OBJECT on the teleporter: 

https://wotlk.evowow.com/?object=142172

**Comment by ZhengPeiRu21** [comment]
Thanks for the issue report. Closing this in favor of the upstream AC issue.
