### ISSUE TITLE
StatBooster Crash last update

### ISSUE THREAD

**Issue by Maverickaes** [ZhengPeiRu21/mod-individual-progression#228]
As of last update from [Module Preview Build](https://github.com/ZhengPeiRu21/mod-individual-progression/releases/tag/20240122) the server crashes when enabling StatBooster in the config file.

Updating a previous build will also result in a crash as the config file for StatBooster is missing.

**Comment by StraysFromPath** [comment]
> As of last update from [Module Preview Build](https://github.com/ZhengPeiRu21/mod-individual-progression/releases/tag/20240122) the server crashes when enabling StatBooster in the config file.
> 
> Updating a previous build will also result in a crash as the config file for StatBooster is missing.

You can find the config in the full download.

You're right that all relevant configs should be in the update folder.

Here is my config, you can edit it as you wish. 

[statbooster.zip](https://github.com/ZhengPeiRu21/mod-individual-progression/files/14056948/statbooster.zip)

**Comment by StraysFromPath** [comment]
Oh you also need to run both SQL files from here (which ought to be pre-ran in the db).

https://github.com/AnchyDev/StatBooster/tree/master/data/sql

**Comment by Maverickaes** [comment]
Solved. Thank you!
