### ISSUE TITLE
[DK] [Talents] Rune Tap healing effected by healing config. 

### ISSUE THREAD

**Issue by XSNomad** [ZhengPeiRu21/mod-individual-progression#23]
Rune Tap and Improved Rune Tap should heal for 20% of Max health. 
https://www.wowhead.com/wotlk/spell=48982/rune-tap
https://www.wowhead.com/wotlk/spell=49489/improved-rune-tap

Current Behavior: 
healing reduction from IP effects this talent incorrectly healing for 20%*healing reduction

Expected Behavior: 
Talent / Skill should not be effected since it is a % based spell.

Notes: 
There may be other % based spells effected by this. Such as
https://www.wowhead.com/wotlk/spell=53563/beacon-of-light

**Comment by ZhengPeiRu21** [comment]
Fixed in https://github.com/ZhengPeiRu21/mod-individual-progression/commit/7100604d6aab2e8e2c085969c62369601b935f0c. I did not see any other spells that should need this custom fix, but please let me know if you encounter any more.
