### ISSUE TITLE
[Frequent Bug] Stuck in combat stance/can't autoattack

### ISSUE THREAD

**Issue by StraysFromPath** [ZhengPeiRu21/mod-individual-progression#230]
In almost 20% of combats you get softlocked into a combat animation way after combat has ended.

You cannot attack/eat/emote during this.

I think this may be related to NPCs having the same issue: https://github.com/ZhengPeiRu21/mod-individual-progression/issues/229

But it is much more annoying for players who must relog (and if in a dungeon this teleports you out of dunegeon).

**Comment by StraysFromPath** [comment]
![image](https://github.com/ZhengPeiRu21/mod-individual-progression/assets/119371540/2c33d6f7-712b-4996-a517-2fe1c67173e1)

**Comment by Grimfeather** [comment]
Is there a specific area or instance where this happens?
Does it happen everywhere for you?

I don't experience this at all.

**Comment by StraysFromPath** [comment]
> Is there a specific area or instance where this happens? Does it happen everywhere for you?
> 
> I don't experience this at all.
> 
> Only thing that comes to mind is maybe a stuck npc somewhere you're still in combat with. In the past I recall this happening with an npc stuck under the ground.

My players are reporting it all over the worlds. Instances, battlegrounds, open world, etc.

I've personally had this come up 25+ times since the update, and I have never seen it before in my life.

**Comment by ValeTheVioletMote** [comment]
I have seen it at least on hunters who weave between ranged and melee 
auto attacks.

**Comment by Day36512** [comment]
This is not an individual prog issue. This is either an core or client specific issue.

**Comment by ZhengPeiRu21** [comment]
Thank you for opening the issue! As always, I appreciate you taking the time to write things up and give detailed information.
As Day36512 stated, this wouldn't be something impacted by the module, so upstream AC would be a better place to file an issue report.
