### ISSUE TITLE
Group Loot & Quest Items Broken

### ISSUE THREAD

**Issue by StraysFromPath** [ZhengPeiRu21/mod-individual-progression#231]
When in a group and group loot is active quest items should alternate between player 1 and 2.

Currently one player loots ALL LOOT FROM ALL CORPSES until they are finished with the quest, and then player 2 gets exclusive loot.

This is ok for small community servers like mine but for a public one this is terrible as when someone is done with the quest they will leave the others high and dry.

![image](https://github.com/ZhengPeiRu21/mod-individual-progression/assets/119371540/44cbd640-b3ea-4c9e-8885-480d29f68bbb)

**Comment by ZhengPeiRu21** [comment]
Thank you for the issue report. As Vale commented, this is not something influenced by the module at all, but I appreciate you checking! I'll be closing this issue, but please feel free to re-open if you feel the module is causing a problem here.
