### ISSUE TITLE
Thunder Bluff Elevators Out of Sync

### ISSUE THREAD

**Issue by StraysFromPath** [ZhengPeiRu21/mod-individual-progression#232]
Both are up and down at the same time. Should ideally alternate. Likely same issue with other elevators (UC, Thousand Needles)

![image](https://github.com/ZhengPeiRu21/mod-individual-progression/assets/119371540/4ee0991f-3041-458f-a407-00f0ccce6f8a)

**Comment by Grimfeather** [comment]
Not related to this module, Individual progression.

But anyways, I just did a quick check
https://i.gyazo.com/a288dd1f5146ade5d3a3cd41964e9780.jpg
I can't reproduce it.

Does this happen over time ? are the elevators out of sync after a server restart?

**Comment by StraysFromPath** [comment]
Fixed by doing fresh install instead of "update".
