### ISSUE TITLE
[TBC tier 7] a few Zul'Aman npcs that should be hidden.

### ISSUE THREAD

**Issue by Grimfeather** [ZhengPeiRu21/mod-individual-progression#238]
I'm currently in the first tier of TBC, tier 7

Griftah ( https://www.wowhead.com/tbc/npc=19227/griftah )
This npc in Shattrath can be hidden/phased until he's needed in tier 10.
Right now he gives out the quest Oooh, Shinies! ( https://www.wowhead.com/tbc/quest=11130/oooh-shinies )

Same goes for Prigmon ( https://www.wowhead.com/tbc/npc=23761/prigmon )
this npc just outside of Zul'Aman gives the quest Tuskin' Raiders ( https://www.wowhead.com/tbc/quest=11164/tuskin-raiders )
This is also too early and should be phased until tier 10.

**Comment by ZhengPeiRu21** [comment]
Fixed in https://github.com/ZhengPeiRu21/mod-individual-progression/commit/a92ce5b1393dd37a531aca784a0d26c9a4de851b. Thanks Grimfeather!
