### ISSUE TITLE
Optional SQL for crafting cooldown timers

### ISSUE THREAD

**Issue by Grimfeather** [ZhengPeiRu21/mod-individual-progression#239]
I would like to suggest to add an optional SQL to restore the cooldown timers on several crafting recipes in Vanilla and TBC.

such as: Mooncloth, Transmute Arcanite, Primal Mooncloth, etc, etc

I'm sure many like it the way it is now with no cooldowns at all, so this for sure would get the optional tag.

**Comment by ZhengPeiRu21** [comment]
I agree this would be a good optional component to increase Vanilla accuracy.

**Comment by ZhengPeiRu21** [comment]
Implemented by Grimfeather in his recent PR. Thanks!
