### ISSUE TITLE
Add option to disable PvP Content Before ending progression

### ISSUE THREAD

**Issue by ZhengPeiRu21** [ZhengPeiRu21/mod-individual-progression#24]
Individual Progression is not balanced with PvP content in mind, and PvP gear also provides methods to break progression. There should exist an option to disable this content until players have reached end of the game.

**Comment by XSNomad** [comment]
As long as the progression for PVP gear stays. IE level 60 for level 60, etc.

**Comment by ZhengPeiRu21** [comment]
This has largely been resolved by restoring PvP rank progression requirements in 20f9993311a6004c5dfe216702f32a0d7b9fded5.
