### ISSUE TITLE
Resource nodes not spawning in Ghostlands

### ISSUE THREAD

**Issue by dlsmain** [ZhengPeiRu21/mod-individual-progression#243]
I'm getting some herb spawns but almost zero ore spawns.

**Comment by StraysFromPath** [comment]
> I'm getting some herb spawns but almost zero ore spawns.

Azerothcore is horrendous for herbs/mining nodes.

It's a real simple fix to use historical data from harvesting addons too.

Spots like Loch Modan have 600 ore nodes mostly stacked on each other but areas like Ghostlands (3x the size) have less than 20 nodes.

**Comment by dlsmain** [comment]
Thanks! Yeah, I've noticed some zones are definitely better for harvesting than others. I'll give this a shot.

**Comment by ZhengPeiRu21** [comment]
Thanks for opening an issue! This is not something in the scope of the module, but it is definitely something I also hope to see improved in upstream AC in the future. I believe there are some efforts in the works to improve it.
