### ISSUE TITLE
Dungeon Finder isn't work

### ISSUE THREAD

**Issue by Garashan** [ZhengPeiRu21/mod-individual-progression#244]
Hello all!
I'm using mod-individual progression with playerbots and transmog.
I'm leveling with my mage from lvl 1. In vanilla contect I saw that the dungeon finder isn't available. I thought that this is a blizzlike feature, because in vanilla there was no DF.
But I arrived lvl 80 and DF still isn't available. It said: "You do not have the world of warcraft expansion" or something similar (I'm not at the computherm now).
In the auth_db my account has expansion=2.

What do you think, what is the problem?

**Comment by Badgermilk0** [comment]
Change this to '0' in "individualProgression.conf":
#    IndividualProgression.SimpleConfigOverride
#        Description: If enabled, allow IndividualProgression module to set several AzerothCore values to suit individual progression
#                     Many of these config options were added with IndividualProgression in mind.
#                     For more advanced individual tuning, disable this option and change the respective values in worldserver.conf
#
#                     Changed options include:
#                     Water Breath Timer to 1 Minute (Vanilla value, changed to 3 Minutes in WotLK)
#                     Disable Quest Object sparkle and object quest markers (added in patch 2.3)
#                     Enable PlayerSettings (required by Individual Progression module)
#
#        Default:   1 - Enabled
#                   0 - Disabled
#
#

IndividualProgression.SimpleConfigOverride = 1

Also check this option in "worldserver.conf":
#
#     DungeonFinder.OptionsMask
#        Description: Dungeon and raid finder system.
#        Value is a bitmask consisting of:
#           LFG_OPTION_ENABLE_DUNGEON_FINDER    = 1,     Enable the dungeon finder browser
#           LFG_OPTION_ENABLE_RAID_BROWSER      = 2,     Enable the raid browser
#           LFG_OPTION_ENABLE_SEASONAL_BOSSES   = 4,     Enable seasonal bosses

#        Default:     5

DungeonFinder.OptionsMask = 5

**Comment by Garashan** [comment]
> Change this to '0' in "individualProgression.conf":
> 
> IndividualProgression.SimpleConfigOverride = 1
> 
> Also check this option in "worldserver.conf":
> 
> DungeonFinder.OptionsMask = 5

Thanks, it was my mistake.
This was in my conf file:
IndividualProgression.SimpleConfigOverride = 1
I changed the value to zero and it is working.

I think, that I will write a script that enable LFG tool if ProgressionState >= than a custom value.

**Comment by Badgermilk0** [comment]
> > Change this to '0' in "individualProgression.conf":
> > IndividualProgression.SimpleConfigOverride = 1
> > Also check this option in "worldserver.conf":
> > DungeonFinder.OptionsMask = 5
> 
> Thanks, it was my mistake. This was in my conf file: IndividualProgression.SimpleConfigOverride = 1 I changed the value to zero and it is working.
> 
> I think, that I will write a script that enable LFG tool if ProgressionState >= than a custom value.

Here is what the config overrides:

  if (sIndividualProgression->simpleConfigOverride)
        {
            sWorld->setIntConfig(CONFIG_WATER_BREATH_TIMER, 60000);
            sWorld->setIntConfig(CONFIG_LFG_OPTIONSMASK, 4);
            sWorld->setBoolConfig(CONFIG_OBJECT_QUEST_MARKERS, false);
            sWorld->setBoolConfig(CONFIG_OBJECT_SPARKLES, false);
            sWorld->setBoolConfig(CONFIG_PLAYER_SETTINGS_ENABLED, true);
            sWorld->setBoolConfig(CONFIG_LOW_LEVEL_REGEN_BOOST, false);
            sWorld->setBoolConfig(CONFIG_DBC_ENFORCE_ITEM_ATTRIBUTES, false);
        }
