### ISSUE TITLE
Preview build -  Warning in Worldserver.exe after update: Script named 'npc_reagent_banker' is not assigned in the database.

### ISSUE THREAD

**Issue by Badgermilk0** [ZhengPeiRu21/mod-individual-progression#245]
Warning Script named 'npc_reagent_banker' is not assigned in the database. appears after update of the preview package.

Can a manual fix be performed

**Comment by Badgermilk0** [comment]
Sorry - this issue only came up for first server start after update...
I'm assuming all is good!

**Comment by Badgermilk0** [comment]
To add more to this, the reagent banker NPC does not exist anymore.
The static one added to Stormwind is transformed and performs the Transmog fuctions and gossip options.

Using .npc add 190011 will spawn an NPC called "Ling" but the appearance and functions are that of 190010 (Transmog NPC).

**Comment by StraysFromPath** [comment]
Adding onto this it'd be nice if Zheng renamed Ling as doing ".lo cre ling" produces over 18,000 results so it's hard to actually find/spawn the npc.

**Comment by ZhengPeiRu21** [comment]
Thank you for reporting the issue, it looks like a conflict with the updated version of mod-transmog. I'll fix the reagent bank module.

**Comment by ZhengPeiRu21** [comment]
I've updated reagent-bank to fix this compatibility issue. The next release of the preview build will have this fix. In the meantime, you can fix it by running this SQL code:

```

SET
@Entry = 290011,
@Name = "Ling";

DELETE FROM `creature_template` WHERE `entry` = @Entry;

INSERT INTO `creature_template` (`entry`, `modelid1`, `modelid2`, `name`, `subname`, `IconName`, `gossip_menu_id`, `minlevel`, `maxlevel`, `exp`, `faction`, `npcflag`, `scale`, `rank`, `dmgschool`, `baseattacktime`, `rangeattacktime`, `unit_class`, `unit_flags`, `type`, `type_flags`, `lootid`, `pickpocketloot`, `skinloot`, `AIName`, `MovementType`, `HoverHeight`, `RacialLeader`, `movementId`, `RegenHealth`, `mechanic_immune_mask`, `flags_extra`, `ScriptName`) VALUES
(@Entry, 15965, 0, @Name, 'Reagent Banker', NULL, 0, 6, 6, 0, 35, 1, 1, 0, 0, 2000, 0, 1, 0, 7, 138412032, 0, 0, 0, '', 0, 1, 0, 0, 1, 0, 2, 'npc_reagent_banker');

DELETE FROM `creature` WHERE `id1`=290011;
DELETE FROM `creature` WHERE `id1`=190011;
INSERT INTO `creature` (`guid`, `id1`, `id2`, `id3`, `map`, `zoneId`, `areaId`, `spawnMask`, `phaseMask`, `equipment_id`, `position_x`, `position_y`, `position_z`, `orientation`, `spawntimesecs`, `wander_distance`, `currentwaypoint`, `curhealth`, `curmana`, `MovementType`, `npcflag`, `unit_flags`, `dynamicflags`, `ScriptName`, `VerifiedBuild`) VALUES (3110454, 290011, 0, 0, 0, 0, 0, 1, 1, 0, -8904.05, 616.934, 99.5233, 2.85328, 300, 0, 0, 120, 0, 0, 0, 0, 0, '', 0);
```

The correct ID for Ling is now 290011. Transmog co-opted the previous ID for the portable transmog NPC.

**Comment by Badgermilk0** [comment]
You are awsome!
