### ISSUE TITLE
[BUG QUEST] Jarl Needs a Blade - Wrong Text/Flags

### ISSUE THREAD

**Issue by StraysFromPath** [ZhengPeiRu21/mod-individual-progression#246]
https://www.wowhead.com/tbc/quest=1203/jarl-needs-a-blade

![image](https://github.com/ZhengPeiRu21/mod-individual-progression/assets/119371540/62ebaf87-f3d8-4d52-8e68-4f57aec38555)

it is using 3.3.5 quest description and map data (kill murloc, get quest item)

but it is set to 1.1.12 completion criteria (find a blacksmith, moonsteel claymore)

it can't be both

personally i just reset it to the 3.3.5 quest because as discussed in the wowhead comments it was a joke quest to give a 4g item which is hard to make to an npc for 35 silver

**Comment by Saniok88** [comment]
Sorry for the offtop, but it was not intended to be a joke for 4g, it was intended to be just another reason to grind/farm more money or mats to complete another activity (in this case just for a single quest). Vanilla, was the most time-sink expansion ever, BC was better (by getting rid of World  Buffs and Alchemy buff stacking), WOTLK is even better by allowing to craft scrolls, and making party buffs raid-wide. Any WoW expansion is a timesink, but Vanilla is worst of all (speaking of required time investment for raiding and to satisfy stupid raid leaders, who think, that raids should not be attempted without alchemy potion stacks and World Buffs, and other consumables).

For me, any version of this quest is fine, Vanilla is more "canon", and WOTLK version is more casual friendly, so fix it to any variant, please.

**Comment by ZhengPeiRu21** [comment]
Thank you for the issue report. In the spirit of the module and making Vanilla content accurate, I will update it to the correct 1.12 data and let anyone who would like to change it do so independently.

**Comment by ZhengPeiRu21** [comment]
Fix in https://github.com/ZhengPeiRu21/mod-individual-progression/commit/1e627059eb769e0b4d8bd8c3417bc28252fe6e11. Thanks for the issue report and the discussion!
