### ISSUE TITLE
Worldserver shows item errors due to item changes

### ISSUE THREAD

**Issue by Boxhead78** [ZhengPeiRu21/mod-individual-progression#249]
Hello, upon loading items, the worldserver shows some errors.

![grafik](https://github.com/ZhengPeiRu21/mod-individual-progression/assets/12766359/ce522b3f-3611-4c45-872e-276bfd2f1d86)
_Screenshot while starting the worldserver_

**Example for item entry 1014**
Error Message: "Item (Entry: 1014) has wrong Class value (1), must be (12)."
Item Changes from individual progression:

![grafik](https://github.com/ZhengPeiRu21/mod-individual-progression/assets/12766359/c3b7da42-4938-4abd-85a9-a28d68879b7d)
_Screenshot from the individual progression changes item entry 1014_

**Comment by ZhengPeiRu21** [comment]
Thank you for opening an issue. Please ensure DBC.EnforceItemAttributes is set to 0 in your worldserver.conf. This will allow the module to override item stats with their correct Vanilla stats and should no longer show the error.
