### ISSUE TITLE
[1-19][Quest][Priest][Dwarven] Garments of the Light Multiple People can not complete. 

### ISSUE THREAD

**Issue by XSNomad** [ZhengPeiRu21/mod-individual-progression#25]
Issue: 
When one person completes the NPC doesn't reset. 

Current Behavior: 
After casting Heal and Fort One person is able to complete the quest, but for the next person nothing happens. 

Expected Blizz like
NPC will reset after a short time to allow for more than one person to complete the quest. 

![image](https://user-images.githubusercontent.com/60951221/190835029-4ed874ac-62a6-410e-bf60-540a04540619.png)
![image](https://user-images.githubusercontent.com/60951221/190835037-2f392f42-8f2c-4af1-9b2f-2a490d582359.png)
After Rank 2 heal and fort
![image](https://user-images.githubusercontent.com/60951221/190835050-50b4c145-50a9-4557-ad70-5f42162851ab.png)
![image](https://user-images.githubusercontent.com/60951221/190835055-93c0d144-4725-47c5-9581-2a585fc92b5c.png)

**Comment by XSNomad** [comment]
![image](https://user-images.githubusercontent.com/60951221/190835081-cb500e8a-09ad-4a00-84c7-cae4c7c8e53e.png)

**Comment by ZhengPeiRu21** [comment]
I am not able to replicate this issue. Please make sure you are follow the instructions of the quest:
1. First heal with Lesser Heal (Rank 2)
2. Cast Power Word: Fortitude (Rank 1)

The order and rank of the spells is important. The quest will not proceed if incorrect spells are used. Please let me know if you are still able to see an issue with this even with correct spells, ranks, and order.
