### ISSUE TITLE
Module Config File Updates

### ISSUE THREAD

**Issue by StraysFromPath** [ZhengPeiRu21/mod-individual-progression#250]
Please provide a list/changelog of config file changes with each update.

When updating from an old to a new version it is very rare for people to want to delete their own config file with their changes in it.

But it's also hard to compare 2 text files to determine changes.

The latest update added at least 3-4 config options which are undocumented and cause errors on worldserver launch.

**Comment by Day36512** [comment]
That's what commits are for https://github.com/ZhengPeiRu21/mod-individual-progression/commit/e814c794c704590bef84998e6fe59d2f054c11ef

**Comment by ZhengPeiRu21** [comment]
I'll do my best to include config changes in the release notes in the future. As Day36512 mentioned, the commit history is the best source in case I ever forget to mention anything.
