### ISSUE TITLE
Naxx: Anub'Rhekan's Locust Swarm applies dot stacks before the cast has finished.

### ISSUE THREAD

**Issue by SuzumiK** [ZhengPeiRu21/mod-individual-progression#252]
In the level 60 version of Naxxramas, Anub'Rhekan's Locust Swarm applies dot stacks before the cast has finished. This makes it really hard to avoid the damage.
In the level 80 version, the dot only starts stacking once the cast has finished.

**Comment by ZhengPeiRu21** [comment]
Thank you for reporting this issue. I will look into it.
