### ISSUE TITLE
[Question] How individual progression triggers?

### ISSUE THREAD

**Issue by Saniok88** [ZhengPeiRu21/mod-individual-progression#253]
if i kill Kel'Thuzad, does it force me right away to next phase, or i can farm him as many times i want and only then speak with some NPC dialogue (or doing some custom quest) to manually trigger the next phase? So i can choose, or it is forced right away? Or it requires running some database script files?

**Comment by ZhengPeiRu21** [comment]
Individual Progression triggers will happen right away and are per-player. Players can be in different progression phases (this is why the module is titled Individual Progression.) If you would like to remain at a certain phase, you can set the max progression via the config:
IndividualProgression.ProgressionLimit = 0

Setting this to 5, for example, will not allow you to progress past Naxx40.
There is not currently a way to set a limit only for specific players, so this will affect everyone on your server.

I hope that helps! Please let me know if you have any further questions.
