### ISSUE TITLE
Npcbots No Gosssip Menu

### ISSUE THREAD

**Issue by Sukoshock** [ZhengPeiRu21/mod-individual-progression#255]
I mentioned this is my last issue, but figured it might be wise to make a separate entry.

The console command side of npcbots seems to be working fine, I am able to spawn npcs, and create new ones, but I cannot access their menus. The gossip icon shows up on mouse over, and when I click them, it plays the player character's speaking emote, but no menu appears. This happens on fresh installs of both the version from 03-04, and 01-22.

Edit: Jeez, I'm dense. I was editing the wrong config file. I had enabled the module in the wrong config. Enabling it in the correct one fixed the problem.

**Comment by ZhengPeiRu21** [comment]
I'm glad you got it working. I will go ahead and close this issue.
