### ISSUE TITLE
Multiple Major Errors on Fresh Clean Install

### ISSUE THREAD

**Issue by StraysFromPath** [ZhengPeiRu21/mod-individual-progression#256]
1) NPCBots errors due to the database changes. There's an SQL update to run which fixes this but the fresh new install shouldn't come with errors.

2) Statbooster errors due to no tables existing. You can run the Statbooster SQL files and also my tables with the install - https://github.com/AnchyDev/StatBooster/issues/26

This will not affect people negatively as the module is disabled by default.

**Comment by ZhengPeiRu21** [comment]
Thank you, I will include your Statbooster fixes in the update tomorrow.

**Comment by ZhengPeiRu21** [comment]
These errors should now be resolved in the latest release: https://github.com/ZhengPeiRu21/mod-individual-progression/releases/tag/20240418
