### ISSUE TITLE
Naxx: Four Horsemen use level 80 version of spells

### ISSUE THREAD

**Issue by SuzumiK** [ZhengPeiRu21/mod-individual-progression#258]
The four horsemen in Naxx40 appear to use the level 80 version of spells. For example, the tank is being hit by 5-6k Holy Bolts from Sir Zeliek. He then starts casting Condemnation, which does 3k damage per tick. Ouch!

**Comment by StraysFromPath** [comment]
> The four horsemen in Naxx40 appear to use the level 80 version of spells. For example, the tank is being hit by 5-6k Holy Bolts from Sir Zeliek. He then starts casting Condemnation, which does 3k damage per tick. Ouch!

A temporary workaround fix is to delete the wotlk naxx abilities from the database.

Then you can later re-add them once you reach wotlk phased content.

**Comment by SuzumiK** [comment]
> > The four horsemen in Naxx40 appear to use the level 80 version of spells. For example, the tank is being hit by 5-6k Holy Bolts from Sir Zeliek. He then starts casting Condemnation, which does 3k damage per tick. Ouch!
> 
> A temporary workaround fix is to delete the wotlk naxx abilities from the database.
> 
> Then you can later re-add them once you reach wotlk phased content.

But this would mean they perform no abilities at all, right? Or is there some kind of fallback mechanism that I'm not aware of?
