### ISSUE TITLE
Mount quest skills are present at trainers + very cheap cost

### ISSUE THREAD

**Issue by Defalion** [ZhengPeiRu21/mod-individual-progression#264]
Hello! 
I had installed this mod to try to simulate progression up to WoTLK. 
I use WotLK 3.3.5a client with AzerothCore + NPC Bots by Trickerer.
I installed this Individual Progression module, and I had read that it restores mount quests. 
I started a game as Paladin and I had immediately noticed that I can purchase mount for 33silver at any trainer (at lvl 40 obv). 
Is this supposed to be like this? I was expecting that I will be able to reach my mount only via quest and not just cheap purchase.

Also - somebody suggested that even if it exists at trainers - it should be expensive - around 80g. While my price currently is 33 silver.

**Comment by ZhengPeiRu21** [comment]
Thanks for the bug report. The level 60 mount was already changed to be only available from the relevant quests, as intended. The level 40 mount is available as a free instant-complete quest for Alliance paladins, as in Classic. For Horde Blood Elf paladins, the level 40 mount should be learned from a trainer, as was the case when they were introduced in TBC.
However, there was a bug present in that the Alliance mount shouldn't be available to be trained - it should only be available through the quest. I've resolved this in https://github.com/ZhengPeiRu21/mod-individual-progression/commit/f080f86f401be7fd7f44d3d1e1ba4c6df5d38bd6. Thanks again for reporting the issue!
