### ISSUE TITLE
[Feature Request] Paladin/Shaman Gear at 60 PvP Vendors

### ISSUE THREAD

**Issue by StraysFromPath** [ZhengPeiRu21/mod-individual-progression#267]
As title says

Horde Paladin / Alliance Shaman has no 60 pvp gear to buy.

I think this is worth the add as it's blizzlike for paladins to buy paladin pvp gear but the tbc/wotlk setup with belves/draenei griefs 2 classes.

**Comment by ZhengPeiRu21** [comment]
Thanks for the comment. I think this is a valid suggestion. However, as far as I'm aware, PvP gear is faction specific, and there is no level 60 PvP gear for Horde Paladins and Alliance Shamans. (I may be mistaken, as I'm less familiar with PvP aspects of the game.) In this case, this solution wouldn't be possible without either modifying the client to create custom items, or modifying existing PvP gear to be cross-faction.
Given only those options, I think I would prefer to existing situation where these characters do not have PvP gear available at this level and instead should seek out PvE gear, which I understand to be superior to PvP gear in Vanilla anyway. However, I'm open to feedback and will leave this issue open if there are others more familiar with PvP who would like to chime in.

**Comment by StraysFromPath** [comment]
> Thanks for the comment. I think this is a valid suggestion. However, as far as I'm aware, PvP gear is faction specific, and there is no level 60 PvP gear for Horde Paladins and Alliance Shamans. (I may be mistaken, as I'm less familiar with PvP aspects of the game.) In this case, this solution wouldn't be possible without either modifying the client to create custom items, or modifying existing PvP gear to be cross-faction. Given only those options, I think I would prefer to existing situation where these characters do not have PvP gear available at this level and instead should seek out PvE gear, which I understand to be superior to PvP gear in Vanilla anyway. However, I'm open to feedback and will leave this issue open if there are others more familiar with PvP who would like to chime in.

https://www.wowhead.com/wotlk/item-set=697/champions-redoubt#comments

The horde version of alliance paladin gear exists it just needs to be added to the vendors.

same for alliance shaman:

https://www.wowhead.com/wotlk/item-set=718/lieutenant-commanders-earthshaker

**Comment by StraysFromPath** [comment]
@ZhengPeiRu21 I found the items!

**Comment by ZhengPeiRu21** [comment]
Thank you! I didn't know that the items already existed but had just been removed. Thanks again for submitting your fixes. They've been added in https://github.com/ZhengPeiRu21/mod-individual-progression/commit/977a33dcbf76d24c38b852cdb75e56f7ce4168e9.
