### ISSUE TITLE
Quest Wrong ZoneID for Dungeon Set Quests - 

### ISSUE THREAD

**Issue by StraysFromPath** [ZhengPeiRu21/mod-individual-progression#269]
Quest "The Ectoplasmic Distiller" says to gather ash in Burning Steppes but the "go here, do this" icons/drawings are drawn on UnGoro crater.

**Comment by Grimfeather** [comment]
not an individual progression issue

**Comment by ZhengPeiRu21** [comment]
Thanks for noticing this bug. Please open an AzerothCore issue - the problem comes from upstream and isn't changed by the module. Thanks!
