### ISSUE TITLE
When capped by IPM Quests do not give extra gold and still display XP Gain

### ISSUE THREAD

**Issue by XSNomad** [ZhengPeiRu21/mod-individual-progression#27]
When completing a quest at progression cap bonus gold should be given and the "experience to receive" display should be removed.

**Comment by ZhengPeiRu21** [comment]
Could you give more detail about this issue? Is the extra gold actually not awarded or is this a visual issue in the quest details UI?

**Comment by ZhengPeiRu21** [comment]
This issue should be fixed when the linked PR is merge.

**Comment by ZhengPeiRu21** [comment]
The upstream PR has been merged and this issue has been resolved.
