### ISSUE TITLE
Anvilrage Soldier Hits WAY TOO HARD

### ISSUE THREAD

**Issue by StraysFromPath** [ZhengPeiRu21/mod-individual-progression#270]
![image](https://github.com/ZhengPeiRu21/mod-individual-progression/assets/119371540/9b479fa0-e237-4398-a68a-068001530dac)

Lvl 50 paladin tank with 4800 armor and they hit for 1200 each.

This is a level 51 mob.

**Comment by StraysFromPath** [comment]
For context my tank finds it easier to tank 25 mobs from LBRS (harder dungeon) than a single Anvilrage Soldier.

Anvilrage Soldier is set to 10x damage in the database and the other Anvilrage mobs range from 1.6 to 5.

I put it down to 5 and it still hurts.

**Comment by ZhengPeiRu21** [comment]
Please update to the latest version of the module. This was fixed in https://github.com/ZhengPeiRu21/mod-individual-progression/commit/2968451770b0eba5aaba31f7b8bd18dc08d702b0 about a month ago. The correct value should be 3.3.
