### ISSUE TITLE
Truesilver Boar / Figurine Broken

### ISSUE THREAD

**Issue by StraysFromPath** [ZhengPeiRu21/mod-individual-progression#271]
![image](https://github.com/ZhengPeiRu21/mod-individual-progression/assets/119371540/49bd2ac0-1855-4879-903a-a9544426e98c)

The lvl 49 mob is meant to fight with you but it has 109 hp and has no attacks. It's also the size of an ant.

![image](https://github.com/ZhengPeiRu21/mod-individual-progression/assets/119371540/bad9b2ce-2f13-4239-a767-ad4fbd4d356d)

**Comment by ZhengPeiRu21** [comment]
The module makes no modification to this creature. I believe this may be an upstream issue in AzerothCore.
