### ISSUE TITLE
Jewelcrafting Capped at 300 / Weird

### ISSUE THREAD

**Issue by StraysFromPath** [ZhengPeiRu21/mod-individual-progression#275]
There's like 4-5 jewelcrafting recipes for lvl 48 to 60 which require Jewelcraftng up to lvl 325/330 which can be learned at lvl 50.

These are hidden/locked behind the TBC portal so all the 48 to 60 jewels can't be learned/used.

I suggest adding the 300-375 training to Jewelcrafting trainers.

**Comment by Grimfeather** [comment]
I'm against this. That would be a custom change. It's always been like this. You have to go to Shattrath for training.
I think a mage or warlock could help you get there, but not sure about that.

**Comment by StraysFromPath** [comment]
> I'm against this. That would be a custom change. It's always been like this. You have to go to Shattrath for training. I think a mage or warlock could help you get there, but not sure about that.

You cannot go to Shattrath for training at level 50 during the classic progression stages of this module.

Which is the only time you'd care about the level 49-55 rings which are made.

Which can only be learned at Shattrath after you've finished Naxx.

It's a custom change but it's more blizzlike/realistic to have the professions relevant at the right level.
