### ISSUE TITLE
Soulforge Set Issues - 2 items 1/8

### ISSUE THREAD

**Issue by StraysFromPath** [ZhengPeiRu21/mod-individual-progression#278]
![image](https://github.com/ZhengPeiRu21/mod-individual-progression/assets/119371540/694b8ca5-dd3b-4545-8f48-01dd7d52b094)
![image](https://github.com/ZhengPeiRu21/mod-individual-progression/assets/119371540/431fa6b5-2fa1-421b-befe-7e71991fe5d1)

I have 2 soulforge items equipped but no set bonus as both say 1/8.

Possible issue with database or transmog npc?

**Comment by StraysFromPath** [comment]
I did some testing and I can confirm that transmog NPC removes set bonus.

This has major implications as you can transmog non-set items into set items and gain set bonuses.

**Comment by ZhengPeiRu21** [comment]
Thank you for the report. I don't think this is related to the Individual Progression module; I'd recommend opening an issue in the [transmog module repo](https://github.com/azerothcore/mod-transmog/issues)
