### ISSUE TITLE
Onyxia 40 Man

### ISSUE THREAD

**Issue by corey-allen** [ZhengPeiRu21/mod-individual-progression#279]
The only modules I have installed are:
- Individual Progression
- NPCBots
- Eluna Lua Scripts

I have my individual progression conf set to Progression Tier 6.

When I spawn in 39 Playerbots, add them to raid, give them all Drakefire Amulet and then attempt to enter Onyxia's Lair, I get the following error message on the server:

> InstanceMap::Add: player Admin (GUID Full: 0x0000000000000001 Type: Player Low: 1) is permanently bound to instance 249, 1, 0, false but he is being put into instance 249, 2, 0, true
> WORLD: failed to teleport player Admin (GUID Full: 0x0000000000000001 Type: Player Low: 1) to map 249 because of unknown reason!

Myself and all 39 bots are then teleported to my race's starting zone..

Any idea what the issue is?

**Comment by ZhengPeiRu21** [comment]
That is unusual. Does the issue still occur if you try to enter without any bots?

**Comment by corey-allen** [comment]
Nope, doesn't happen when I go in solo.

**Comment by Grimfeather** [comment]
+1 also having issues with getting npcbots to follow me inside.
it's a recent thing, because a few months ago I wasn't having this problem.
I can enter the instance still, the Warders inside are level 60-63, but the npcbots don't follow me in.

I do not get the error message, mentioned by Corey,  on the server.

**Comment by Grimfeather** [comment]
I compiled Azerothcore with PlayerBots and Individual progression today. To see if that would make a difference.
But no. PlayerBots do not follow me inside either. So I very much doubt it's an issue with the NPCbots.

**Comment by ZhengPeiRu21** [comment]
I'll find time to look into this issue. Thanks for the additional information.

**Comment by Grimfeather** [comment]
I found out what the problem was for npcbots.
it was a setting in worldserver.conf
NpcBot.Enable.Raid          = 0

after setting this to 1, the npcbots follow me inside again.

not sure yet about playerbots

**Comment by ZhengPeiRu21** [comment]
atrapalis kindly submitted a fix for this issue that I've just merged. Would you please confirm if it's now working correctly?

**Comment by ZhengPeiRu21** [comment]
This appears to be resolved, per comments in the related issue.
