### ISSUE TITLE
[Feature Request] Statbooster Module Upgrade

### ISSUE THREAD

**Issue by StraysFromPath** [ZhengPeiRu21/mod-individual-progression#282]
Hi Zheng,

Could you add this enhancemnet/extra for the statbooster in next build <3. It's an item to reroll the statbooster bonuses.

No affect on anyone else as its not spawned into world but huge effect for people like me using statbooster that will add it to their server economy with an npc.

https://github.com/AnchyDev/StatBoosterReroller/tree/master

**Comment by ZhengPeiRu21** [comment]
Sure, I will include this update in the next build.

**Comment by ZhengPeiRu21** [comment]
This has been included in the release today.
