### ISSUE TITLE
[FIX] PvP Vendors Missing Horde Paladin Sets

### ISSUE THREAD

**Issue by StraysFromPath** [ZhengPeiRu21/mod-individual-progression#283]
I have fixed this - alliance shaman is next

![image](https://github.com/ZhengPeiRu21/mod-individual-progression/assets/119371540/0fe2113d-1b07-4bd9-8a08-9647b904a7a5)

DELETE FROM `npc_vendor` WHERE (`entry` = 12792) AND (`item` IN (29612));
INSERT INTO `npc_vendor` (`entry`, `slot`, `item`, `maxcount`, `incrtime`, `ExtendedCost`, `VerifiedBuild`) VALUES
(12792, 0, 29612, 0, 0, 465, 0);

DELETE FROM `npc_vendor` WHERE (`entry` = 12792) AND (`item` IN (29613));
INSERT INTO `npc_vendor` (`entry`, `slot`, `item`, `maxcount`, `incrtime`, `ExtendedCost`, `VerifiedBuild`) VALUES
(12792, 0, 29613, 0, 0, 465, 0);

DELETE FROM `npc_vendor` WHERE (`entry` = 12792) AND (`item` IN (29614));
INSERT INTO `npc_vendor` (`entry`, `slot`, `item`, `maxcount`, `incrtime`, `ExtendedCost`, `VerifiedBuild`) VALUES
(12792, 0, 29614, 0, 0, 465, 0);

DELETE FROM `npc_vendor` WHERE (`entry` = 12792) AND (`item` IN (29615));
INSERT INTO `npc_vendor` (`entry`, `slot`, `item`, `maxcount`, `incrtime`, `ExtendedCost`, `VerifiedBuild`) VALUES
(12792, 0, 29615, 0, 0, 463, 0);

DELETE FROM `npc_vendor` WHERE (`entry` = 12792) AND (`item` IN (29616));
INSERT INTO `npc_vendor` (`entry`, `slot`, `item`, `maxcount`, `incrtime`, `ExtendedCost`, `VerifiedBuild`) VALUES
(12792, 0, 29616, 0, 0, 463, 0);

DELETE FROM `npc_vendor` WHERE (`entry` = 12792) AND (`item` IN (29617));
INSERT INTO `npc_vendor` (`entry`, `slot`, `item`, `maxcount`, `incrtime`, `ExtendedCost`, `VerifiedBuild`) VALUES
(12792, 0, 29617, 0, 0, 463, 0);

DELETE FROM `npc_vendor` WHERE (`entry` = 12792) AND (`item` IN (29600));
INSERT INTO `npc_vendor` (`entry`, `slot`, `item`, `maxcount`, `incrtime`, `ExtendedCost`, `VerifiedBuild`) VALUES
(12792, 0, 29600, 0, 0, 428, 0);

DELETE FROM `npc_vendor` WHERE (`entry` = 12792) AND (`item` IN (29601));
INSERT INTO `npc_vendor` (`entry`, `slot`, `item`, `maxcount`, `incrtime`, `ExtendedCost`, `VerifiedBuild`) VALUES
(12792, 0, 29601, 0, 0, 428, 0);

DELETE FROM `npc_vendor` WHERE (`entry` = 12792) AND (`item` IN (29602));
INSERT INTO `npc_vendor` (`entry`, `slot`, `item`, `maxcount`, `incrtime`, `ExtendedCost`, `VerifiedBuild`) VALUES
(12792, 0, 29602, 0, 0, 652, 0);

DELETE FROM `npc_vendor` WHERE (`entry` = 12792) AND (`item` IN (29603));
INSERT INTO `npc_vendor` (`entry`, `slot`, `item`, `maxcount`, `incrtime`, `ExtendedCost`, `VerifiedBuild`) VALUES
(12792, 0, 29603, 0, 0, 652, 0);

DELETE FROM `npc_vendor` WHERE (`entry` = 12792) AND (`item` IN (29604));
INSERT INTO `npc_vendor` (`entry`, `slot`, `item`, `maxcount`, `incrtime`, `ExtendedCost`, `VerifiedBuild`) VALUES
(12792, 0, 29604, 0, 0, 444, 0);

DELETE FROM `npc_vendor` WHERE (`entry` = 12792) AND (`item` IN (29605));
INSERT INTO `npc_vendor` (`entry`, `slot`, `item`, `maxcount`, `incrtime`, `ExtendedCost`, `VerifiedBuild`) VALUES
(12792, 0, 29605, 0, 0, 444, 0);

**Comment by ZhengPeiRu21** [comment]
Thanks for submitting this fix! Added in https://github.com/ZhengPeiRu21/mod-individual-progression/commit/977a33dcbf76d24c38b852cdb75e56f7ce4168e9.
