### ISSUE TITLE
[FIX] PvP Vendors Missing Alliance Shaman items

### ISSUE THREAD

**Issue by StraysFromPath** [ZhengPeiRu21/mod-individual-progression#284]
![image](https://github.com/ZhengPeiRu21/mod-individual-progression/assets/119371540/4c989dad-6891-4fa1-b0fd-07b62c841a8d)

DELETE FROM `npc_vendor` WHERE (`entry` = 12777) AND (`item` IN (29608));
INSERT INTO `npc_vendor` (`entry`, `slot`, `item`, `maxcount`, `incrtime`, `ExtendedCost`, `VerifiedBuild`) VALUES
(12777, 0, 29608, 0, 0, 465, 0);

DELETE FROM `npc_vendor` WHERE (`entry` = 12777) AND (`item` IN (29606));
INSERT INTO `npc_vendor` (`entry`, `slot`, `item`, `maxcount`, `incrtime`, `ExtendedCost`, `VerifiedBuild`) VALUES
(12777, 0, 29606, 0, 0, 465, 0);

DELETE FROM `npc_vendor` WHERE (`entry` = 12777) AND (`item` IN (29611));
INSERT INTO `npc_vendor` (`entry`, `slot`, `item`, `maxcount`, `incrtime`, `ExtendedCost`, `VerifiedBuild`) VALUES
(12777, 0, 29611, 0, 0, 465, 0);

DELETE FROM `npc_vendor` WHERE (`entry` = 12777) AND (`item` IN (29609));
INSERT INTO `npc_vendor` (`entry`, `slot`, `item`, `maxcount`, `incrtime`, `ExtendedCost`, `VerifiedBuild`) VALUES
(12777, 0, 29609, 0, 0, 463, 0);

DELETE FROM `npc_vendor` WHERE (`entry` = 12777) AND (`item` IN (29607));
INSERT INTO `npc_vendor` (`entry`, `slot`, `item`, `maxcount`, `incrtime`, `ExtendedCost`, `VerifiedBuild`) VALUES
(12777, 0, 29607, 0, 0, 463, 0);

DELETE FROM `npc_vendor` WHERE (`entry` = 12777) AND (`item` IN (29610));
INSERT INTO `npc_vendor` (`entry`, `slot`, `item`, `maxcount`, `incrtime`, `ExtendedCost`, `VerifiedBuild`) VALUES
(12777, 0, 29610, 0, 0, 463, 0);

DELETE FROM `npc_vendor` WHERE (`entry` = 12777) AND (`item` IN (29595));
INSERT INTO `npc_vendor` (`entry`, `slot`, `item`, `maxcount`, `incrtime`, `ExtendedCost`, `VerifiedBuild`) VALUES
(12777, 0, 29595, 0, 0, 428, 0);

DELETE FROM `npc_vendor` WHERE (`entry` = 12777) AND (`item` IN (29599));
INSERT INTO `npc_vendor` (`entry`, `slot`, `item`, `maxcount`, `incrtime`, `ExtendedCost`, `VerifiedBuild`) VALUES
(12777, 0, 29599, 0, 0, 428, 0);

DELETE FROM `npc_vendor` WHERE (`entry` = 12777) AND (`item` IN (29597));
INSERT INTO `npc_vendor` (`entry`, `slot`, `item`, `maxcount`, `incrtime`, `ExtendedCost`, `VerifiedBuild`) VALUES
(12777, 0, 29597, 0, 0, 652, 0);

DELETE FROM `npc_vendor` WHERE (`entry` = 12777) AND (`item` IN (29596));
INSERT INTO `npc_vendor` (`entry`, `slot`, `item`, `maxcount`, `incrtime`, `ExtendedCost`, `VerifiedBuild`) VALUES
(12777, 0, 29596, 0, 0, 652, 0);

DELETE FROM `npc_vendor` WHERE (`entry` = 12777) AND (`item` IN (29598));
INSERT INTO `npc_vendor` (`entry`, `slot`, `item`, `maxcount`, `incrtime`, `ExtendedCost`, `VerifiedBuild`) VALUES
(12777, 0, 29598, 0, 0, 444, 0);

DELETE FROM `npc_vendor` WHERE (`entry` = 12777) AND (`item` IN (29594));
INSERT INTO `npc_vendor` (`entry`, `slot`, `item`, `maxcount`, `incrtime`, `ExtendedCost`, `VerifiedBuild`) VALUES
(12777, 0, 29594, 0, 0, 444, 0);

**Comment by ZhengPeiRu21** [comment]
Thank you for submitting this fix! Added in https://github.com/ZhengPeiRu21/mod-individual-progression/commit/977a33dcbf76d24c38b852cdb75e56f7ce4168e9.
