### ISSUE TITLE
[FIX] Incorrect Mount Prices

### ISSUE THREAD

**Issue by StraysFromPath** [ZhengPeiRu21/mod-individual-progression#285]
![image](https://github.com/ZhengPeiRu21/mod-individual-progression/assets/119371540/837d9fc8-f785-400b-b271-dffdc0d309ec)

UPDATE `item_template` SET `BuyPrice` = 100000 WHERE (`entry` = 47100);
UPDATE `item_template` SET `BuyPrice` = 1000000 WHERE (`entry` = 12302);

**Comment by ZhengPeiRu21** [comment]
Thank you very much for the fix! Added in https://github.com/ZhengPeiRu21/mod-individual-progression/commit/7e5095c31b75263642abe5b0641fd8ac89ea1bdc.
