### ISSUE TITLE
Can't install module anymore

### ISSUE THREAD

**Issue by Purple-23** [ZhengPeiRu21/mod-individual-progression#288]
I successfully installed the module yesterday, but now there is a NAXX script error that is preventing the world server from launching:

Exception code: C0000005 ACCESS_VIOLATION
Fault address:  00007FF78EC02502 01:0000000000081502 C:\Azerothcore - Build\bin\RelWithDebInfo\worldserver.exe

Call stack:
Address   Frame     Function      SourceFile
00007FF78EC02502  0000008F92766840  spell_gluth_decimate::Register+C2  C:\AzerothCore\modules\mod-individual-progression\src\naxx40Scripts\boss_gluth_40.cpp line 279
00007FF78F4288B3  0000008F92766870  _SpellScript::_Register+13  C:\AzerothCore\src\server\game\Spells\SpellScript.cpp line 49
00007FF78F1A1612  0000008F92766A50  ScriptRegistry<SpellScriptLoader>::AddALScripts+82  C:\AzerothCore\src\server\game\Scripting\ScriptMgr.h line 772
00007FF78F1A6518  0000008F92766B50  ScriptMgr::LoadDatabase+58  C:\AzerothCore\src\server\game\Scripting\ScriptMgr.cpp line 178
00007FF78F1723FE  0000008F9276F280  World::SetInitialWorldSettings+959E  C:\AzerothCore\src\server\game\World\World.cpp line 2024
00007FF78EBD4E32  0000008F9276F8E0  main+1B02  C:\AzerothCore\src\server\apps\worldserver\Main.cpp line 310
00007FF78FD4DC20  0000008F9276F920  __scrt_common_main_seh+10C  D:\a\_work\1\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl line 288
00007FFEF0B4257D  0000008F9276F950  BaseThreadInitThunk+1D
00007FFEF1CAAF28  0000008F9276F9D0  RtlUserThreadStart+28

**Comment by ZhengPeiRu21** [comment]
Would you please test if https://github.com/ZhengPeiRu21/mod-individual-progression/commit/830574a1367680cb0568378c2e7a3d27d66ac650 fixed the problem?

**Comment by Grimfeather** [comment]
I just compiled the latest version.
I'm also having issues.

worldserver fails to launch.

-------------------

last few lines in server.log:

Loading Creature Text Locales...
>> Loaded 14027 Creature Text Locale in 48 ms
 
Loading Scripts...
Loading Script Waypoints For 63 Creature(s)...
>> Loaded 2363 Script Waypoint nodes in 9 ms

--------------------

crash log:

Revision: AzerothCore rev. 0289fd97dccb 2024-05-22 21:35:08 +0700 (npcbots_3.3.5 branch) (Win64, Release, Static)
Date 13:6:2024. Time 21:39 
//=====================================================
*** Hardware ***
Processor: Intel(R) Core(TM) i7-4770K CPU @ 3.50GHz
Number Of Processors: 8
Physical Memory: 16714052 KB (Available: 11387604 KB)
Commit Charge Limit: 41290052 KB

*** Operation System ***
Windows 10 Professional (Version 10.0, Build 19045)

//=====================================================
Exception code: C0000005 ACCESS_VIOLATION
Fault address:  00007FF771BE5F22 01:0000000000074F22 C:\WotLK AzerothCore\worldserver.exe

Registers:
RAX:000001F4F4EE8FF0
RBX:000001F4C125C590
RCX:00007FF771BE59F0
RDX:0000000006BA01D6
RSI:00007FF772C80828
RDI:0000000000000000
R8: 0000000000000040
R9: 0000000000000680
R10:190353EDE06F8D80
R11:0555555555555555
R12:0000000000000000
R13:000001F4C125C4F0
R14:00007FF772E0B920
R15:000001F400000001
CS:RIP:0033:00007FF771BE5F22
SS:RSP:002B:00000000651B69A0  RBP:00000000
DS:002B  ES:002B  FS:0053  GS:002B
Flags:00010202

Call stack:
Address   Frame     Function      SourceFile
00007FF771BE5F22  000000CF651B6A10  0001:0000000000074F22 C:\WotLK AzerothCore\worldserver.exe
00007FF7723A29C3  000000CF651B6A40  0001:00000000008319C3 C:\WotLK AzerothCore\worldserver.exe
00007FF77215947E  000000CF651B6C10  0001:00000000005E847E C:\WotLK AzerothCore\worldserver.exe
00007FF77215E66F  000000CF651B6D10  0001:00000000005ED66F C:\WotLK AzerothCore\worldserver.exe
00007FF77213A8BD  000000CF651BF450  0001:00000000005C98BD C:\WotLK AzerothCore\worldserver.exe
00007FF771BBD773  000000CF651BF810  0001:000000000004C773 C:\WotLK AzerothCore\worldserver.exe
00007FF772AFD330  000000CF651BF850  argon2id_verify_ctx+26F50
00007FFEBAD47344  000000CF651BF880  BaseThreadInitThunk+14
00007FFEBCCDCC91  000000CF651BF900  RtlUserThreadStart+21

Call stack:
Address   Frame     Function      SourceFile
00007FFEBCD2F3B4  000000CF651B4A70  NtGetContextThread+14
00000000000003D4  000000CF651B4A78  0000:0000000000000000 
000000000000000D  000000CF651B4A80  0000:0000000000000000 
000000CF651B5835  000000CF651B4A88  0000:0000000000000000 
000000CF651B5B00  000000CF651B4A90  0000:0000000000000000 
00000000000003D8  000000CF651B4A98  0000:0000000000000000 

Call stack:
Address   Frame     Function      SourceFile
00007FFEBCD30FF4  000000CF654FF890  ZwWaitForWorkViaWorkerFactory+14
00007FFEBCCDD407  000000CF654FFB90  TpReleaseCleanupGroupMembers+747
00007FFEBAD47344  000000CF654FFBC0  BaseThreadInitThunk+14
00007FFEBCCDCC91  000000CF654FFC40  RtlUserThreadStart+21

Call stack:
Address   Frame     Function      SourceFile
00007FFEBCD30FF4  000000CF655FF8C0  ZwWaitForWorkViaWorkerFactory+14
00007FFEBCCDD407  000000CF655FFBC0  TpReleaseCleanupGroupMembers+747
00007FFEBAD47344  000000CF655FFBF0  BaseThreadInitThunk+14
00007FFEBCCDCC91  000000CF655FFC70  RtlUserThreadStart+21

Call stack:
Address   Frame     Function      SourceFile
00007FFEBCD30FF4  000000CF656FFAA0  ZwWaitForWorkViaWorkerFactory+14
00007FFEBCCDD407  000000CF656FFDA0  TpReleaseCleanupGroupMembers+747
00007FFEBAD47344  000000CF656FFDD0  BaseThreadInitThunk+14
00007FFEBCCDCC91  000000CF656FFE50  RtlUserThreadStart+21

Call stack:
Address   Frame     Function      SourceFile
00007FFEBCD2D684  000000CF657FF730  NtRemoveIoCompletion+14
00007FFEBA6CE6AF  000000CF657FF790  GetQueuedCompletionStatus+4F
00007FF771BB49B9  000000CF657FF870  0001:00000000000439B9 C:\WotLK AzerothCore\worldserver.exe
00007FF771BB9EEC  000000CF657FF930  0001:0000000000048EEC C:\WotLK AzerothCore\worldserver.exe
00007FF771BB9DA3  000000CF657FF990  0001:0000000000048DA3 C:\WotLK AzerothCore\worldserver.exe
00007FF771B9EF1A  000000CF657FF9C0  0001:000000000002DF1A C:\WotLK AzerothCore\worldserver.exe
00007FFEBAA81BB2  000000CF657FF9F0  _configthreadlocale+92
00007FFEBAD47344  000000CF657FFA20  BaseThreadInitThunk+14
00007FFEBCCDCC91  000000CF657FFAA0  RtlUserThreadStart+21

Call stack:
Address   Frame     Function      SourceFile
00007FFEBCD2D684  000000CF658FFAF0  NtRemoveIoCompletion+14
00007FFEBA6CE6AF  000000CF658FFB50  GetQueuedCompletionStatus+4F
00007FF771BB49B9  000000CF658FFC30  0001:00000000000439B9 C:\WotLK AzerothCore\worldserver.exe
00007FF771BB9EEC  000000CF658FFCF0  0001:0000000000048EEC C:\WotLK AzerothCore\worldserver.exe
00007FF771BB9DA3  000000CF658FFD50  0001:0000000000048DA3 C:\WotLK AzerothCore\worldserver.exe
00007FF771B9EF1A  000000CF658FFD80  0001:000000000002DF1A C:\WotLK AzerothCore\worldserver.exe
00007FFEBAA81BB2  000000CF658FFDB0  _configthreadlocale+92
00007FFEBAD47344  000000CF658FFDE0  BaseThreadInitThunk+14
00007FFEBCCDCC91  000000CF658FFE60  RtlUserThreadStart+21

Call stack:
Address   Frame     Function      SourceFile
00007FFEBCD30F94  000000CF659FFCC0  NtWaitForAlertByThreadId+14
00007FFEBCCF5601  000000CF659FFD40  RtlSleepConditionVariableSRW+131
00007FFEBA6E5479  000000CF659FFD80  SleepConditionVariableSRW+29
00007FFEA59B22C5  000000CF659FFDB0  _Cnd_wait+25
00007FF772A6F268  000000CF659FFDE0  0001:0000000000EFE268 C:\WotLK AzerothCore\worldserver.exe
00007FF771C453CF  000000CF659FFE10  0001:00000000000D43CF C:\WotLK AzerothCore\worldserver.exe
00007FFEBAA81BB2  000000CF659FFE40  _configthreadlocale+92
00007FFEBAD47344  000000CF659FFE70  BaseThreadInitThunk+14
00007FFEBCCDCC91  000000CF659FFEF0  RtlUserThreadStart+21

Call stack:
Address   Frame     Function      SourceFile
00007FFEBCD30F94  000000CF65AFF6E0  NtWaitForAlertByThreadId+14
00007FFEBCCF5601  000000CF65AFF760  RtlSleepConditionVariableSRW+131
00007FFEBA6E5479  000000CF65AFF7A0  SleepConditionVariableSRW+29
00007FFEA59B22C5  000000CF65AFF7D0  _Cnd_wait+25
00007FF772A6F268  000000CF65AFF800  0001:0000000000EFE268 C:\WotLK AzerothCore\worldserver.exe
00007FF771C453CF  000000CF65AFF830  0001:00000000000D43CF C:\WotLK AzerothCore\worldserver.exe
00007FFEBAA81BB2  000000CF65AFF860  _configthreadlocale+92
00007FFEBAD47344  000000CF65AFF890  BaseThreadInitThunk+14
00007FFEBCCDCC91  000000CF65AFF910  RtlUserThreadStart+21

Call stack:
Address   Frame     Function      SourceFile
00007FFEBCD30F94  000000CF65BFFA20  NtWaitForAlertByThreadId+14
00007FFEBCCF5601  000000CF65BFFAA0  RtlSleepConditionVariableSRW+131
00007FFEBA6E5479  000000CF65BFFAE0  SleepConditionVariableSRW+29
00007FFEA59B22C5  000000CF65BFFB10  _Cnd_wait+25
00007FF772A6F268  000000CF65BFFB40  0001:0000000000EFE268 C:\WotLK AzerothCore\worldserver.exe
00007FF771C453CF  000000CF65BFFB70  0001:00000000000D43CF C:\WotLK AzerothCore\worldserver.exe
00007FFEBAA81BB2  000000CF65BFFBA0  _configthreadlocale+92
00007FFEBAD47344  000000CF65BFFBD0  BaseThreadInitThunk+14
00007FFEBCCDCC91  000000CF65BFFC50  RtlUserThreadStart+21

Call stack:
Address   Frame     Function      SourceFile
00007FFEBCD2D5E4  000000CF65CFF730  ZwWaitForSingleObject+14
00007FFEBA691C4E  000000CF65CFF7D0  WaitForSingleObjectEx+8E
00007FF771BB9D33  000000CF65CFF800  0001:0000000000048D33 C:\WotLK AzerothCore\worldserver.exe
00007FF771BBBB75  000000CF65CFF830  0001:000000000004AB75 C:\WotLK AzerothCore\worldserver.exe
00007FFEBAA81BB2  000000CF65CFF860  _configthreadlocale+92
00007FFEBAD47344  000000CF65CFF890  BaseThreadInitThunk+14
00007FFEBCCDCC91  000000CF65CFF910  RtlUserThreadStart+21

Call stack:
Address   Frame     Function      SourceFile
00007FFEBCD30F94  000000CF65DFF8C0  NtWaitForAlertByThreadId+14
00007FFEBCCF5601  000000CF65DFF940  RtlSleepConditionVariableSRW+131
00007FFEBA6E5479  000000CF65DFF980  SleepConditionVariableSRW+29
00007FFEA59B22C5  000000CF65DFF9B0  _Cnd_wait+25
00007FF771C50CF2  000000CF65DFFD60  0001:00000000000DFCF2 C:\WotLK AzerothCore\worldserver.exe
00007FF771C453CF  000000CF65DFFD90  0001:00000000000D43CF C:\WotLK AzerothCore\worldserver.exe
00007FFEBAA81BB2  000000CF65DFFDC0  _configthreadlocale+92
00007FFEBAD47344  000000CF65DFFDF0  BaseThreadInitThunk+14
00007FFEBCCDCC91  000000CF65DFFE70  RtlUserThreadStart+21
========================
Local Variables And Parameters

Call stack:
Address   Frame     Function      SourceFile
00007FF771BE5F22  000000CF651B6A10  0001:0000000000074F22 C:\WotLK AzerothCore\worldserver.exe

00007FF7723A29C3  000000CF651B6A40  0001:00000000008319C3 C:\WotLK AzerothCore\worldserver.exe

00007FF77215947E  000000CF651B6C10  0001:00000000005E847E C:\WotLK AzerothCore\worldserver.exe

00007FF77215E66F  000000CF651B6D10  0001:00000000005ED66F C:\WotLK AzerothCore\worldserver.exe

00007FF77213A8BD  000000CF651BF450  0001:00000000005C98BD C:\WotLK AzerothCore\worldserver.exe

00007FF771BBD773  000000CF651BF810  0001:000000000004C773 C:\WotLK AzerothCore\worldserver.exe

00007FF772AFD330  000000CF651BF850  argon2id_verify_ctx+26F50

00007FFEBAD47344  000000CF651BF880  BaseThreadInitThunk+14

00007FFEBCCDCC91  000000CF651BF900  RtlUserThreadStart+21


Call stack:
Address   Frame     Function      SourceFile
00007FFEBCD2F3B4  000000CF651B4A70  NtGetContextThread+14

000000000000033C  000000CF651B4A78  0000:0000000000000000 

000000000000000D  000000CF651B4A80  0000:0000000000000000 

000000CF651B5835  000000CF651B4A88  0000:0000000000000000 

000000CF651B5B00  000000CF651B4A90  0000:0000000000000000 

0000000000000370  000000CF651B4A98  0000:0000000000000000 

0000000000000001  000000CF651B4AA0  0000:0000000000000000 

00007FF771BCA451  000000CF651B4FD0  0001:0000000000059451 C:\WotLK AzerothCore\worldserver.exe

00007FF771BC8741  000000CF651B5660  0001:0000000000057741 C:\WotLK AzerothCore\worldserver.exe

00007FF771BC98E3  000000CF651B5960  0001:00000000000588E3 C:\WotLK AzerothCore\worldserver.exe

00007FFEBA79D827  000000CF651B5A80  UnhandledExceptionFilter+1E7

00007FFEBCD35898  000000CF651B5AC0  memset+1218

00007FFEBCD1CE56  000000CF651B5B30  __C_specific_handler+96

00007FFEBCD3292F  000000CF651B5B60  __chkstk+11F

00007FFEBCCE2554  000000CF651B6270  RtlRaiseException+484

00007FFEBCD3143E  000000CF651B6990  KiUserExceptionDispatcher+2E

00007FF771BE5F22  000000CF651B6A10  0001:0000000000074F22 C:\WotLK AzerothCore\worldserver.exe

00007FF7723A29C3  000000CF651B6A40  0001:00000000008319C3 C:\WotLK AzerothCore\worldserver.exe

00007FF77215947E  000000CF651B6C10  0001:00000000005E847E C:\WotLK AzerothCore\worldserver.exe

00007FF77215E66F  000000CF651B6D10  0001:00000000005ED66F C:\WotLK AzerothCore\worldserver.exe

00007FF77213A8BD  000000CF651BF450  0001:00000000005C98BD C:\WotLK AzerothCore\worldserver.exe

00007FF771BBD773  000000CF651BF810  0001:000000000004C773 C:\WotLK AzerothCore\worldserver.exe

00007FF772AFD330  000000CF651BF850  argon2id_verify_ctx+26F50

00007FFEBAD47344  000000CF651BF880  BaseThreadInitThunk+14

00007FFEBCCDCC91  000000CF651BF900  RtlUserThreadStart+21


Call stack:
Address   Frame     Function      SourceFile
00007FFEBCD30FF4  000000CF654FF890  ZwWaitForWorkViaWorkerFactory+14

00007FFEBCCDD407  000000CF654FFB90  TpReleaseCleanupGroupMembers+747

00007FFEBAD47344  000000CF654FFBC0  BaseThreadInitThunk+14

00007FFEBCCDCC91  000000CF654FFC40  RtlUserThreadStart+21


Call stack:
Address   Frame     Function      SourceFile
00007FFEBCD30FF4  000000CF655FF8C0  ZwWaitForWorkViaWorkerFactory+14

00007FFEBCCDD407  000000CF655FFBC0  TpReleaseCleanupGroupMembers+747

00007FFEBAD47344  000000CF655FFBF0  BaseThreadInitThunk+14

00007FFEBCCDCC91  000000CF655FFC70  RtlUserThreadStart+21


Call stack:
Address   Frame     Function      SourceFile
00007FFEBCD30FF4  000000CF656FFAA0  ZwWaitForWorkViaWorkerFactory+14

00007FFEBCCDD407  000000CF656FFDA0  TpReleaseCleanupGroupMembers+747

00007FFEBAD47344  000000CF656FFDD0  BaseThreadInitThunk+14

00007FFEBCCDCC91  000000CF656FFE50  RtlUserThreadStart+21


Call stack:
Address   Frame     Function      SourceFile
00007FFEBCD2D684  000000CF657FF730  NtRemoveIoCompletion+14

00007FFEBA6CE6AF  000000CF657FF790  GetQueuedCompletionStatus+4F

00007FF771BB49B9  000000CF657FF870  0001:00000000000439B9 C:\WotLK AzerothCore\worldserver.exe

00007FF771BB9EEC  000000CF657FF930  0001:0000000000048EEC C:\WotLK AzerothCore\worldserver.exe

00007FF771BB9DA3  000000CF657FF990  0001:0000000000048DA3 C:\WotLK AzerothCore\worldserver.exe

00007FF771B9EF1A  000000CF657FF9C0  0001:000000000002DF1A C:\WotLK AzerothCore\worldserver.exe

00007FFEBAA81BB2  000000CF657FF9F0  _configthreadlocale+92

00007FFEBAD47344  000000CF657FFA20  BaseThreadInitThunk+14

00007FFEBCCDCC91  000000CF657FFAA0  RtlUserThreadStart+21


Call stack:
Address   Frame     Function      SourceFile
00007FFEBCD2D684  000000CF658FFAF0  NtRemoveIoCompletion+14

00007FFEBA6CE6AF  000000CF658FFB50  GetQueuedCompletionStatus+4F

00007FF771BB49B9  000000CF658FFC30  0001:00000000000439B9 C:\WotLK AzerothCore\worldserver.exe

00007FF771BB9EEC  000000CF658FFCF0  0001:0000000000048EEC C:\WotLK AzerothCore\worldserver.exe

00007FF771BB9DA3  000000CF658FFD50  0001:0000000000048DA3 C:\WotLK AzerothCore\worldserver.exe

00007FF771B9EF1A  000000CF658FFD80  0001:000000000002DF1A C:\WotLK AzerothCore\worldserver.exe

00007FFEBAA81BB2  000000CF658FFDB0  _configthreadlocale+92

00007FFEBAD47344  000000CF658FFDE0  BaseThreadInitThunk+14

00007FFEBCCDCC91  000000CF658FFE60  RtlUserThreadStart+21


Call stack:
Address   Frame     Function      SourceFile
00007FFEBCD30F94  000000CF659FFCC0  NtWaitForAlertByThreadId+14

00007FFEBCCF5601  000000CF659FFD40  RtlSleepConditionVariableSRW+131

00007FFEBA6E5479  000000CF659FFD80  SleepConditionVariableSRW+29

00007FFEA59B22C5  000000CF659FFDB0  _Cnd_wait+25

00007FF772A6F268  000000CF659FFDE0  0001:0000000000EFE268 C:\WotLK AzerothCore\worldserver.exe

00007FF771C453CF  000000CF659FFE10  0001:00000000000D43CF C:\WotLK AzerothCore\worldserver.exe

00007FFEBAA81BB2  000000CF659FFE40  _configthreadlocale+92

00007FFEBAD47344  000000CF659FFE70  BaseThreadInitThunk+14

00007FFEBCCDCC91  000000CF659FFEF0  RtlUserThreadStart+21


Call stack:
Address   Frame     Function      SourceFile
00007FFEBCD30F94  000000CF65AFF6E0  NtWaitForAlertByThreadId+14

00007FFEBCCF5601  000000CF65AFF760  RtlSleepConditionVariableSRW+131

00007FFEBA6E5479  000000CF65AFF7A0  SleepConditionVariableSRW+29

00007FFEA59B22C5  000000CF65AFF7D0  _Cnd_wait+25

00007FF772A6F268  000000CF65AFF800  0001:0000000000EFE268 C:\WotLK AzerothCore\worldserver.exe

00007FF771C453CF  000000CF65AFF830  0001:00000000000D43CF C:\WotLK AzerothCore\worldserver.exe

00007FFEBAA81BB2  000000CF65AFF860  _configthreadlocale+92

00007FFEBAD47344  000000CF65AFF890  BaseThreadInitThunk+14

00007FFEBCCDCC91  000000CF65AFF910  RtlUserThreadStart+21


Call stack:
Address   Frame     Function      SourceFile
00007FFEBCD30F94  000000CF65BFFA20  NtWaitForAlertByThreadId+14

00007FFEBCCF5601  000000CF65BFFAA0  RtlSleepConditionVariableSRW+131

00007FFEBA6E5479  000000CF65BFFAE0  SleepConditionVariableSRW+29

00007FFEA59B22C5  000000CF65BFFB10  _Cnd_wait+25

00007FF772A6F268  000000CF65BFFB40  0001:0000000000EFE268 C:\WotLK AzerothCore\worldserver.exe

00007FF771C453CF  000000CF65BFFB70  0001:00000000000D43CF C:\WotLK AzerothCore\worldserver.exe

00007FFEBAA81BB2  000000CF65BFFBA0  _configthreadlocale+92

00007FFEBAD47344  000000CF65BFFBD0  BaseThreadInitThunk+14

00007FFEBCCDCC91  000000CF65BFFC50  RtlUserThreadStart+21


Call stack:
Address   Frame     Function      SourceFile
00007FFEBCD2D5E4  000000CF65CFF730  ZwWaitForSingleObject+14

00007FFEBA691C4E  000000CF65CFF7D0  WaitForSingleObjectEx+8E

00007FF771BB9D33  000000CF65CFF800  0001:0000000000048D33 C:\WotLK AzerothCore\worldserver.exe

00007FF771BBBB75  000000CF65CFF830  0001:000000000004AB75 C:\WotLK AzerothCore\worldserver.exe

00007FFEBAA81BB2  000000CF65CFF860  _configthreadlocale+92

00007FFEBAD47344  000000CF65CFF890  BaseThreadInitThunk+14

00007FFEBCCDCC91  000000CF65CFF910  RtlUserThreadStart+21


Call stack:
Address   Frame     Function      SourceFile
00007FFEBCD30F94  000000CF65DFF8C0  NtWaitForAlertByThreadId+14

00007FFEBCCF5601  000000CF65DFF940  RtlSleepConditionVariableSRW+131

00007FFEBA6E5479  000000CF65DFF980  SleepConditionVariableSRW+29

00007FFEA59B22C5  000000CF65DFF9B0  _Cnd_wait+25

00007FF771C50CF2  000000CF65DFFD60  0001:00000000000DFCF2 C:\WotLK AzerothCore\worldserver.exe

00007FF771C453CF  000000CF65DFFD90  0001:00000000000D43CF C:\WotLK AzerothCore\worldserver.exe

00007FFEBAA81BB2  000000CF65DFFDC0  _configthreadlocale+92

00007FFEBAD47344  000000CF65DFFDF0  BaseThreadInitThunk+14

00007FFEBCCDCC91  000000CF65DFFE70  RtlUserThreadStart+21

**Comment by ZhengPeiRu21** [comment]
Interesting. I'm unable to reproduce the issue with a fresh build. Did you re-run CMAKE before compiling?

**Comment by Grimfeather** [comment]
> Interesting. I'm unable to reproduce the issue with a fresh build. Did you re-run CMAKE before compiling?

yes i did

**Comment by Purple-23** [comment]
I tried using this latest version and still the same issue; world server will not start.  In the interim, I am using a version from 3 days ago.  Works great but would prefer the most up-to-date.

**Comment by ZhengPeiRu21** [comment]
For those having problems, are you using the NPCbots branch of AzerothCore? I believe it may be out of date with some of the most recent changes regarding spellscripts, which is causing the issue. You may need to merge it with the current AzerothCore master for it to work.

**Comment by Purple-23** [comment]
Yeah, I am also using NPCbots branch.  I will wait for it to update on Saturday. Thank you for all your work on the indiv progression module and figuring out this issue!

**Comment by Purple-23** [comment]
Feel free to close. The latest updates to npcbots fixed this
