### ISSUE TITLE
worldserver fails to start, segmentation fault

### ISSUE THREAD

**Issue by latchee** [ZhengPeiRu21/mod-individual-progression#289]
Hi There,

I have just freshly compiled AzerothCore with NPCBots (https://github.com/trickerer/AzerothCore-wotlk-with-NPCBots) with mod-individual-progression (only this module installed, obtained via git clone).
After cmake, make generated a few warning but no blocking errors.
However, when I try to start the server it fails at this point:

> Loading Scripts...
> Loading Script Waypoints For 63 Creature(s)...
> >> Loaded 2363 Script Waypoint nodes in 6 ms
> Segmentation fault

I have imported all sql scripts (apart from optional_*) in the acore_world.
Errors.log is unfortunately empty, so I cannot post anything from it.

Would you be able to help with this?

**Comment by ZhengPeiRu21** [comment]
Thanks for opening an issue. I believe the current NPCbots fork may be out of date with some of the most recent changes regarding spellscripts, which is causing the issue. You may need to merge it with the current AzerothCore master for it to work. Please also see https://github.com/ZhengPeiRu21/mod-individual-progression/issues/288, where others appear to be having the same problem. Hopefully we can get this worked out!

**Comment by latchee** [comment]
Hi,
Ok, thank you for your input. From what I can see, the NPCBot is scheduled to update every Saturday 05:00 AM UTC+0. Maybe after this update, the mod will work. I'll wait 24 hours then try to build again with latest commit. I'll let you know how it goes.
Cheers,

**Comment by latchee** [comment]
Last available commit from https://github.com/trickerer/AzerothCore-wotlk-with-NPCBots fixes this issue.
I am closing this issue :)
