### ISSUE TITLE
Can't level Poisons skill

### ISSUE THREAD

**Issue by wetferretz** [ZhengPeiRu21/mod-individual-progression#290]
Originally had an issue where Poisons skill was sitting at 0/0, and couldn't level it up to learn more poisons from rogue trainer. But now it's sitting at 4381/0 skill level, and I still can't learn more poisons from rogue trainer. 
![Screenshot_14](https://github.com/ZhengPeiRu21/mod-individual-progression/assets/170791262/ce550f62-dc83-424d-87a6-13b8fc0d1377)
![Screenshot_15](https://github.com/ZhengPeiRu21/mod-individual-progression/assets/170791262/4fa536d3-7ecd-43d1-98f7-1ac116ad80b5)

**Comment by ZhengPeiRu21** [comment]
It looks like your server may be missing the optional DBC files. Are you sure they are installed properly? There are optional files for both the server and the client.

**Comment by wetferretz** [comment]
Well I could have sworn I had done that, but installing those files again worked. Thanks!
