### ISSUE TITLE
sql error

### ISSUE THREAD

**Issue by cutdachez** [ZhengPeiRu21/mod-individual-progression#293]
Pulled latest build. Now have sql error when it attempts to update new sql. 

naxx40_creatures.sql': Table 'world.creature_template_model' doesn't exist♪◙

creature_model does not the above

Very new issue.

**Comment by ZhengPeiRu21** [comment]
Please ensure you have an up-to-date build of AzerothCore. You seem to be missing [this commit](https://github.com/azerothcore/azerothcore-wotlk/commit/d6d49a9e45e5eb59e06fe14d7e4107015fcc0e0e), which contains the creature_template_model change.

**Comment by cutdachez** [comment]
> Please ensure you have an up-to-date build of AzerothCore. You seem to be missing [this commit](https://github.com/azerothcore/azerothcore-wotlk/commit/d6d49a9e45e5eb59e06fe14d7e4107015fcc0e0e), which contains the creature_template_model change.

Updated fresh:
2024_04_07_00_creatures_objects.sql': Unknown column 'modelid1' in 'field list'♪◙

**Comment by ZhengPeiRu21** [comment]
Thank you for reporting this issue. All field model consistency issues should now be fixed as of https://github.com/ZhengPeiRu21/mod-individual-progression/commit/db9b87226e21a00152fb04772769b80163238ab7. Please make sure you have the latest version of the module and of AzerothCore.
