### ISSUE TITLE
Weak character after progressing beyond tier 5

### ISSUE THREAD

**Issue by aluveitie** [ZhengPeiRu21/mod-individual-progression#296]
I'm running AC with mod-individual-progression and mod-autobalance latest versions. 

After completing AQ/Naxx 40 we noticed our characters being suddenly very weak.
My paladin 60 is healing for 150 instead of the >2000 baseline of the spell. 
Also only have 2k health despite having almost 500 stamina. 

I re-tested setting back the progression level of my character to test.
As soon as progression level is >5 my heal/damage goes down the drain.

**Comment by ZhengPeiRu21** [comment]
This is intended behavior. When you complete an expansion, all end-game gear from that expansion receives a 3% penalty towards health/damage/healing. This means that a full set of Naxx40 gear will only be about 50% as strong as it should. The purpose of this is to make leveling in the newly available TBC content more interesting. Without this feature, your Naxx 40 gear wouldn't be replaced until TBC raid gear, and TBC leveling would be trivially easy. With the tuning, you should be able the same power level going into TBC content as you would be in level 58-60 questing gear, which is what the TBC content was tuned for.

This tuning can be adjusted or disabled in the config. Look for "IndividualProgression.PreviousGearTuning" in individualProgression.conf.

**Comment by aluveitie** [comment]
Thanks for the Hint, I'll check `IndividualProgression.PreviousGearTuning`.

At the moment the hit is massive, we're currently having issues killing level 55-58 mobs in eastern plaguelands.
Holy Light is healing just 10% of what it should normally.

**Comment by ZhengPeiRu21** [comment]
As a follow up to this, I looked more at the numbers and have adjusted to default tuning from 3% per item to 1% per item in https://github.com/ZhengPeiRu21/mod-individual-progression/commit/be7fe20a995c0a4e0c2f7e0f3f5f4aacf3929824. With the way the scaling interacts with the regular progression based Vanilla and TBC scaling, it was stacking in a way that made it much more potent than intended. Thanks for bringing up the issue!
