### ISSUE TITLE
Health Regeneration too low

### ISSUE THREAD

**Issue by ajgration** [ZhengPeiRu21/mod-individual-progression#3]
Noticed my warrior and mages HP regen seemed too low. Checked a few classic videos and formulas and confirmed suspicions. Below is the data I could find on the formulas, though they're not 100% accurate as some of the numbers don't match up and it is definitely different for lower levels. It's hard to find specifics as private server values seem to differ from retail. List currently incomplete, I'll add more data and video evidence when I have the time so we can start figuring out the formulas to get close enough to retail numbers.

**DATA**
https://wow.allakhazam.com/wiki/HP_Regen_%28WoW%29
https://wowwiki-archive.fandom.com/wiki/Health_regeneration
https://www.reddit.com/r/classicwow/comments/bpu07d/health_and_mana_regeneration_research/

60 Rogue Mod - 56 spirit, 19hp per tick
60 Rogue Classic - 53 spirit, 28.5hp per tick - https://www.youtube.com/watch?v=o-0haljPyRQ   
40 Rogue Classic - 54 spirit, 27hp per tick - https://www.youtube.com/watch?v=WoP2seY1_dc

1 Warrior Mod - 23 spirit, 6hp per tick
1 Warrior Classic - 23 spirit, 4.5hp per tick
60 Warrior Mod - 48 spirit, 30hp per tick
60 Warrior classic - 51 spirit, 48.5hp per tick - https://www.youtube.com/watch?v=9Mn-zto7i64
39 Warrior classic - 46 spirit, 35hp per tick - https://www.youtube.com/watch?v=DXxlhtYJoH0

60 DK Mod - 48 spirit, 30hp per tick (assuming this should probably be same value as warrior)

60 Hunter Mod - 74 spirit, 13hp p/tick
60 Hunter Mod - 138 spirit, 21hp p/tick

60 Shaman Mod - 105 spirit, 12hp p/tick
60 Shaman Mod - 172 spirit, 17hp p/tick

60 Paladin Mod - 76 spirit, 16hp per tick
60 Paladin Mod - 140 spirit, 24hp per tick

60 Druid Mod - 115 spirit, 11hp per tick
60 Druid Mod - 183 spirit, 15hp per tick

60 Mage Mod - 122 spirit, 8hp per tick
60 Mage Mod - 178 spirit, 11hp per tick
60 Mage Classic - 176 spirit, 17hp per tick - https://www.youtube.com/watch?v=gGYpy9Jbm7c

60 Warlock Mod - 114 spirit, 9hp per tick
60 Warlock Mod - 182spirit, 12hp per tick

60 Priest Mod - 133 spirit, 13hp per tick
60 Priest Mod - 203 spirit, 15hp per tick

I get this is not that important. Feel free to close if not worried or I'm wrong.

**Comment by ZhengPeiRu21** [comment]
Thank you for the detailed reporting! The gtoctregenhp_dbc values are from the Vanilla Client DBC, so they must be correct. But it is possible that the AzerothCore formula is not correct, or that the formula changed since Vanilla. I just check with Vmangos, and it appears they are use a manual formula and not load the DBC values at all. If we can confirm that AzerothCore has correct regen formula and matches WotLK correct regen values, then we can adjust the imported Vanilla values to accommodate that the formula is different than Vanilla time, otherwise I think this is an AzerothCore bug.

**Comment by ZhengPeiRu21** [comment]
I have done more research and confirm that for levels about 15, regen values are the same as base AzerothCore. There is not an advisable way for the module to change the regen formula, so fixing this is unfortunately outside the scope of this module. I feel the existing values are close enough that there is not a significant impact on the experience. I am currently investigate a related issue of that AzerothCore may be boosting low level regen values too much, but this is a separate issue.

I am going to close this issue as something that cannot be fix, but please comment and let me know if you think there is more discussion to be talk about.
