### ISSUE TITLE
Kill 'Em With Sleep Deprivation

### ISSUE THREAD

**Issue by Grimfeather** [ZhengPeiRu21/mod-individual-progression#304]
https://www.wowhead.com/quest=7702/kill-em-with-sleep-deprivation

Sleepy Dark Iron Workers and Chambermaid Pillaclencher are level 1 again.
I remember posting this issue before.
https://github.com/ZhengPeiRu21/mod-individual-progression/issues/155#issue-1821508012

the fix got undone somehow.

one difference, last time only the Chambermaid got fixed. 
this time please also fix the sleepy dark iron workers.
they both are set to level 1 in vanilla_creature_values.sql

**Comment by ZhengPeiRu21** [comment]
Thanks for reporting this regression. Fixed in https://github.com/ZhengPeiRu21/mod-individual-progression/commit/9ca57f20bc3b4f971fffc9f51dccd073aafc9571.
