### ISSUE TITLE
Compilation error on latest acore master: `getLevel` is deprecated

### ISSUE THREAD

**Issue by SuzumiK** [ZhengPeiRu21/mod-individual-progression#306]
A recent commit removed `getLevel`: https://github.com/azerothcore/azerothcore-wotlk/commit/21f86d1c3c0d48ca8f31c6d6f29005fe492a9a2e

`getLevel` is still used through the module. It does no longer compile with the latest acore version.

**Comment by StraysFromPath** [comment]
AzerothCore needs to stop fucking with core values. They're bricking every mod/module/custom content of the last 11 years by doing wierd stuff. They also broke all quest mods by removing the gold reward column which nothing used anyway.

**Comment by ZhengPeiRu21** [comment]
Thanks for reporting the issue. Fixed in https://github.com/ZhengPeiRu21/mod-individual-progression/commit/dd93a5fc7349f48f0016783a48b5beac59d32cb1.
