### ISSUE TITLE
MySQL Aborted after Update

### ISSUE THREAD

**Issue by samaelfox** [ZhengPeiRu21/mod-individual-progression#308]
![Screenshot 2024-07-22 122106](https://github.com/user-attachments/assets/724ffaed-c3cc-4ebd-b04f-21ba64ace330)
![Screenshot 2024-07-21 193304](https://github.com/user-attachments/assets/e639db5c-9cb6-4e21-8df1-111f62e09c41)

**Comment by ZhengPeiRu21** [comment]
You are using an old version of the repack. This issue was fixed in the latest release on July 10th. Please update.
