### ISSUE TITLE
Boat Gobject Moved Incorrectly

### ISSUE THREAD

**Issue by StraysFromPath** [ZhengPeiRu21/mod-individual-progression#309]
This gobject used to be placed correctly.

It's on the beach outside booty bay at 27.7/83.2 in stranglethorn vale.

![image](https://github.com/user-attachments/assets/2b25ce73-b92f-4ca2-b370-481f90d7152a)

**Comment by ZhengPeiRu21** [comment]
The module doesn't move this Gobject. This looks like it may be an AzerothCore upstream issue.
