### ISSUE TITLE
Thorium Quests Slightly Off Requirements

### ISSUE THREAD

**Issue by StraysFromPath** [ZhengPeiRu21/mod-individual-progression#311]
![image](https://github.com/user-attachments/assets/b270195a-40d5-40c9-9eb6-6104d9a5423e)

NPC 14567 Imperial Plate Quests

All say and ask for different numbers.

"I'll need 10 bars" "required items: 20 bars"

**Comment by ZhengPeiRu21** [comment]
Thanks for the issue report. I'll get this fixed.

**Comment by Grimfeather** [comment]
Also, Thorium Brotherhood (59) reputation rewards are wrong for these quests

Vanilla values are:
Imperial plate belt gives 250, should give 100 rep.
Imperial plate bracer gives 250, should give 100 rep.
Imperial plate shoulders gives 250, should give 100 rep.
Imperial plate boots gives 350, should give 150 rep
Imperial plate helm gives 500, should give 200 rep.
Imperial plate leggings gives 500, should give 200 rep.
Imperial plate chest gives 500, should give 200 rep.

**Comment by Grimfeather** [comment]
I've made 2 pull requests to fix this.

**Comment by ZhengPeiRu21** [comment]
Fixed via Grimfeather's PRs. Thanks!
