### ISSUE TITLE
Feature Request: Starting/Minimum Progression Level

### ISSUE THREAD

**Issue by StraysFromPath** [ZhengPeiRu21/mod-individual-progression#312]
As my server moves to TBC I'd like to be able to make it so all players can access TBC content without having to do Naxx.

But I'd still like them to have to progress through the TBC tiers.

Can we have a "starting/minimum progression level" applied to all characters so people are not left behind?

We can currently change in the config to adjust the maximum progression level but not the minimum.

**Comment by ZhengPeiRu21** [comment]
This feature already exists. Please use the following option in the config to set the starting progression level:
https://github.com/ZhengPeiRu21/mod-individual-progression/blob/dd93a5fc7349f48f0016783a48b5beac59d32cb1/conf/individualProgression.conf.dist#L239

**Comment by StraysFromPath** [comment]
> This feature already exists. Please use the following option in the config to set the starting progression level:
> 
> https://github.com/ZhengPeiRu21/mod-individual-progression/blob/dd93a5fc7349f48f0016783a48b5beac59d32cb1/conf/individualProgression.conf.dist#L239

Correct me if I am wrong but this only works for newly created characters.

Existing characters are "left behind" when a server progresses.

My server is moving into TBC so all the lvl 70s will not go back and carry people through molten core.
