### ISSUE TITLE
Timbermaw Quests - Reputation reward issue.

### ISSUE THREAD

**Issue by Grimfeather** [ZhengPeiRu21/mod-individual-progression#313]
Related to a report I made before
https://github.com/ZhengPeiRu21/mod-individual-progression/issues/171
There are still some Timbermaw quests that give too much reputation.

'timbermaw ally' quest gives 1400 rep, should be 150
https://www.wowhead.com/classic/quest=8460/timbermaw-ally

'feathers for grazle' quest gives 300 rep, should be 50
https://www.wowhead.com/classic/quest=8466/feathers-for-grazle

'feathers for nafien' quest gives 300 rep, should be 50
https://www.wowhead.com/classic/quest=8467/feathers-for-nafien

'speak to nafien' quest gives 100 rep, should be 25
https://www.wowhead.com/classic/quest=8462/speak-to-nafien

and there is another one, 'beads for Salfa'. should give 50 rep.
https://www.wowhead.com/classic/quest=8469/beads-for-salfa

-------

The fixes from my previous report (171) seem to not have been done correctly?
Example, deadwood of the north (8461)
https://www.wowhead.com/classic/quest=8461/deadwood-of-the-north
This quest now gave 600 rep. It was 1400, after the fix it's 600, but it should be 150.
something is multiplying the reputation by 4
also because it's giving me 1400 reputation, instead of 350 what it should give in WotLK.

-------

also, I just noticed two quests I reported in 171 weren't updated in the fix.
deadwood ritual totem (8470) gives 1400 rep. should be 150
https://www.wowhead.com/classic/quest=8470/deadwood-ritual-totem
winterfall ritual totem (8471) still gives 1400 rep. should be 150
https://www.wowhead.com/classic/quest=8471/winterfall-ritual-totem

**Comment by Grimfeather** [comment]
I found it.

in the database
acore_world/reputation_reward_rate

timbermaw is 576, it's set to 4x the reputation.

**Comment by ZhengPeiRu21** [comment]
Thanks for digging into this. Is this fixed by your PR https://github.com/ZhengPeiRu21/mod-individual-progression/pull/321?

**Comment by Grimfeather** [comment]
yes, can be closed
