### ISSUE TITLE
Fatal Error with aq_scripts.cpp when trying to CMake.

### ISSUE THREAD

**Issue by Thatharis** [ZhengPeiRu21/mod-individual-progression#314]
When I try to CMake, I recieve a fatal error that stops the whole operation from aq_scripts.cpp. Here is the log.
![image](https://github.com/user-attachments/assets/780a1e7c-a45d-4d28-b89b-da913cc9d38f)

**Comment by Thatharis** [comment]
I frequently update my AzerothCore as I suspect that this might have occured from an outdated piece of code, never happened before.

**Comment by Kabakaylen** [comment]
I am also experiencing this in windows while compiling. I am using playerbots module and fork. It is only the aq_scripts.cpp code that is throwing an error.

**Comment by Thatharis** [comment]
> I am also experiencing this in windows while compiling. I am using playerbots module and fork. It is only the aq_scripts.cpp code that is throwing an error.

I fixed mine manually, changed the incorrect code in aq_scripts.cpp. "SendWorldText" ---> "SendZoneText"

**Comment by ZhengPeiRu21** [comment]
Thanks for reporting the issue. Looks like the module was affected by a breaking upstream change. I've added the fix in https://github.com/ZhengPeiRu21/mod-individual-progression/commit/697f77ad65a4a72f49c83761330907a00ddb0e02.
