### ISSUE TITLE
Evie Whirlbrew sells Mooncloth recipe

### ISSUE THREAD

**Issue by Grimfeather** [ZhengPeiRu21/mod-individual-progression#316]
I noticed Evie Whirlbrew, the alchemy vendor in Everlook, sells the Mooncloth Pattern.

I checked vanilla_vendors.sql and found this:
/* NPC Evie Whirlbrew - 11188 */
/* Add Missing Vanilla item Pattern: Mooncloth */
DELETE FROM `npc_vendor` WHERE `entry` = 11188 AND `item` = 14526;
INSERT INTO `npc_vendor` (`entry`, `item`, `maxcount`, `incrtime`) VALUES (11188, 14526, 0, 0);
must be a mistake.

https://www.wowhead.com/classic/npc=11188/evie-whirlbrew#sells

Qia (trade goods supplies) already sells the mooncloth pattern.

**Comment by ZhengPeiRu21** [comment]
Nice catch. Thanks for submitting an issue. Fixed in https://github.com/ZhengPeiRu21/mod-individual-progression/commit/30041addc50a63c84549e70406d317c20cdbea7e.
