### ISSUE TITLE
NPCbots causes server to crash

### ISSUE THREAD

**Issue by Badgermilk0** [ZhengPeiRu21/mod-individual-progression#318]
After "some" update, NPC bot generation now causes a server crash, either by wandering bots in the world, or if trying to enter a BG with wander bot generation.

# Location: D:\Workshop\azerothcore-wotlk\src\server\game\AI\NpcBots\botdatamgr.cpp:177
# Function: SpawnWandererBot
# Condition: false

Server works if I disable NPC bots.

**Comment by ZhengPeiRu21** [comment]
Thank you for submitting an issue. Does this same issue happen when the module is not installed? If so, it sounds like an issue with NPCbots, not with Individual Progression.

**Comment by Badgermilk0** [comment]
It does not, so likely an NPCbot issue, so we can close this issue, but,
Is this the repository used in your "Module Preview Build":
https://github.com/trickerer/AzerothCore-wotlk-with-NPCBots

Thanks for an awsome project btw!
