### ISSUE TITLE
sendNotification Build Error

### ISSUE THREAD

**Issue by siegmeyerX** [ZhengPeiRu21/mod-individual-progression#323]
sendNotification on line 361 of IndividualProgressionPlayer.cpp causes a build error. 

Looking at a recent update to Azerothcore two days ago, sendNotification may need to be moved to chathandler.

![Screenshot 2024-08-12 092500](https://github.com/user-attachments/assets/14fb1704-f4fc-425a-ac24-3955d6e7b8a4)

**Comment by ZhengPeiRu21** [comment]
Fixed by https://github.com/ZhengPeiRu21/mod-individual-progression/pull/324. Thanks for submitting the fix!
