### ISSUE TITLE
Fatal Error in IndividualProgressionPlayer.cpp when iniatiating CMake.

### ISSUE THREAD

**Issue by Thatharis** [ZhengPeiRu21/mod-individual-progression#325]
![image](https://github.com/user-attachments/assets/9894c059-b816-4ad9-a087-0ac231987c22)

**Comment by Grimfeather** [comment]
this looks a lot like: https://github.com/ZhengPeiRu21/mod-individual-progression/pull/324

your build includes that fix?

**Comment by Thatharis** [comment]
I updated just last night moments before I sent this report and tried to CMake.

**Comment by Thatharis** [comment]
Fixed itself. I dunno how but it did.
