### ISSUE TITLE
15170 Rutgar Glyphshaper Wrong Gossips

### ISSUE THREAD

**Issue by StraysFromPath** [ZhengPeiRu21/mod-individual-progression#329]
![image](https://github.com/user-attachments/assets/39f95983-a071-45e3-a2a8-48e2ec8c3d2a)

Rutgar has Frankal's gossips.

Frankal has Frankal's gossips.

**Comment by Grimfeather** [comment]
not an individual progression issue

**Comment by ZhengPeiRu21** [comment]
Thanks for filing an issue. Grimfeather is correct; this isn't related to Individual Progression. It's not desirable to fix it in the module as that would mean AC users in general wouldn't get the fix. Please file an issue with AC upstream to get it fixed properly. Thanks!
