### ISSUE TITLE
Not compiling

### ISSUE THREAD

**Issue by htc16** [ZhengPeiRu21/mod-individual-progression#33]
Not compiling Zheng

![image](https://user-images.githubusercontent.com/58153179/194362035-88bb7d48-140f-46c5-9ffd-65c7ebd8c8de.png)

**Comment by ZhengPeiRu21** [comment]
Sorry, the MSVC compiler automatically fix this so I always miss these bugs. Thanks for the report! Fixed in https://github.com/ZhengPeiRu21/mod-individual-progression/commit/4fb1a9e4984668ba181a52ebe7f91b2de0477af2.
