### ISSUE TITLE
9596 Bannok Grimaxe Spawning Incorrectly

### ISSUE THREAD

**Issue by StraysFromPath** [ZhengPeiRu21/mod-individual-progression#332]
Bannock Grimaxe doesn't seem to appear in LBRS until AFTER you kill the final boss and are on your way back through to leave.

If your group clears and hearths you wouldn't even know he was there.

https://www.wowhead.com/classic/npc=9596/bannok-grimaxe#drops;mode:normal

**Comment by Grimfeather** [comment]
not an individual progression issue
And I did a few lbrs runs recently. I did run into Grimaxe on one of those runs.

**Comment by ZhengPeiRu21** [comment]
This content isn't changed by Individual Progression. It would be best to open an AzerothCore issue to see if others are having the same problem.
