### ISSUE TITLE
17822 Landen Stilwell missing quest-specific dialogue.

### ISSUE THREAD

**Issue by Secret-Bird** [ZhengPeiRu21/mod-individual-progression#333]
Expected behavior:

NPC 17822, Landen Stillwell, located in the dungeon of Shadowfang Keep, is intended to have special text providing information for Horde Paladins to locate the crate of Bloodforged Ingots for the quest "The Path of the Adept", and then NPC should subsequently transform into a worgen.

Current behavior:
The NPC has no special dialogue for characters on the quest, and the subsequent event does not trigger. 
<img width="460" alt="landen" src="https://github.com/user-attachments/assets/b99eee98-7e1c-49bd-899f-b81354adc71b">

**Comment by Grimfeather** [comment]
not an individual progression issue

**Comment by ZhengPeiRu21** [comment]
Thanks for filing an issue. Grimfeather, as always, is correct - this content wasn't changed between release and WotLK, so the Individual Progression module makes no changes to it. This needs to be fixed in AzerothCore upstream. Please open an issue there if you haven't yet. Thanks!
