### ISSUE TITLE
Seal of Ascension (UBRS Attunement) Bugged

### ISSUE THREAD

**Issue by StraysFromPath** [ZhengPeiRu21/mod-individual-progression#335]
Vaelan (10299) spawns in the instance.

![image](https://github.com/user-attachments/assets/6966dd18-21c1-4087-a6d6-45acef806fb3)

Database has both Seal of Ascension Quests linked to NPC 10296.

Thus, it is impossible to attune to UBRS.

**Comment by StraysFromPath** [comment]
![image](https://github.com/user-attachments/assets/fc27e3bb-784e-49b3-906f-15f42acdecde)

Similar issue.

I have the seal of ascension hand in, the adorned seal, and the quest, and he's bricked/red.

**Comment by sogladev** [comment]
You need a "Unadorned Seal of Ascension" to trigger him to transform

 https://wowgaming.altervista.org/aowow/?item=12219
