### ISSUE TITLE
Quest 679: "Call to Arms" Poor Experience Respawn Times

### ISSUE THREAD

**Issue by StraysFromPath** [ZhengPeiRu21/mod-individual-progression#336]
https://www.wowhead.com/classic/quest=679/call-to-arms

The Boulderfists were changed to have a 1 hour respawn.

You need to kill 15 of one and 10 of the other ogres.

Only 12 of one and 7 of the other exist in the world.

With a one hour respawn this quest becomes unplayably unfun to any single player (or group) farming the area.

**Comment by ZhengPeiRu21** [comment]
The module doesn't change the respawn time of any creatures. I agree this is a problem, but it is best solved in AzerothCore upstream. Please open an issue there. Thanks!
