### ISSUE TITLE
Beware of Pterrodax (4501)

### ISSUE THREAD

**Issue by StraysFromPath** [ZhengPeiRu21/mod-individual-progression#340]
Slay 115 should be 10 of one and 15 of the other.

![image](https://github.com/user-attachments/assets/db8fd6bb-7158-48f9-9fd6-4e5cdd180b23)

![image](https://github.com/user-attachments/assets/55a7b8e5-c6de-4cbb-87b5-0dbda919b2eb)

**Comment by ZhengPeiRu21** [comment]
Fixed in https://github.com/ZhengPeiRu21/mod-individual-progression/commit/a76becd1fd5b10206a44010d8ce2183488c3cd21. Thanks for the issue report!
