### ISSUE TITLE
10503 Jandice Barov Phases Out but Does NOT Phase Back In

### ISSUE THREAD

**Issue by StraysFromPath** [ZhengPeiRu21/mod-individual-progression#341]
Scholomancer Jandice Barov can phase out during the fight then never come back.

Very aggrieving for normal scholo group experience.

**Comment by ZhengPeiRu21** [comment]
Thanks for filing an issue. Individual Progression doesn't make any changes to the mechanics of this fight. Please file an issue with AC upstream to get it fixed properly. Thanks!
