### ISSUE TITLE
creature_template_model does not have any existing display (NPCbots and Instance Resetter)

### ISSUE THREAD

**Issue by TwHProx** [ZhengPeiRu21/mod-individual-progression#342]
![creature_template_model](https://github.com/user-attachments/assets/e73960a4-bfc7-43ac-bbf1-8dccf2d1bce6)

When starting my server and activating those modules the database is not populated. 
Don't know enough on how to correct.

**Comment by Grimfeather** [comment]
a little while ago AzerothCore moved the CreatureDisplayID from creature_template to creature_template_model

70000 to 70060 are all custom added entries in creature_template by an outdated module. npcbots in this case.
all those entries need to be added to creature_template_model.

you need to make sure you are using the latest AzerothCore + NPCbots
https://github.com/trickerer/AzerothCore-wotlk-with-NPCBots

**Comment by TwHProx** [comment]
AzerothCore rev. 4c5628726808 2024-07-10 15:50:21 -0600 (npcbots branch) (Win64, RelWithDebInfo, Static) (worldserver-daemon)
I downloaded the precompiled above, and followed the instructions. I didn't try to update anything.

**Comment by TwHProx** [comment]
![temo](https://github.com/user-attachments/assets/373f5d3d-f9c4-48f9-a588-cab5f9b760fc)
There is no creature_template_model in the database

**Comment by TwHProx** [comment]
> a little while ago AzerothCore moved the modelid columns from creature_template to creature_template_model
> 
> 70000 to 70060 are npcbots that did not have their model moved to creature_template_model. all those entries need to be added to creature_template_model.
> 
> you need to make sure you are using the latest AzerothCore + NPCbots https://github.com/trickerer/AzerothCore-wotlk-with-NPCBots
> 
> I think you tried to update your server but didn't do it correctly. let your server recreate the npcbots if you created custom npcbots yourself it gets more complicated.

I'm using the latest files, dbc, and revision of azerothcore individual progression.
AzerothCore rev. 4c5628726808 2024-07-10 15:50:21 -0600 (npcbots branch) (Win64, RelWithDebInfo, Static) (worldserver-daemon)
How do I let my server recreate the NPC-Bots:

**Comment by Grimfeather** [comment]
I'm not sure what your situation is. Where exactly did you download the server? Which instructions did you follow?

I can tell you what I just did to update my npcbots server.

I have 2 servers. One for playerbots, one for npcbots.
my npcbots server was in the same situation as yours. Still the old item_template, no item_template_model

I cloned the latest azerothcore with npcbots, added the individual progression module and reagent bank
I compiled it.

I checked the worldserver.conf file for updates, it had some so I used the new one that was created during compiling.

Running worldserver.exe updated all the databases.
it created the item_template_model database and moved all the information from item_template to it.

done.

Your precompiled server has issues then. It should have the creature_template_model

https://i.gyazo.com/1d84c07cd5c70ec97ea2c53540a2c5d1.png

I can offer you the server files I just compiled.
It has no instance resetter though, I just use a macro to reset instances:
.instance unbind all

**Comment by TwHProx** [comment]
sure would be nice.
can they run all the other stuff in individual progression pack?
mod-autobalance
mod-individual-progression
mod-reagent-bank
mod-transmog
The following modules are supported in the compiled binary but are disabled by default - they can be enabled through config options:

mod-ah-bot
mod-challenge-modes
mod-leech
mod-aoe-loot
mod-instance-reset
mod-pvp-titles
StatBooster
StatBoosterReroll
NPCBots

**Comment by Grimfeather** [comment]
No, what I can offer right now only has NPCbots, Individual progression and reagent bank.
All the other modules I did not include. 

If you want all those you'll have to wait for ZhengPei to update the preview build.
Sorry, but I'm not going to look them all up, compile it again and configure them all

**Comment by TwHProx** [comment]
I didn`t mean like that. I meant like If I run the server would it update the database from mine.
Downloading, thanks.

**Comment by ZhengPeiRu21** [comment]
Thanks for noticing this issue. This should be fixed in the latest version of the repack. Thanks Grimfeather for giving a solution in the meantime. Please let me know if you see any other problems!
