### ISSUE TITLE
Cannot verify progression state

### ISSUE THREAD

**Issue by erkankhan** [ZhengPeiRu21/mod-individual-progression#35]
I created a character from a GM account (my fault), but in order to fix it I changed the account to be a normal account, and verified that the character no longer has access to gm commands in-game. I've tried setting the characters progression through the console using the individualprogression set XX 0(also tried 1), but it does not seem to work, I can still enter the dark portal and I still get experience at lvl 60. How can I check a characters progressionlevel, or will this character be broken forever?

**Comment by ZhengPeiRu21** [comment]
Using a GM account, select the character and run the command .invidiualprogression set 0
This will reset progression for that character. You could also run a SQL command to delete the progression from that character from the character database if the GM command is not working for you for some reason.

**Comment by erkankhan** [comment]
That worked perfectly! Thank you so much for this amazing mod. For the future, is there any list of what content is locked behind progression stages? If there is, I think that would be amazing to have in the readme for the mod. Many thanks!

**Comment by ZhengPeiRu21** [comment]
> That worked perfectly! Thank you so much for this amazing mod. For the future, is there any list of what content is locked behind progression stages? If there is, I think that would be amazing to have in the readme for the mod. Many thanks!

I am happy it worked! I am hope soon to write better documentation on the progression stages, but right now the easiest way to see is just from the header file:
```
    PROGRESSION_START           = 0,
    PROGRESSION_MOLTEN_CORE     = 1,
    PROGRESSION_ONYXIA          = 2,
    PROGRESSION_BLACKWING_LAIR  = 3,
    PROGRESSION_PRE_AQ          = 4,
    PROGRESSION_AQ              = 5,
    PROGRESSION_NAXX40          = 6,
    PROGRESSION_TBC_TIER_1      = 7,  // Karazhan, Gruul's Lair, Magtheridon's Lair
    PROGRESSION_TBC_TIER_2      = 8,  // Serpentshrine Cavern, Tempest Keep
    PROGRESSION_TBC_TIER_3      = 9,  // Hyjal Summit and Black Temple
    PROGRESSION_TBC_TIER_4      = 10, // Zul'Aman
    PROGRESSION_TBC_TIER_5      = 11, // Sunwell Plateau
    PROGRESSION_WOTLK_TIER_1    = 12, // WotLK Naxx, EoE, OS
    PROGRESSION_WOTLK_TIER_2    = 13, // Ulduar
    PROGRESSION_WOTLK_TIER_3    = 14, // TotC
    PROGRESSION_WOTLK_TIER_4    = 15, // ICC
    PROGRESSION_WOTLK_TIER_5    = 16  // Ruby Sanctum
    ```
    
    

Thank you for try the module! I will close this issue because it seems to be resolved, but please let me know if you are run into any other trouble!
