### ISSUE TITLE
Strings/numbers variables not printing to chat correctly: %i instead of a number.

### ISSUE THREAD

**Issue by WuStangDan** [ZhengPeiRu21/mod-individual-progression#354]
![image](https://github.com/user-attachments/assets/edacf91c-1612-4537-98b7-48950836ef33)

As shown all variables print with the type, instead of the number itself. Was told this is related to azerothcore update.

**Comment by UniSpandex** [comment]
You need to replace some stuff Inside AutoBalance.cpp and Message.cpp. 
 I did this myself so far didn't have any problems, those smarter correct me if I'm wrong. 
This is the way I did it:
any of these three %u %i %s  replace them with  {}
%.3f   with  {:.3f}   %u%s with {}{} 

To get Current Player Difficulty Offset to display proper number for example
Edit Message.cpp with notepad++, and make sure it looks like this below.
{LOCALE_enUS, "Current Player Difficulty Offset = {}.|r"}

**Comment by WuStangDan** [comment]
My apologies. Should have posted this to autobalance. There seems to be an autobalance fix now. Will close this issue.
