### ISSUE TITLE
[Fix Included] Rattlecage Skull Droprate Incorrect (Should be 100%)

### ISSUE THREAD

**Issue by StraysFromPath** [ZhengPeiRu21/mod-individual-progression#356]
https://wotlk.evowow.com/?npc=1890

My warlock has killed 14 skeletons and has only 1 skull.

Should be 100% drop. Super easy fix but worth patching.

DELETE FROM `creature_loot_template` WHERE (`Entry` = 1890) AND (`Item` IN (0, 0, 6281));
INSERT INTO `creature_loot_template` (`Entry`, `Item`, `Reference`, `Chance`, `QuestRequired`, `LootMode`, `GroupId`, `MinCount`, `MaxCount`, `Comment`) VALUES
(1890, 6281, 0, 100, 1, 1, 0, 1, 1, 'Rattlecage Skeleton - Rattlecage Skull');

**Comment by Grimfeather** [comment]
I looked into this. The drop rate is indeed wrong. but it's not 100% either.

I watched 2 videos
https://www.youtube.com/watch?v=1vl-nPBKAKY
https://www.youtube.com/watch?v=vh24ePzPciY

both of them show a player having to kill 4 skeletons to get 3 skulls.
not a great sample size. but according to this the drop chance should be around 70 to 80%

I'll make a pull request for this.

**Comment by ZhengPeiRu21** [comment]
I believe this was fixed by https://github.com/ZhengPeiRu21/mod-individual-progression/pull/381. Thanks Grimfeather!
