### ISSUE TITLE
[Fix Included] Rockfist Added to Phalanx Loot Table

### ISSUE THREAD

**Issue by StraysFromPath** [ZhengPeiRu21/mod-individual-progression#357]
DELETE FROM `creature_loot_template` WHERE (`Entry` = 9502) AND (`Item` IN (11743));
INSERT INTO `creature_loot_template` (`Entry`, `Item`, `Reference`, `Chance`, `QuestRequired`, `LootMode`, `GroupId`, `MinCount`, `MaxCount`, `Comment`) VALUES
(9502, 11743, 0, 5, 0, 1, 0, 1, 1, '');

Phalanx should drop Rockfist.

Currently he cannot.

**Comment by ZhengPeiRu21** [comment]
Thanks for bringing up this issue. Fixed by https://github.com/ZhengPeiRu21/mod-individual-progression/pull/380.
