### ISSUE TITLE
Quest: Battle of Hillsbrad - wrong quest text

### ISSUE THREAD

**Issue by Badgermilk0** [ZhengPeiRu21/mod-individual-progression#362]
Hi,

Quest line: https://www.wowhead.com/classic/quest=541/battle-of-hillsbrad

Step 6: This quest should be marked as "Group" since the enemies are now elite.
Step 7: The Quest text references to bring a note to "Bragor Bloodfist" but it is in reality Varimathras

**Comment by Badgermilk0** [comment]
I confirmed that the zone_undercity.sql has been run.
In acore_world -> quest_template ->ID 14351: it references Varimathras correctly - it did not however ingame.

**Comment by Grimfeather** [comment]
I can see the error.
https://www.wowhead.com/classic/quest=550/battle-of-hillsbrad
that's step 7.
quest ID is 550
in quest_template under LogDescription and QuestDescription it indeed says "Bragor Bloodfist".

**Comment by ZhengPeiRu21** [comment]
Fixed by Grimfeather in https://github.com/ZhengPeiRu21/mod-individual-progression/pull/363. Thanks!
