### ISSUE TITLE
Question: NPCBots support - damage and healing reductions

### ISSUE THREAD

**Issue by Badgermilk0** [ZhengPeiRu21/mod-individual-progression#365]
Hi, does the current implementation affect the NPCbots?

ex. Classic x0.6 DPS for players, since the NPCBOts are not counted as players - does the code support so they are affected aswell?

**Comment by Grimfeather** [comment]
afaik the worldserver.conf covers this for npcbots. you can set their damage by bracket. 
It's not perfect as level 70 falls into the 70-79 range. so level 70 TBC content will be too easy with the following settings.
But heck, npcbots are so powerful, it will be easy regardless. you have to nerf them really hard.

#
#    NpcBot.Mult.Damage.Levels
#        Description: Multipliers for bots' damage by level: 0-9, 10-19, 20,29, ... , 70-79, 80+.
#                     At least 9 values required.
#        Default:     1.0
#        Minimum:     0.1
#        Maximum:    10.0

NpcBot.Mult.Damage.Levels = 0.6,0.6,0.6,0.6,0.6,0.6,0.6,1.0,1.0


the IndividualProgression.VanillaPowerAdjustment in individualProgression.conf does not effect npcbots.

**Comment by Badgermilk0** [comment]
Thank you Grimfeather - I believe this solves the feature request to align them slightly more to player power (even though they are indeed very powerful..)
