### ISSUE TITLE
Onyxias Lair 40 man - wrong message shown when un-able to enter.

### ISSUE THREAD

**Issue by Badgermilk0** [ZhengPeiRu21/mod-individual-progression#366]
When you try to enter Onyxias Lair - lv 60 - 40 man, you get the following message:
"You must be at last level [] and have item [] to enter"

I guess it should say level 60 and item Drakefire Amulet.

**Comment by sogladev** [comment]
this error is an AzerothCore issue https://github.com/azerothcore/azerothcore-wotlk/issues/20006

**Comment by Badgermilk0** [comment]
Upstream issue
