### ISSUE TITLE
Set Them Ablaze! - Missing elite Dark Iron Sentry

### ISSUE THREAD

**Issue by Grimfeather** [ZhengPeiRu21/mod-individual-progression#368]
In Searing Gorge
https://www.wowhead.com/classic/quest=3463/set-them-ablaze#comments

Three towers should have an elite Dark Iron Sentry, level 48, https://www.wowhead.com/classic/npc=8504/dark-iron-sentry
Right now a non elite Dark Iron Lookout is standing in it's place.
video: https://www.youtube.com/watch?v=qOAiGTAPbcs

Wowhead shows the Dark Iron Sentry still exists in tbc and wotlk, but that's false.

a comment here also confirms this.
https://www.wowhead.com/wotlk/npc=8504/dark-iron-sentry#comments

----------

also, Overseer Maltorius should have 2 elite Dark Iron Sentry adds, level 48
Right now he has 1 non elite Dark Iron Lookout standing next to him.
https://www.wowhead.com/classic/npc=14621/overseer-maltorius#comments

video: https://www.youtube.com/watch?v=j8_kIeM5VBI

----------

I'll try to fix this myself. just putting it here so I remember.

**Comment by ZhengPeiRu21** [comment]
Resolved by https://github.com/ZhengPeiRu21/mod-individual-progression/pull/369. Thanks Grimfeather!
