### ISSUE TITLE
professions.sql causing problems in the database after the newest update.

### ISSUE THREAD

**Issue by Thatharis** [ZhengPeiRu21/mod-individual-progression#376]
After the newest update, I've started getting this error message:

![image](https://github.com/user-attachments/assets/6804b18d-ecbf-4273-bb2c-393655d74d20)

>> Reapplying update "professions.sql" '6EF2581' -> 'B305771' (it changed)...
ERROR 1064 (42000) at line 868 in file: '/root/azerothcore-wotlk/modules/mod-individual-progression/sql/world/base/professions.sql': You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '18771, -201028, 0, 0, 0, 0),
(19187, -201028, 0, 0, 0, 0),
(21087, -201028, 0, 0' at line 1

Applying of file '/root/azerothcore-wotlk/modules/mod-individual-progression/sql/world/base/professions.sql' to database 'acore_world' failed! If you are a user, please pull the latest revision from the repository. Also make sure you have not applied any of the databases with your sql client. You cannot use auto-update system and import sql files from AzerothCore repository with your sql client. If you are a developer, please fix your sql query.
Could not update the World database, see log for details.

EDIT: Revision helped find and fix the problems with the sqls. Here are the problems:
professions.sql:
![image](https://github.com/user-attachments/assets/58c1e9b9-ea9e-4bdd-9374-462aab027111)
that semicolon shouldn't be there. It should be a comma.

zone_eversong_woods.sql:
There's no delete query for that insert.
![image](https://github.com/user-attachments/assets/19eb1a7b-75ef-4a04-9c0c-c95ac7528484)
DELETE FROM `creature_loot_template` WHERE `Entry`=15298 AND `Item`=20935;

**Comment by Grimfeather** [comment]
I noticed. I'm working on it now.

**Comment by ZhengPeiRu21** [comment]
This should now be resolved by https://github.com/ZhengPeiRu21/mod-individual-progression/pull/377. Thanks Grimfeather for the quick fix!
