### ISSUE TITLE
Trueaim Gauntlets

### ISSUE THREAD

**Issue by Grimfeather** [ZhengPeiRu21/mod-individual-progression#378]
![Trueaim](https://github.com/user-attachments/assets/01ee3a78-c223-4913-8322-e0d114d5d56f)
https://www.wowhead.com/classic/item=13255/trueaim-gauntlets

In item_changes.sql this item gets updated

/*  Trueaim Gauntlets  */
UPDATE `item_template` SET `stat_type1` = 0, `stat_value1` = 0, `stat_type2` = 0, `stat_value2` = 0, `spellid_1` = 17818, `spellid_2` = 15464, `spellid_3` = 27743, `spellid_4` = 27744 WHERE entry=13255;

17818 = increase bow +8 in classic, but +19 in wotlk
15464 = increased hit chance + 10, works correctly
27743 = increased gun + 8 in classic, but +19 in wotlk
27744 = increased crossbow +8 in classic, but +19 in wotlk

Now the issue I run into is that when I equip this item it increases my character`s bow, unarmed and polearms skills by 23
(sometimes daggers instead of polearms)

In classic this item gives +8 to bow, crossbow and guns, the +19 is perhaps to compensate for wotlk game mechanics,
but I don't understand where the +23 comes from when I check my skill increase when I equip the item.
I would like to understand how it increases unarmed and polearms and not crossbows.

Does anyone have any answers for me?

**Comment by StraysFromPath** [comment]
"Skill ratings" scale with player level like how 10 expertise is not actually 10 expertise at all levels.

25 expertise is 260 expertise at lvl 1 but 25 expertise is also 10 expertise at lvl 60.

I think a similar thing is occuring with weapon skills. It reads 19, which would be less at 80, and more at 60.

**Comment by Grimfeather** [comment]
alright. thanks SFP.

It's just that the item now looks strange. It received changes because it was altered in WotLK, 
but now it's still not exactly how it was during vanilla. Maybe the spells could be altered so it shows +8 instead of +19.
Also weird that I see my dagger and unarmed skill go up when I equip the gloves

But it's fine I guess, I'll just ignore the item.
