### ISSUE TITLE
d27982d The latest code recompilation was an error

### ISSUE THREAD

**Issue by gutoukuaiken** [ZhengPeiRu21/mod-individual-progression#388]
During the compilation of the latest https://github.com/liyunfan1223/azerothcore-wotlk.git code, an error is as follows:

Error C2065 "player" : No statement identifier modules C: \ develop \ azplayerbot - core \ modules \ mod - individual - progression \ SRC \ IndividualProgressionPlayer CPP, 324

**Comment by Grimfeather** [comment]
known issue. already made a pull request to fix it here:  https://github.com/ZhengPeiRu21/mod-individual-progression/pull/382

if you don't want to wait
go to azerothcore-wotlk\modules\mod-individual-progression\src
open IndividualProgressionPlayer.cpp

change line 322 to:
    bool OnUpdateFishingSkill(Player* player, int32 /*skill*/, int32 /*zone_skill*/, int32 chance, int32 roll) override
