### ISSUE TITLE
Getting an invalid when compiling with the newest version of playerbot, was not happening with previsly version

### ISSUE THREAD

**Issue by tmyrdal** [ZhengPeiRu21/mod-individual-progression#391]
Severity	Code	Description	Project	File	Line	Suppression State	Details
Error	C2065	'player': undeclared identifier	modules	C:\AzerothCore\modules\mod-individual-progression\src\IndividualProgressionPlayer.cpp	324		

Severity	Code	Description	Project	File	Line	Suppression State	Details
Warning	C4834	discarding return value of function with [[nodiscard]] attribute	modules	C:\AzerothCore\modules\mod-playerbots\src\factory\PlayerbotFactory.cpp	807		

Severity	Code	Description	Project	File	Line	Suppression State	Details
Error	LNK1181	cannot open input file '..\..\..\modules\RelWithDebInfo\modules.lib'	worldserver	C:\Build\src\server\apps\LINK	1

**Comment by Grimfeather** [comment]
known issue. already made a pull request to fix it here:  https://github.com/ZhengPeiRu21/mod-individual-progression/pull/382

If you don't want to wait, look at the 'files changed' section to see what you need to edit.

Or use my fork: https://github.com/Grimfeather/mod-individual-progression
It has my pull requests already merged.

**Comment by ZhengPeiRu21** [comment]
Grimfeather's PR has been merged, so this should now be fixed. Thanks!
