### ISSUE TITLE
Remove Spell Ranks learned by AQ20 Books

### ISSUE THREAD

**Issue by Grim93** [ZhengPeiRu21/mod-individual-progression#4]
Not sure if this is a design choice or not, but I noticed that spells learnt from AQ20 books were still on the NPC trainers. I went ahead and changed my professions.sql to remove these spells. I'm assuming the warlock books (Shadowbolt X, Immolate VIII, Corruption VII, Shadow Ward IV) will need to be added back to boss tables too if this is added, as well as Deadly Poison V. Below is the updated table of all spells learned through books.

-- Class skills taught by dropped items
DELETE
FROM npc_trainer
WHERE SpellID IN (26991,
                  27127,
                  25392,
                  27090,
                  33717,
                  39374,
                  21564,
                  21850,
                  25304,
                  25306,
                  25345,
                  25307,
                  25309,
                  25311,
                  28610,
                  25314,
                  25315,
                  25316,
                  25290,
                  25291,
                  25292,
                  25357,
                  25361,
                  25297,
                  25298,
                  25299,
                  25286,
                  25289,
                  25288,
                  25300,
                  21302,
                  25302,
                  25294,
                  25295,
                  25296,
                  27683,
                  28609,
                  28612,
                  29228,
                  31709,
                  31018,
                  31016,
                  21849,
                  23028,
                  21562);

**Comment by ZhengPeiRu21** [comment]
Thank you for the very great report! I had remove some of these but had not yet spend time to do a thorough check for all. This is fixed in https://github.com/ZhengPeiRu21/mod-individual-progression/commit/876048b59d2b5138d8428283f87cf70c8e94db4f.
