### ISSUE TITLE
Onyxia lvl60 raid problem

### ISSUE THREAD

**Issue by blazersrng** [ZhengPeiRu21/mod-individual-progression#40]
Onyxian Whelps that spawn during phase 2 and from eggs are level 80 and it makes encounter impossible.

**Comment by blazersrng** [comment]
Hey, another issue is that Onyxia 60 is not skinnable, so players are unable to get materials for Onyxian Scale Cloak which is needed in BWL.

**Comment by ZhengPeiRu21** [comment]
> Hey, another issue is that Onyxia 60 is not skinnable, so players are unable to get materials for Onyxia Scale Cloak which is needed in BWL.

Thank you for finding this, I'll fix this at the same time. I hope to fix these both today - thanks for your patience!

**Comment by ZhengPeiRu21** [comment]
This should now be fixed in https://github.com/ZhengPeiRu21/mod-individual-progression/commit/923cb266d02ef83c568807c87d7c9d660f197aa3 and https://github.com/ZhengPeiRu21/mod-individual-progression/commit/f8eb0654b509bd41a22298f7ddb8f9b714d86fa1. Please let me know if you see any more issues!

**Comment by blazersrng** [comment]
Thank you for the module. We are progressing through BWL right now and will report if we find any issues.
