### ISSUE TITLE
Unknown Spell - Individual Progression+NPCBots

### ISSUE THREAD

**Issue by Badgermilk0** [ZhengPeiRu21/mod-individual-progression#401]
I'm getting this when compiling with these mods.

Any clues on how I can solve it?
![image](https://github.com/user-attachments/assets/3478b045-8131-4fa4-a3b1-c0455dcd6a1b)

**Comment by StraysFromPath** [comment]
The error is harmless. Just ignore. They will also proc errors for windfury sometimes too.

**Comment by Badgermilk0** [comment]
Ah ok, thank you!
