### ISSUE TITLE
Compilation error

### ISSUE THREAD

**Issue by gutoukuaiken** [ZhengPeiRu21/mod-individual-progression#407]
Azerothcore Commits: 0b6aebaf0a2adba261e366bd6abd6c371bc2714b
individual-progression Commits: 28319a16f6d1eddfa31551249b62f71dc48923e9
A compilation error occurred: Error C2065 "sSpellMgr" : Undeclared identifier modules C:\develop\azerothcore\modules\mod-individual-progression\src\vanillaScripts\boss_lord_kazzak.cpp 214

**Comment by Grimfeather** [comment]
can be fixed by adding
#include "SpellMgr.h"

at the top of the boss_lord_kazzak.cpp file.
I'll make a PR

**Comment by ZhengPeiRu21** [comment]
This should now be resolved. Thanks for reporting the issue!
