### ISSUE TITLE
with the current latest azerothcore update, the module causes a build error/failure in visual studio due to Onyxia (i have snippets of the log)

### ISSUE THREAD

**Issue by ExLuck6** [ZhengPeiRu21/mod-individual-progression#41]
here is the log snippets

22>C:\AzerothCore\modules\mod-individual-progression\src\vanillaScripts\boss_onyxia.cpp(344,1): error C2660: 'ScriptedAI::DoResetThreat': function does not take 0 arguments
22>C:\AzerothCore\src\server\game\AI\ScriptedAI\ScriptedCreature.h(314,10): message : see declaration of 'ScriptedAI::DoResetThreat' (compiling source file C:\AzerothCore\modules\mod-individual-progression\src\vanillaScripts\boss_onyxia.cpp)
22>C:\AzerothCore\modules\mod-individual-progression\src\vanillaScripts\boss_onyxia.cpp(394,1): error C2660: 'ScriptedAI::DoResetThreat': function does not take 0 arguments
22>C:\AzerothCore\src\server\game\AI\ScriptedAI\ScriptedCreature.h(314,10): message : see declaration of 'ScriptedAI::DoResetThreat' (compiling source file C:\AzerothCore\modules\mod-individual-progression\src\vanillaScripts\boss_onyxia.cpp)

Done building project "modules.vcxproj" -- FAILED.

25>LINK : fatal error LNK1181: cannot open input file '..\..\..\modules\RelWithDebInfo\modules.lib'
25>Done building project "worldserver.vcxproj" -- FAILED

========== Rebuild All: 24 succeeded, 2 failed, 0 skipped ==========

**Comment by ZhengPeiRu21** [comment]
Thank you for the report. This should now be fixed as of https://github.com/ZhengPeiRu21/mod-individual-progression/commit/2e55d02a794205a956e34023448de67e3868b2b8.

**Comment by ExLuck6** [comment]
awesome! thank you so much for fixing it <3
