### ISSUE TITLE
Error message when combined with Playerbots - Item (Entry: xxxx has wrong class value....)

### ISSUE THREAD

**Issue by Badgermilk0** [ZhengPeiRu21/mod-individual-progression#411]
When compiled together with the Playerbots Mod the following errors are produced in the cli:

Will this be a long term issue on the server or can it be disregarded (or fixed)?
![image](https://github.com/user-attachments/assets/75fa4d30-b821-440f-a392-7916040b0fd1)

**Comment by Grimfeather** [comment]
I actually had the same question a while ago.
https://github.com/ZhengPeiRu21/mod-individual-progression/issues/163

Could you check worldserver.conf for:
DBC.EnforceItemAttributes = 0

If this is set to 1, change it to 0.

**Comment by Badgermilk0** [comment]
Argh!
You were correct in your assumptions and it was fixed by setting it to the correct value!

Thank you!
