### ISSUE TITLE
dungeon_onyxia.sql duplicate entry error

### ISSUE THREAD

**Issue by diederikdegraaf** [ZhengPeiRu21/mod-individual-progression#42]
ERROR 1062 (23000) at line 1022 in file: '/azerothcore/data/sql/custom/db_world/dungeon_onyxia.sql': Duplicate entry '2848' for key 'areatrigger_scripts.PRIMARY'

I think the below line is missing a DELETE FROM before it. Got this error after applying the new version of dungeon_onyxia.sql.

https://github.com/ZhengPeiRu21/mod-individual-progression/blob/f8eb0654b509bd41a22298f7ddb8f9b714d86fa1/sql/world/base/dungeon_onyxia.sql#L1022

**Comment by ZhengPeiRu21** [comment]
Thank you for reporting this issue! This should be fixed in https://github.com/ZhengPeiRu21/mod-individual-progression/commit/036cb7a34983d4a761ab12dce0c835fa2f144402.
