### ISSUE TITLE
Attacked by invisible creatures hidden by IndividualProgressionAwarenessScripts.cpp

### ISSUE THREAD

**Issue by acore-crap** [ZhengPeiRu21/mod-individual-progression#421]
To observe:

.gm off
.individual set 8
.go xyz -3025.2693 1747.8899 75.2492 530

Get attacked by invisible Coilskar Siren since progression is below PROGRESSION_TBC_TIER_3.

I'm not sure of a good way to address this issue.  I tried a few things in the npc_ipp_tbc_t4AI script: set evade state, me->CombatStop, but I couldn't find a good way to keep the creature in a state that both:
  - completely ignores the player under the progression tier (the options I tried keep the player in combat)
  - allows players at or above the progression tier to attack the mob (I'm sure I'm not understanding something about how UNIT_STATE_EVADE works)

The solution I ended up implementing for myself is just having the invisible creature kill itself on JustEngagedWith() if the target player's progression tier hasn't passed PROGRESSION_TBC_TIER_3, but there has to be a better way to go about this.  I'm just not sure what it is.

**Comment by Grimfeather** [comment]
ok, can confirm this.
do you know why they are phased? is it because of the jewelcrafting pattern drop?

I could make a copy of these creatures and remove this item from their drop table.
the copy will then be swapped for the original at PROGRESSION_TBC_TIER_4

**Comment by acore-crap** [comment]
Yeah, according to the attached comment in ipp_aware_npcs.sql:

```
-- Drop source for 2.3 Jewelcrafting Recipe
UPDATE `creature_template` SET `ScriptName` = 'npc_ipp_tbc_t4' WHERE `entry` IN (19768, 19227, 23761);
```

**Comment by Grimfeather** [comment]
I was thinking, what if we made a new skill. a skill called Progression.
Every time a player goes up a progression stage we also increase that player's progression skill.
This way we could add a RequiredSkill together with a RequiredSkillRank to an item in item_template. 
If you haven't progressed far enough you would not be able to use the item.

**Comment by acore-crap** [comment]
Another theoretical possibility would be through a hidden aura that makes these creatures visible, similar to how https://www.wowhead.com/wotlk/item=32446/elixir-of-shadows makes https://www.wowhead.com/wotlk/npc=21651/time-lost-skettis-reaver and company visible, but I'm not sure how much of this is handled client-side.

One instance of this behavior that I dug into, not being able to mine https://www.wowhead.com/wotlk/object=185877/nethercite-deposit without https://www.wowhead.com/wotlk/spell=40216/dragonmaw-illusion , seems to be entirely client-side as far as I can tell.

I'm not familiar enough with the project yet, there's so much to figure out.

**Comment by Grimfeather** [comment]
I don't want the creature to be hidden. That's replacing one issue with another. The creature should be there before TBC tier 4.
