### ISSUE TITLE
Skinning requirement for vanilla phases

### ISSUE THREAD

**Issue by Badgermilk0** [ZhengPeiRu21/mod-individual-progression#422]
Currently it is impossible to skin lv 60+ mobs during any of the Vanilla phases.

Ex.
Immul'thar lv61 requires 305 skinning skill - I believe everything in Vanilla content should be skinnable with skill 300.

**Comment by psajdak45** [comment]
I believe you needed 315 skinning for onyxia in vanilla. The beast from UBRS drops dagger with +10 skinning nad  i think you have to enchant gloves +5 skinning. Hope this helps.

**Comment by Badgermilk0** [comment]
@psajdak45  - does that mean that this is not an issue and it is infact vanilla like? :)

**Comment by Grimfeather** [comment]
> @psajdak45 - does that mean that this is not an issue and it is infact vanilla like? :)

yes, this is how it was in vanilla. you need the dagger and gloves enchant.

**Comment by Badgermilk0** [comment]
Thank you for the responses - closing!
