### ISSUE TITLE
[Feature Request] Starting Zone Chooser

### ISSUE THREAD

**Issue by StraysFromPath** [ZhengPeiRu21/mod-individual-progression#44]
It's nice to lvl in a different starting zone, GMs can do .tele, but players must suffer. 

Can we have an optional config to choose our own starting zone? You could attach it to the same menu as the challenge mode object gossip so that only lvl 1 characters can use the service.

**Comment by ZhengPeiRu21** [comment]
This is a good idea, but I think it might be better as its own module. If I am soon able to find some free time, I can create this - it should be quite fast to make. I'll post the link to the repo here when it is complete, but I will close this for now as this is not an issue for the Individual Progression module.
