### ISSUE TITLE
Northspear and Bravery overlap

### ISSUE THREAD

**Issue by Tbales1025** [ZhengPeiRu21/mod-individual-progression#46]
When you activate the vanilla transports, the bravery and the northspear in Menethil Harbor will appear at the same time sometimes and overlap each other.

**Comment by ZhengPeiRu21** [comment]
Thank you for reporting this. I am aware of this issue, but unfortunately resolving this would require extensive and messy client DBC patching, so I've found it is best for gameplay to leave it as this way, even though it sometimes is having some messy visual. If anyone is able to think of a better solution, please let me know.

**Comment by Tbales1025** [comment]
The only thing I could think of, if this is even possible, is to have the boat to NR essentially be turned off until you can access it when Sunwell is completed. Then the boat from Teldrassil reverts to Stormwind as it is on live.
