### ISSUE TITLE
[Fatal] Wrong Thrall in Orgrimmar for Death Knight Progression

### ISSUE THREAD

**Issue by StraysFromPath** [ZhengPeiRu21/mod-individual-progression#47]
You cannot progress as DK during quest Warchief's Blessing as Thrall is not the Thrall you hand the quest into.

I guess this is the same issue for Alliance version of same quest.

![image](https://user-images.githubusercontent.com/119371540/205734122-6d09ceba-4faf-4d06-90dd-f2393c204b7b.png)

**Comment by StraysFromPath** [comment]
More info: It is the correct thrall but he is the wrong faction.

.npc set faction temp 35

Fixed the bug temporarily (making Thrall join a faction that is friendly to all)

**Comment by ZhengPeiRu21** [comment]
Thank you for the report.

**Comment by ZhengPeiRu21** [comment]
This should now be fixed in https://github.com/ZhengPeiRu21/mod-individual-progression/commit/d9f6325c725443135e8f03d33c3aa9ae8f87c6ec. Please let me know if you find any more issues!
