### ISSUE TITLE
Items missing stats

### ISSUE THREAD

**Issue by ajgration** [ZhengPeiRu21/mod-individual-progression#48]
Here's a couple more items I've noticed with wrong stats. I'll add to this issue as I find more

Coppercloth Gloves https://classicdb.ch/?item=4767 - currently no stats, missing +3 strength 
Gemmed Copper Gauntlets https://classicdb.ch/?item=3474 - currently no stats, missing random bonuses ie. "of the bear/eagle"

**Comment by ZhengPeiRu21** [comment]
Thank you very much for reporting the issue. I will look into these items! Please let me know if you find any more.

**Comment by ZhengPeiRu21** [comment]
These issues should be fixed in https://github.com/ZhengPeiRu21/mod-individual-progression/commit/57ea9222800e3155c985a1ac5bcfa904db5eab8b and https://github.com/ZhengPeiRu21/mod-individual-progression/commit/1f701a3307a58a1a5dad8733468680a044ba3304.
