### ISSUE TITLE
Unable to complete "Bang a gong"

### ISSUE THREAD

**Issue by Grakazela** [ZhengPeiRu21/mod-individual-progression#5]
https://classic.wowhead.com/quest=8743/bang-a-gong is unable to be accepted, also the gong in silithis for this quest is showing in game as gameobject 180718(listed as type 5-GAMEOBJECT_TYPE_GENERIC in gameobject_template), when wowhead stats the gong for the quest is 180717(listed as type 10-GAMEOBJECT_TYPE_GOOBERin gameobject_template).

spawned both, added both to gameobject_queststarter, set data1 for 180717 to the correct quest id, no changes the quest is still unable to be picked up or completed even with the mallet in the inventory

**Comment by ZhengPeiRu21** [comment]
Thank you for the report. I will investigate!

**Comment by Grakazela** [comment]
used gm command .quest add 8743, unable to cash in to either gong model

**Comment by Grakazela** [comment]
just gonna add another note, reading the src it looks like PROGRESSION_PRE_AQ should be triggered by the completion of "might of kalimdor" but i am unable to enter the raids, either by flying over the still sealed door and walking into the portals or using .teleport aq20/40

**Comment by Grakazela** [comment]
k managed to fix the gong itself: set 180718 or 180717 and replaced the gobject ingame, set it to type 2, replace data2 with the quest id, set quest starter and ender tables to also point to the quests and gobject.
however the completion of might of kalimdor or the gong quest doesn't seem to update the character settings table and allow me into the raid

**Comment by ZhengPeiRu21** [comment]
It seems this is do to an AzerothCore bug. The hook is not implement properly. I will submit a PR upstream to fix.

**Comment by ZhengPeiRu21** [comment]
I have submit a PR to AzerothCore upstream to fix the originally not working hook. On the other hand, here I was able to switch to a different hook that is working and is have the same effect, so Might of Kalimdor quest check is fixed in https://github.com/ZhengPeiRu21/mod-individual-progression/commit/4670a663828ca2672ec9ab0e04610a0360c4099a.
I will still need to fix the Bang a Gong not opening the door.

**Comment by ZhengPeiRu21** [comment]
Fixed in https://github.com/ZhengPeiRu21/mod-individual-progression/commit/93fe2eebddb1be24dd5fc2af20a646203230f721.
