### ISSUE TITLE
[Bug] Boat to Azuremyst from Darkshore does not work

### ISSUE THREAD

**Issue by StraysFromPath** [ZhengPeiRu21/mod-individual-progression#50]
![image](https://user-images.githubusercontent.com/119371540/206863592-d611a599-292b-4cbf-8410-2527cfb1de56.png)

 you just get stuck here forever. azuremyst only place to learn jewelcrafting + has low lvl quests/items for draenei to return to.

i assume this means the zeppling to everson might also be broke

**Comment by ZhengPeiRu21** [comment]
I am not able to reproduce the issue; it is working for me. This transport is not edited by the module. Are you sure you are on the right boat?

**Comment by StraysFromPath** [comment]
> 

I tried to reproduce but it was working this time.

I am using your repacked individual progression released 28/11 so will keep giving any reports/notes of what I find.
