### ISSUE TITLE
spell_resotrations.sql

### ISSUE THREAD

**Issue by mtompkins** [ZhengPeiRu21/mod-individual-progression#51]
Not knowing the logic but having hit an error on this sql script, it looks like you need to delete `1787` 
You have `1786` listed twice.

https://github.com/ZhengPeiRu21/mod-individual-progression/blob/master/sql/world/base/spell_restorations.sql

**Comment by ZhengPeiRu21** [comment]
Thank you for finding this typo! I appreciate the report. This is fixed in https://github.com/ZhengPeiRu21/mod-individual-progression/commit/f42cb0f86720865f8f01ef8a949fcbf5e8cef81c.
