### ISSUE TITLE
"Luck Be With You" Winterspring quest number of items to gather not aligned with quest description

### ISSUE THREAD

**Issue by justurn** [ZhengPeiRu21/mod-individual-progression#53]
![image](https://user-images.githubusercontent.com/5217306/207317224-d65780c6-486e-4e12-8b59-494a4c0e0f99.png)

**Comment by ZhengPeiRu21** [comment]
Thank you for the report. This is fixed in https://github.com/ZhengPeiRu21/mod-individual-progression/commit/1382244bb03d2ede9d099b08962cef4d48f42c82.
