### ISSUE TITLE
Small Faction Issue Torek and Splintertree Raiders Friendly to Alliance

### ISSUE THREAD

**Issue by StraysFromPath** [ZhengPeiRu21/mod-individual-progression#56]
![image](https://user-images.githubusercontent.com/119371540/207710669-e648cf70-3806-4b27-9f27-ef5a2636ef46.png)

https://www.wowhead.com/classic/npc=12858/torek

should be assigned a horde faction hostile to alliance

**Comment by ZhengPeiRu21** [comment]
Thank you for the report.

**Comment by ZhengPeiRu21** [comment]
Fixed in https://github.com/ZhengPeiRu21/mod-individual-progression/commit/34c7f78d08e8b25c258e6fe60b8133e041c28e11.
