### ISSUE TITLE
[AC Issue] Enemies in Water are not behaving well

### ISSUE THREAD

**Issue by StraysFromPath** [ZhengPeiRu21/mod-individual-progression#58]
If an enemy is in water and you are not in water it will enter "evade" mode and ignore all attacks.

Intended behaviour - the enemy leaves the water and attacks you.

The opposite is also true (you in water, enemy not in water).

This causes so many issues in Darkshore with Murlocs, Lakeshire with Murlocs, and Bloodmyst with Murlocs. As murlocs are a common water enemy it is frustrating to play.

This issue probably AC based as well outside scope of this module.

![image](https://user-images.githubusercontent.com/119371540/207881278-819d4e3b-b4e7-4c1c-b115-269445995835.png)

**Comment by bkmangx1** [comment]
You are right, this doesn't really have anything to do with the module. There is a PR waiting to be merged that should improve this behavior. You can follow it here https://github.com/azerothcore/azerothcore-wotlk/pull/13705
