### ISSUE TITLE
[Updater Issue] Overwriting data that is not needed.

### ISSUE THREAD

**Issue by StraysFromPath** [ZhengPeiRu21/mod-individual-progression#59]
I understand it is easiest for the updater to overwrite everything but this leads to unfortunate circumstances.

For example, I had custom edits made to tables like PlayerXptoLevel, PlayerClassLevelStats, etc which enabled levelling up to 85 with generated stats/abilities/etc. 

I also had custom items, quests, npcs, etc created in the database.

All of this got wiped by the update but the update did not change any of these tables.

If possible can you please consider changing the updater to only edit/overwrite tables you have made changes to?

**Comment by ZhengPeiRu21** [comment]
I am sorry you lost your custom changes. Every update is a freshly generated world database from AC master with all module changes applied - there is not a convenient way to apply individual updates. I would recommend saving your custom changes as a SQL file, which you can re-apply after updating. The other option is to not use the full update, and to instead manually re-run all Individual Progression SQL files that have changes and AzerothCore updates from the core repo. Please let me know if you have any other questions!
