### ISSUE TITLE
[Enhancement] PvP Items Requiring Reputation Again

### ISSUE THREAD

**Issue by StraysFromPath** [ZhengPeiRu21/mod-individual-progression#60]
The second you hit 60 you can buy a full set of high ilvl epic weapons and armour from pvp merchants thus skipping huge amounts of normal progression.

These should be locked behind reputation scores as they were in vanilla so you have to grind to get them the same way you would any other set.

https://www.wowhead.com/classic/guide/alterac-valley-rewards-pvp-classic-wow

https://wowpedia.fandom.com/wiki/Classic_reputation_rewards

**Comment by ZhengPeiRu21** [comment]
Thank you for the suggestion, this is related to https://github.com/ZhengPeiRu21/mod-individual-progression/issues/24

**Comment by StraysFromPath** [comment]
> Thank you for the suggestion, this is related to #24

These links might help anyone researching which items required which reputation values. You can hover the item names in the tables to preview the ID in the URL.

https://www.wowhead.com/classic/guide/frostwolf-clan-alterac-valley-reputation

https://www.wowhead.com/classic/guide/silverwing-sentinels-warsong-gulch-reputation-wow-classic

https://www.wowhead.com/classic/guide/warsong-outriders-warsong-gulch-reputation-wow-classic

https://classic.wowhead.com/guides/stormpike-guard-alterac-valley-reputation

https://www.wowhead.com/classic/guide/league-of-arathor-arathi-basin-reputation-wow-classic

https://www.wowhead.com/classic/guide/defilers-arathi-basin-reputation-wow-classic

**Comment by ZhengPeiRu21** [comment]
Implemented in https://github.com/ZhengPeiRu21/mod-individual-progression/commit/97b94bdcb20f2c692da372be682d2fbe388a8cd3.
