### ISSUE TITLE
Mount tab for Vanilla mounts

### ISSUE THREAD

**Issue by justurn** [ZhengPeiRu21/mod-individual-progression#63]
I noticed that vanilla mounts are modified in the SQL mounts_and_riding.SQL 
It is not so clear how those changes have disabled the mounts tab that is present on WOTLK content?
Maybe the spell_ID?

Is there a way to keep the level and price changes for vanilla, but also maintain access to the mounts tab?
I'd prefer to not have bags slots occupied by mounts, if possible.

Thanks :)

**Comment by StraysFromPath** [comment]
As a workaround you can do ".learn X" where X is the ID of the mount spell. 

To find the spell use ".look sp X" where X is the name of the mount.

For example, 8394 is the Striped Frostsaber for Night Elves.

Then you can delete the whistle from your inventory after buying it.

https://wotlkdb.com/?spell=8394

**Comment by justurn** [comment]
Thanks, would that add the mount to the tab though or just add it to your spell book?
I noticed all of the blood elf mounts are going directly into the mount tab.

Maybe this is just an issue with vanilla mounts?

**Comment by justurn** [comment]
I found removing the changes to mounts in the mounts and riding tab solved this issue, perhaps these should be split into two SQL files. Making the mounts portion optional?

**Comment by ZhengPeiRu21** [comment]
Thank you for the report - this is not intentional as using the mount tab is a QoL that I hoped to preserve. I will tag this as a bug and fix the SQL so the mounts are added to the tab properly.

**Comment by ZhengPeiRu21** [comment]
This should now be fixed in https://github.com/ZhengPeiRu21/mod-individual-progression/commit/94d4eda797beb4311c7bc6e3afc73112506d3c99. If anyone is prefer the old behavior of requiring mount items in the bag for use, please feel free to retrieve the old version of the file from Git history.
