### ISSUE TITLE
Rogue Poisons

### ISSUE THREAD

**Issue by Purple-23** [ZhengPeiRu21/mod-individual-progression#66]
When you enable the poisons to be returned, do the quest, the only poison you get access to is the original instant.  Everything works fine with learning it, using it, creating it, etc., but that is the only poison you will ever get.  Trainers do not teach others.  Leveling the skill to current max at level 24 still resulted in no new poisons.

**Comment by Purple-23** [comment]
I have tried re-running the SQL commands that bring the poisons back, recompiling and nothing.

**Comment by Purple-23** [comment]
UPDATE:  it appears not all the rogue trainers train poisons.  Most of the horde trainers work, but none of the trainers in Stormwind do.  I added npc 26329 and he trains the missing poisons.

**Comment by ZhengPeiRu21** [comment]
Thank you for the report. I will investigate adding poisons to the missing trainers.

**Comment by ZhengPeiRu21** [comment]
This should now be fixed in https://github.com/ZhengPeiRu21/mod-individual-progression/commit/fd075d686eaea146bfee93728fc4b816cc6f0a62. Please let me know if you find any more cases of missing skills. Thanks!
