### ISSUE TITLE
[Item] Seal of the Dawn not giving scourgestone drops

### ISSUE THREAD

**Issue by justurn** [ZhengPeiRu21/mod-individual-progression#67]
When using seal of the dawn trinket (13209) I am not receiveing scourgestone drops from undead.
Spell ID 17670 is applied to Argent Dawn Commission trinket (12846) but not on Seal of the Dawn in my DB.

I believe this is a change in the mod, in item_changes.sql line 9023, the spell ID and trigger is updated from the second spell slot for Seal of the Dawn. Making it 0.

Restoring spell ID 17670 to Seal of the Dawn in the second spell slot, allows for scourgestones to drop again correctly.

**Comment by ZhengPeiRu21** [comment]
Thank you for reporting the issue! Fixed in https://github.com/ZhengPeiRu21/mod-individual-progression/commit/debcc67e1877e37277f1d4219e73a78cde6b0832.
