### ISSUE TITLE
Old World Elites?

### ISSUE THREAD

**Issue by Kuiriel** [ZhengPeiRu21/mod-individual-progression#72]
I am running the preview build but Sarkoth in Orc starting area is not an elite as he used to be. I was under the impression this restored all the old world elites as well, but now I'm thinking I've confused it for something else?

From https://github.com/ZhengPeiRu21/mod-individual-progression/wiki/List-of-Changes it states:
Restore original mob stats, spells, and Elite status for Vanilla and TBC mobs

**Comment by ZhengPeiRu21** [comment]
All Old World Elites are restored to their original values. Sarkoth is not NPC even in Vanilla, according to other databases and WoWHead: https://www.wowhead.com/classic/npc=3281/sarkoth#comments. Do you have a source that he should be elite?

**Comment by Kuiriel** [comment]
Just my inaccurate memory, it would seem! I don't know why I remember all the dead bodies and a struggle to kill him, I must have just been terrible at rotations back then. Sorry, I should have double checked the history properly myself first.

**Comment by ZhengPeiRu21** [comment]
> Just my inaccurate memory, it would seem! I don't know why I remember all the dead bodies and a struggle to kill him, I must have just been terrible at rotations back then. Sorry, I should have double checked the history properly myself first, someone even listed his stats from back then so I could have just checked the SQL myself

No problem, thank you for reporting an issue! Please let me know if you find anything else that seems to be inaccurate and I will check that it is correct.
