### ISSUE TITLE
[Item] Libram of Fervor - Obsolete spell

### ISSUE THREAD

**Issue by justurn** [ZhengPeiRu21/mod-individual-progression#74]
Libram of Fervor (23203) has an obsolete spell applied to it, where the bonus applies to spells that no longer exist in 3.3.5
Update the spell ID to provide the newer bonus that can apply to spells which at least exist in the game.

The new spell ID for this item should be 60804

**Comment by ZhengPeiRu21** [comment]
Thanks, this is a very helpful report. I will make the correction.

**Comment by ZhengPeiRu21** [comment]
This has been changed in https://github.com/ZhengPeiRu21/mod-individual-progression/commit/77bacf6347fe10345cf31d00e4339411facc1731.
