### ISSUE TITLE
player_levelstats.sql needs updating following new AC changes

### ISSUE THREAD

**Issue by zhbur** [ZhengPeiRu21/mod-individual-progression#77]
player_levelstats.sql fails to apply because of the new changes to AC https://github.com/azerothcore/azerothcore-wotlk/pull/14383

```
>> Applying update "player_levelstats.sql" 'D275039'...
ERROR 1146 (42S02) at line 2 in file: 'C:\Games\Azerothcore\data\sql\custom\db_world\player_levelstats.sql': Table 'acore_world.player_levelstats' doesn't exist♪◙
```

Individual Progression's stat changes will need to be rewritten to fit the new AC tables `player_classstats` and `player_racestats`

**Comment by ZhengPeiRu21** [comment]
Thanks for the report, I'll get this fixed today.

**Comment by ZhengPeiRu21** [comment]
This should now be fixed in the latest update. Please let me know if you continue to see issues.
