### ISSUE TITLE
[Challenge Mode] Talent points reset on login.

### ISSUE THREAD

**Issue by StraysFromPath** [ZhengPeiRu21/mod-individual-progression#78]
When using Config

Hardcore.TalentRewards = "10 1, 11 1, 12 1, 13 1, 14 1, 15 1, 16 1, 17 1, 18 1, 19 1, 20 1, 21 1, 22 1, 23 1, 24 1, 25 1, 26 1, 27 1, 28 1, 29 1, 30 1, 31 1, 32 1, 33 1, 34 1, 35 1, 36 1, 37 1, 38 1, 39 1, 40 1, 41 1, 42 1, 43 1, 44 1, 45 1, 46 1, 47 1, 48 1, 49 1, 50 1, 51 1, 52 1, 53 1, 54 1, 55 1, 56 1, 57 1, 58 1, 59 1, 60 1, 61 1, 62 1, 63 1, 64 1, 65 1, 66 1, 67 1, 68 1, 69 1, 70 1, 71 1, 72 1, 73 1, 74 1, 75 1, 76 1, 77 1, 78 1, 79 1, 80 1"

The talent points are gained on level up, but reset to 0 on login/logout. All talents are unlearned as well.

**Comment by StraysFromPath** [comment]
A possible workaround/fix could be to change the Challenges to utilise the "Rate.TalentPoints" config value but for the individual character instead of granting extra talent points using the command which resets itself.

**Comment by ZhengPeiRu21** [comment]
Please see the related issue on the Challenge Modes module: https://github.com/ZhengPeiRu21/mod-challenge-modes/issues/12. There is an AC bug that causes the talent points to be reset; I have submitted an outstanding PR that will resolve the problem once merged.
