### ISSUE TITLE
[Quest] Wolves Across the Border Missing Drop Table

### ISSUE THREAD

**Issue by XSNomad** [ZhengPeiRu21/mod-individual-progression#8]
**Current Behavior**
Creature does not drop quest item.
Young Wolf - 299
Tough Wolf Meat - 750

Quest ID - 33

**Expected Blizzlike Behavior**
Creature Drops Quest Item

**Source**
https://classic.wowhead.com/item=750/tough-wolf-meat#dropped-by;0-1-10-9

**Steps to reproduce the problem**

1. Start a Human Character:
2. Pick up Quest Wolves Across the Border (Quest from Eagan Peltskinner He is outside Northshire Abbey on left side.)
3. BUG: Young wolf do not drop quest related item (Tough wolf meat)

**Extra Notes**
While this is a very small bug, it is the first interaction many players will have with the server. The concept that one of the first quests in the game is broken will speak incorrectly that most of the quests are broken.

**AC rev. hash/commit**
AC> server debug
AC> AzerothCore rev. https://github.com/azerothcore/azerothcore-wotlk/commit/89251253506d3d1a6baabdf4b40306941789774b 2022-08-25 17:30:24 -0300 (master branch) (Unix, RelWithDebInfo, Static)
Using SSL version: OpenSSL 1.1.1f 31 Mar 2020 (library: OpenSSL 1.1.1f 31 Mar 2020)
Using Boost version: 1.71.0
Using MySQL version: 80030
Using CMake version: 3.16.3
Compiled on: Linux 5.4.0-125-generic
Worldserver listening connections on port 8085
Realmlist (Realm Id: 1) configured in port 8085
VMAPs status: Enabled. LineOfSight: 1, getHeight: 1, indoorCheck: 1
MMAPs status: Enabled
maps directory located in ./maps. Total size: 291014951 bytes
vmaps directory located in ./vmaps. Total size: 658130721 bytes
mmaps directory located in ./mmaps. Total size: 2320900676 bytes
Using enUS DBC Locale as default. All available DBC locales: enUS
Using World DB: ACDB 335.8-dev
LoginDatabase queue size: 0
CharacterDatabase queue size: 0
WorldDatabase queue size: 0

**List enable modules:**

mod-ah-bot
mod-autobalance
mod-individual-progression

**Operating system**
Linux wow-ac 5.4.0-125-generic https://github.com/azerothcore/azerothcore-wotlk/pull/141-Ubuntu SMP Wed Aug 10 13:42:03 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

![image](https://user-images.githubusercontent.com/60951221/187598039-e2bcac4d-6f36-4994-8d3d-d6a101ca5829.png)
![image](https://user-images.githubusercontent.com/60951221/187598362-16af2318-f61c-494a-b6d5-5502d83161d6.png)

**Comment by XSNomad** [comment]
DELETE FROM `creature_questitem` WHERE (`CreatureEntry` = 299);
INSERT INTO `creature_questitem` (`CreatureEntry`, `Idx`, `ItemId`, `VerifiedBuild`) VALUES
(299, 0, 750, 0);

**Comment by XSNomad** [comment]
DELETE FROM `creature_loot_template` WHERE (`Entry` = 299);
INSERT INTO `creature_loot_template` (`Entry`, `Item`, `Reference`, `Chance`, `QuestRequired`, `LootMode`, `GroupId`, `MinCount`, `MaxCount`, `Comment`) VALUES
(299, 0, 11111, 0.2, 0, 1, 0, 1, 1, 'Diseased Timber Wolf - (Small Pouch ReferenceTable)'),
(299, 0, 20000, 20, 0, 1, 0, 1, 1, 'Diseased Timber Wolf - (Grey 1-5 EXP 0 ReferenceTable)'),
(299, 0, 20002, 100, 0, 1, 0, 1, 1, 'Diseased Timber Wolf - (Beast 1-5 EXP 0 ReferenceTable)'),
(299, 0, 20002, 30, 0, 1, 1, 1, 1, 'Diseased Timber Wolf - (Beast 1-5 EXP 0 ReferenceTable)'),
(299, 750, 0, 90, 1, 1, 0, 1, 1, 'Diseased Timber Wolf - Diseased Wolf Pelt');

**Comment by ZhengPeiRu21** [comment]
Thank you for the report! I have applied your fix. Fixed by https://github.com/ZhengPeiRu21/mod-individual-progression/commit/83e6a8d289a6aa5a16831f4e1cff3464fc43dae4.
