### ISSUE TITLE
How to correctly shutdown without losing characters

### ISSUE THREAD

**Issue by Kuiriel** [ZhengPeiRu21/mod-individual-progression#80]
EDIT: It must have been caused be something entirely separate. Somehow we have lost multiple game days of progress. I had a boot up failure after installing the latest ASUS chipset drivers, and I think Windows ran a system restore. That must have somehow affected the SQL Database where characters were stored, which seems incredibly bizarre to me.

I will just make an effort to back up the database regularly instead.

It's weird though. Is there a reason why the database would be affected by System Restore points?

I had about 4 restore points I could browse through with 'scan affected programs' and none of them mention SQL or WoW. They mention Visual C++ 2015-2019 Redistributable a few times but that can't be relevant. On trying to load the oldest restore points it states "System restore cannot be undone ... from the System Recovery Options menu". So, given that's where it probably did it from, that must be why I can't see a point that mentions SQL having been affected.

Ah well. My basic question still stands: Is there a 'correct' process for terminating the server?

ORIGINAL: 

I'm sorry for asking such a stupid question.

I've been paranoid and typing saveall on a regular basis. I type server shutdown 1. I then close the window that has an AC> console prompt (I think it auto closes, I forget). I think I then close the SQL and then the final blue window with the authserver, with CTRL+C.

However I didn't seem to do that the last few times, and we've lost a day - no, wait, several days of of gameplay. We played through it on subsequent days... not sure how I lost the data. Maybe I just hit ctrl+C or I shut my computer down directly? Had COVID and couldn't think straight back then, but brain is decent now and I'm puzzled as to how I borked it.

I thought character information would be saved during the game. I didn't realize I needed to hit save all at the end. However I can see from several crash dump files that I must have been closing it wrong because several of these closes are crash dumps.

Do I need to enable some sort of autosave?

Or is what I'm describing indicative of some other Windows 11 SQL bug?

Thank you for your patience.

**Comment by bkmangx1** [comment]
>Ah well. My basic question still stands: Is there a 'correct' process for terminating the server?

Your process is almost correct, database should be the last thing to close.

>It's weird though. Is there a reason why the database would be affected by System Restore points?

It's not clear why system restore is monitoring innodb file extension. This was discussed by developers and the answer is to blame microsoft. I'm not sure if you can recover the lost data, maybe if there is an "Undo" option available? I haven't used system restore for a long time.

You can move database to a non-system partition or drive and disable system restore for it. Database corruption is very rare thing, but backing up regularly is a good idea in general.

**Comment by Kuiriel** [comment]
Thank you. I will tell my grumpy wife it's all Microsoft's fault then! It looks like there is no undo feature available as it was from a BSOD that Windows ran the startup repair option, at least from my google.

And then I will quietly move this to my non-system partition which isn't affected by system restore, as you recommend. And more frequent backups of the database.

It will be on a 2TB 7200RPM HDD rather than an M2 SSD but I'm guessing with 32GB of RAM it shouldn't matter too much?

...

On another note, I have used the guide [here ](https://www.thewindowsclub.com/where-are-system-restore-points-stored-how-to-view) to vssadmin list shadows and then make a link to the relevant directory in the oldest restore point I had.

I tried copying over the entire old server folder from the system restore copy but had a whole series of SQL related errors flash by, tried copying just the database and mysql folder to an existing (after backing up) server folder, but same series of SQL errors.  So I ended up copying just the IDB files across since they were apparently the only ones with data - the others were all blank. At this point the server got up and running but looks like the damage had been done before that restore point - per the whole can't restore from startup repair, mentioned above.

**Comment by ZhengPeiRu21** [comment]
Sorry to hear about this trouble! I hope that you and your wife did not lose too many progress.

Character data should autosave at regular intervals or whenever meaningful events occur such as picking up a high quality item or defeating a boss. You shouldn't have any need to worry about ensuring everything is saved - shutting down the server as you have been doing is the correct way and should ensure that all data is preserved properly.

**Comment by Kuiriel** [comment]
Thank you. Family is loving your work, much appreciated.
