### ISSUE TITLE
Rogue Poisons missing items and spell

### ISSUE THREAD

**Issue by AlvinZhu** [ZhengPeiRu21/mod-individual-progression#84]
items and spell:
Crippling Poison II
Mind-numbing Poison II
Mind-numbing Poison III
which was removed In Wotlk.

I have done the fix. But I don't know how to submit a patch for DBC properly, as the DBC patch is in a zip file and can‘t manage with git properly.

**Comment by ZhengPeiRu21** [comment]
Fixed by https://github.com/ZhengPeiRu21/mod-individual-progression/pull/101. Thanks!
