### ISSUE TITLE
No config option to allow Naxx teleport without Stratholme entrance

### ISSUE THREAD

**Issue by VladonAbaddon** [ZhengPeiRu21/mod-individual-progression#85]
I finished all previous raids, got attuned to Naxx, but the teleport doesn't work. I tried to teleport to Naxx using GM commands, but it seems like Naxx40 bosses are not even present in game, and entrances to Naxx quarters on the necropolis itself are blocked or raid portals are not present, not sure about this. Also couldn't find the teleport script in database. I'm using Preview version.

**Comment by VladonAbaddon** [comment]
Managed to get inside via the Stratholme raid entrance. Is that the supposed behavior?

**Comment by deadcorpseeater** [comment]
> > Managed to get inside via the Stratholme raid entrance. Is that the supposed behavior?
> 
> Yes, this is the intended behavior. Once you have entered once through the original entrance, you can use the teleport crystal outside. This is the pattern what was used for most other Vanilla raids, so I implement it this way. I was intend to add a config option to allow teleport without needing to use the Stratholme entrance, but forgot ^_^;. I will leave this issue open to remember add this config option.

so I can vivsit Naxx 40 only when finish Strat? (entrance at the end of the instance)

**Comment by ZhengPeiRu21** [comment]
> > > Managed to get inside via the Stratholme raid entrance. Is that the supposed behavior?
> > 
> > 
> > Yes, this is the intended behavior. Once you have entered once through the original entrance, you can use the teleport crystal outside. This is the pattern what was used for most other Vanilla raids, so I implement it this way. I was intend to add a config option to allow teleport without needing to use the Stratholme entrance, but forgot ^_^;. I will leave this issue open to remember add this config option.
> 
> so I can vivsit Naxx 40 only when finish Strat? (entrance at the end of the instance)

Yes, that is the default behavior, but as of a new update today, you can disable this requirement by changing IndividualProgression.RequireNaxxStrathEntrance to 0 in the config.

**Comment by ZhengPeiRu21** [comment]
Feature added in https://github.com/ZhengPeiRu21/mod-individual-progression/commit/cb723a31f991c78bf943cb70baa8c342bb59a858.
