### ISSUE TITLE
Worldserver closes

### ISSUE THREAD

**Issue by luperkalel** [ZhengPeiRu21/mod-individual-progression#86]
Hi,
Followed your instructions for a fresh start, but when I try open worldserver.exe to create an account, it appears to run briefly then closes. Just managed to get a screenshot as attached.
![worldserver](https://user-images.githubusercontent.com/124435221/216763249-179a0a51-6201-43c8-bcde-f859b3c9ee40.png)
I'm very limited in coding/programming so not sure where to go from here. Have been trying a few other repacks and even tried my own trinity core but keep getting stuck.

**Comment by ZhengPeiRu21** [comment]
I don't see anything in your screenshot that looks unusual. I'm not sure why it is closing. Could you start the worldserver through a cmd window so the full logs are displayed? You can do this by opening the folder with worldserver.exe in it in Explorer, typing cmd.exe in the Explorer address bar to start a cmd window in that folder, and then running worldserver.exe in the cmd window.

**Comment by ZhengPeiRu21** [comment]
I am going to close this issue. Please feel free to re-open if you need additional help.
