### ISSUE TITLE
[Quest] The Missing Diplomat XP Needs Adjustment. Not adjusted for catchup?

### ISSUE THREAD

**Issue by XSNomad** [ZhengPeiRu21/mod-individual-progression#9]
Current Behavior

![image](https://user-images.githubusercontent.com/60951221/187609605-a031c847-ea8d-4edd-9c52-b1ff09eea909.png)

Quest ID - 1324

Expected Blizzlike Behavior
XP is inline with other changes. 

Source
https://wotlk.evowow.com/?quest=1324

Steps to reproduce the problem
Complete the Missing Diplomat Series. XP is 1000x what it should be. 

AC rev. hash/commit
AC> server debug
AC> AzerothCore rev. https://github.com/azerothcore/azerothcore-wotlk/commit/89251253506d3d1a6baabdf4b40306941789774b 2022-08-25 17:30:24 -0300 (master branch) (Unix, RelWithDebInfo, Static)
Using SSL version: OpenSSL 1.1.1f 31 Mar 2020 (library: OpenSSL 1.1.1f 31 Mar 2020)
Using Boost version: 1.71.0
Using MySQL version: 80030
Using CMake version: 3.16.3
Compiled on: Linux 5.4.0-125-generic
Worldserver listening connections on port 8085
Realmlist (Realm Id: 1) configured in port 8085
VMAPs status: Enabled. LineOfSight: 1, getHeight: 1, indoorCheck: 1
MMAPs status: Enabled
maps directory located in ./maps. Total size: 291014951 bytes
vmaps directory located in ./vmaps. Total size: 658130721 bytes
mmaps directory located in ./mmaps. Total size: 2320900676 bytes
Using enUS DBC Locale as default. All available DBC locales: enUS
Using World DB: ACDB 335.8-dev
LoginDatabase queue size: 0
CharacterDatabase queue size: 0
WorldDatabase queue size: 0

List enable modules:

mod-ah-bot
mod-autobalance
mod-individual-progression

Operating system
Linux wow-ac 5.4.0-125-generic https://github.com/azerothcore/azerothcore-wotlk/pull/141 SMP Wed Aug 10 13:42:03 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

**Comment by ZhengPeiRu21** [comment]
Thank you for the report! It seems there was quite several Vanilla quests with missing or incorrect XP values. I have updated to the latest correct values. Fixed in https://github.com/ZhengPeiRu21/mod-individual-progression/commit/72cbe4fdf9ba9cfb8754e73fb0f9a7ccd523e7ca.
