### ISSUE TITLE
quest of creature Nazgrel (3230) cannot be completed because the NPC was deleted form Hellfire Peninsula

### ISSUE THREAD

**Issue by AlvinZhu** [ZhengPeiRu21/mod-individual-progression#92]
quest of creature Nazgrel (3230) cannot be completed because the NPC was deleted form Hellfire Peninsula.

**Comment by AlvinZhu** [comment]
I know he's in Orgrimmar right now, but there are some Hellfire Peninsula quests that need him.
My current solution is to have this NPC appear in both Salma and Orgrimmar

-- Nazgrel <Advisor to Thrall>
-- DELETE FROM `creature` WHERE `id1`=3230;
INSERT INTO `creature` (`id1`, `map`, `position_x`, `position_y`, `position_z`, `orientation`, `spawntimesecs`) VALUES (3230, 1, 1938.55, -4133.22, 41.1424, 4.07636, 300);

**Comment by ZhengPeiRu21** [comment]
Thank you very much for reporting this issue! Fixed in https://github.com/ZhengPeiRu21/mod-individual-progression/commit/4bc44f230c29b46ea12eadd64c6717e9c5b6cc6c.
