### ISSUE TITLE
Incorrect modelid  these Rider Guards in Outland should not be Silithid

### ISSUE THREAD

**Issue by AlvinZhu** [ZhengPeiRu21/mod-individual-progression#93]
/*  Gryphon Rider Guard  */
-- UPDATE `creature_template` SET `modelid1` = 15337, `minlevel` = 1, `maxlevel` = 1, `speed_run` = 1.14286, `detection_range` = 18.0, `DamageModifier` = 1.0, `HealthModifier` = 65.0 WHERE `entry`=15241;

/*  Bat Rider Guard  */
-- UPDATE `creature_template` SET `modelid1` = 15337, `minlevel` = 1, `maxlevel` = 1, `speed_walk` = 1.0, `speed_run` = 1.14286, `detection_range` = 18.0, `DamageModifier` = 1.0, `HealthModifier` = 65.0 WHERE `entry`=15242;

Incorrect modelid, these Rider Guards in Outland should not be Silithid

**Comment by ZhengPeiRu21** [comment]
Thank you, I appreciate your reports! I will look into these issues and make the necessary corrections.

**Comment by ZhengPeiRu21** [comment]
Fixed in https://github.com/ZhengPeiRu21/mod-individual-progression/commit/f2fc39e10e7ade31e2d9f315097108c7b5b8c002. Thank you again for the report!
