### ISSUE TITLE
Wrong faction

### ISSUE THREAD

**Issue by AlvinZhu** [ZhengPeiRu21/mod-individual-progression#94]
/*  Summoned Felhunter  */
-- UPDATE `creature_template` SET `faction` = 35 WHERE `entry` = 6268;

/*  Chambermaid Pillaclencher  */
-- UPDATE `creature_template` SET `faction` = 35 WHERE `entry` = 14636;

quest: The Binding(1795), Summoned Felhunter should be killed by player. so the faction is not "Friendly"(35)
Chambermaid Pillaclencher is another creature should be killed by player to Complete a quest.

May I ask why do you have to modify so much faction data ? In particular, many creature have been turned from hostile to friendly
and where do you get the data from?

**Comment by ZhengPeiRu21** [comment]
Once again I'd like to say, I appreciate your reports and feedback. The faction data is mostly coped from Vmangos. The goal is to change creatures that were changed from aggressive to passive after Vanilla back to the correct aggressive factions. However, it has led to several bugs like this. If it seems like these changes are causing many issues, I can consider a more careful method of fixing factions, but if there are only a few individual issues that can be fixed, I will fix them individually. I will go ahead and fix these cases you have identified - please let me know your thoughts if you think there is a better method or if you find other faction issues.

**Comment by AlvinZhu** [comment]
我发现奥达曼有很多怪物包括最终BOSS被设置成了faction35 Friendly，所以我重新检查了一下vanilla_mob_factions.sql。修改的数据太多了，我没办法一一比对。
所以我采用了抽查的方法来评估了一些faction设置为35的creature。总体上对这些数据的质量不太乐观：
1 如果原来在azerothcore master中设置为敌对状态的，现在改成了faction35 Friendly，基本上都是错的。
2 如果原来在azerothcore master中设置为对玩家友善的阵营(并非35,而是更具体的友善阵营，比如Stormwind)。大多数虽然不影响游戏内容，但是却丢失了阵营的细节，被笼统的设置成立faction35 Friendly。
3 这个文件中修改，从名字来看，很多是已弃用、召唤物、环境装饰物、或后续版本的内容（比如战斗小宠物），所以大多数的修改在游戏中感受不到，可能是这个原因造成了这份数据还行的错觉。

一下是在抽查过程中发现的明显错误的数据：
```
diff --git a/sql/world/base/vanilla_mob_factions.sql b/sql/world/base/vanilla_mob_factions.sql
index 6cfa0c7..6acfe57 100644
--- a/sql/world/base/vanilla_mob_factions.sql
+++ b/sql/world/base/vanilla_mob_factions.sql
@@ -379,9 +379,6 @@ UPDATE `creature_template` SET `faction` = 32 WHERE `entry` = 2707;
 /*  Shadowforge Commander  */
 UPDATE `creature_template` SET `faction` = 14 WHERE `entry` = 2744;
 
-/*  Archaedas  */
-UPDATE `creature_template` SET `faction` = 35 WHERE `entry` = 2748;
-
 /*  Siege Golem  */
 UPDATE `creature_template` SET `faction` = 91 WHERE `entry` = 2749;
 
@@ -793,9 +790,6 @@ UPDATE `creature_template` SET `faction` = 128 WHERE `entry` = 4827;
 /*  Old Serra'kis  */
 UPDATE `creature_template` SET `faction` = 128 WHERE `entry` = 4830;
 
-/*  Stone Keeper  */
-UPDATE `creature_template` SET `faction` = 35 WHERE `entry` = 4857;
-
 /*  Guard Jarad  */
 UPDATE `creature_template` SET `faction` = 151 WHERE `entry` = 4923;
 
@@ -979,9 +973,6 @@ UPDATE `creature_template` SET `faction` = 128 WHERE `entry` = 6047;
 /*  Earthgrab Totem  */
 UPDATE `creature_template` SET `faction` = 16 WHERE `entry` = 6066;
 
-/*  Warug's Bodyguard  */
-UPDATE `creature_template` SET `faction` = 35 WHERE `entry` = 6068;
-
 /*  Bartleby  */
 UPDATE `creature_template` SET `faction` = 12 WHERE `entry` = 6090;
 
@@ -1057,12 +1048,6 @@ UPDATE `creature_template` SET `faction` = 92 WHERE `entry` = 6932;
 /*  Agent Kearnen  */
 UPDATE `creature_template` SET `faction` = 11 WHERE `entry` = 7024;
 
-/*  Earthen Guardian  */
-UPDATE `creature_template` SET `faction` = 35 WHERE `entry` = 7076;
-
-/*  Earthen Hallshaper  */
-UPDATE `creature_template` SET `faction` = 35 WHERE `entry` = 7077;
-
 /*  Jadefire Rogue  */
 UPDATE `creature_template` SET `faction` = 90 WHERE `entry` = 7106;
 
@@ -1081,9 +1066,6 @@ UPDATE `creature_template` SET `faction` = 11 WHERE `entry` = 7266;
 /*  [UNUSED] Drayl  */
 UPDATE `creature_template` SET `faction` = 105 WHERE `entry` = 7293;
 
-/*  Earthen Custodian  */
-UPDATE `creature_template` SET `faction` = 35 WHERE `entry` = 7309;
-
 /*  Lady Sathrah  */
 UPDATE `creature_template` SET `faction` = 22 WHERE `entry` = 7319;
 
@@ -1588,9 +1570,6 @@ UPDATE `creature_template` SET `faction` = 32 WHERE `entry` = 10042;
 /*  Deathmaw  */
 UPDATE `creature_template` SET `faction` = 14 WHERE `entry` = 10077;
 
-/*  Vault Warder  */
-UPDATE `creature_template` SET `faction` = 35 WHERE `entry` = 10120;
-
 /*  Rookery Whelp  */
 UPDATE `creature_template` SET `faction` = 14 WHERE `entry` = 10161;
 
@@ -1762,9 +1741,6 @@ UPDATE `creature_template` SET `faction` = 119 WHERE `entry` = 10928;
 /*  Captain Redpath  */
 UPDATE `creature_template` SET `faction` = 113 WHERE `entry` = 10937;
 
-/*  Marduk the Black  */
-UPDATE `creature_template` SET `faction` = 35 WHERE `entry` = 10939;
-
 /*  Davil Lightfire  */
 UPDATE `creature_template` SET `faction` = 113 WHERE `entry` = 10944;
 

```
