### ISSUE TITLE
Creature Bragor Bloodfist(36273) removed. The quest associated with him could not be completed

### ISSUE THREAD

**Issue by AlvinZhu** [ZhengPeiRu21/mod-individual-progression#98]
Creature Bragor Bloodfist(36273) removed. The quest associated with him could not be completed

**The quest associated with Bragor Bloodfist should be given to Varimathras(2425). Just like in TBC or Vanilla:**
DELETE FROM `creature_questender` WHERE `id` = 36273 AND `quest` = 6144;
DELETE FROM `creature_questender` WHERE `id` = 36273 AND `quest` = 14351;
DELETE FROM `creature_questender` WHERE `id` = 36273 AND `quest` = 14352;
DELETE FROM `creature_questender` WHERE `id` = 36273 AND `quest` = 14353;
DELETE FROM `creature_questender` WHERE `id` = 36273 AND `quest` = 14355;
DELETE FROM `creature_questender` WHERE `id` = 36273 AND `quest` = 14356;
REPLACE INTO `creature_questender` (`id`, `quest`) VALUES (2425, 6144);
REPLACE INTO `creature_questender` (`id`, `quest`) VALUES (2425, 14351);
REPLACE INTO `creature_questender` (`id`, `quest`) VALUES (2425, 14352);
REPLACE INTO `creature_questender` (`id`, `quest`) VALUES (2425, 14353);
REPLACE INTO `creature_questender` (`id`, `quest`) VALUES (2425, 14355);
REPLACE INTO `creature_questender` (`id`, `quest`) VALUES (2425, 14356);
DELETE FROM `creature_queststarter` WHERE `id` = 36273 AND `quest` = 14353;
REPLACE INTO `creature_queststarter` (`id`, `quest`) VALUES (2425, 14353);

**and the quest_template_locale and item_template_locale:**
UPDATE `item_template_locale` SET `Description` = '瓦里玛萨斯大人亲启。' WHERE `ID` = '3701' AND `locale` = 'zhCN';
UPDATE `quest_template_locale` SET `Objectives` = '把玛克林大使的头颅交给幽暗城的瓦里玛萨斯。', `CompletedText` = '转至幽暗城，去找皇家区的瓦里玛萨斯。' WHERE `ID` = '6521' AND `locale` = 'zhCN';
UPDATE `quest_template_locale` SET `Details` = '由于你在希尔斯布莱德战役中的英勇表现，我已经向上级写了这封褒奖状以表扬你。$b$b，带着这封密封的褒奖状去见幽暗城的瓦里玛萨斯吧。你可以满怀骄傲地去见他，$c。', `Objectives` = '把达萨利亚的密封褒奖状交给幽暗城的瓦里玛萨斯。', `CompletedText` = '去幽暗城找皇家区的瓦里玛萨斯。' WHERE `ID` = '14351' AND `locale` = 'zhCN';
UPDATE `quest_template_locale` SET `Objectives` = '把小卷轴交给幽暗城的瓦里玛萨斯。', `CompletedText` = '去幽暗城找皇家区的瓦里玛萨斯。' WHERE `ID` = '14352' AND `locale` = 'zhCN';
UPDATE `quest_template_locale` SET `Objectives` = '将玛克林大师的信物交给幽暗城的瓦里玛萨斯。', `CompletedText` = '去幽暗城找皇家区的瓦里玛萨斯。' WHERE `ID` = '14353' AND `locale` = 'zhCN';
UPDATE `quest_template_locale` SET `Objectives` = '消灭大检察官怀特迈恩、血色十字军指挥官莫格莱尼、血色十字军勇士赫洛德和驯犬者洛克希，然后向幽暗城的瓦里玛萨斯报告。', `CompletedText` = '去幽暗城找皇家区的瓦里玛萨斯。' WHERE `ID` = '14355' AND `locale` = 'zhCN';
UPDATE `quest_template_locale` SET `Objectives` = '将《暗影法术研究》和《扭曲虚空的魔法》这两本书交给幽暗城的瓦里玛萨斯。', `CompletedText` = '去幽暗城找皇家区的瓦里玛萨斯。' WHERE `ID` = '14356' AND `locale` = 'zhCN';

Sorry, I only made changes to the Chinese version, you may also want to change the English version, so I did not create a new PR.

**Comment by ZhengPeiRu21** [comment]
Thank you so much! I really appreciate your reports, and especially you include a solution. I'll add this and the English equivalent.
